### ISSUE TITLE
RMagick ignoring border_color

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#1]
<a href="https://github.com/rggjan"><img src="https://avatars.githubusercontent.com/u/128554?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rggjan](https://github.com/rggjan)**
_Tuesday Feb 23, 2010 at 13:50 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/1_

---

With this code:

``` ruby
#!/usr/bin/ruby
require 'RMagick'
include Magick

imagelist=ImageList.new('/home/jan/Desktop/test.jpg')

collage = imagelist.montage do
  self.border_color='red'
  self.border_width=10
  self.geometry=Geometry.new(500, 500)
end

collage.write('/home/jan/Desktop/test_collage.jpg')

IMGCOMMAND="-border 10x10 -bordercolor red -geometry 500x500 /home/jan/Desktop/test_collage_original.jpg"
system "montage /home/jan/Desktop/test.jpg " + IMGCOMMAND
```

A red border is created with the original imagemagick (test_collage_original) while it is white with Rmagick (test_collage). It should be red in both cases...

**Comment by vassilevsky** [comment]
I was tracing sources to understand how `self.border_color = 'red'` works and noticed that the `Color_to_PixelPacket` function receives a pointer to `montage->info->border_color`, but if the color is specified as a string, it passes the pointer further to the `Color_Name_to_PixelPacket` function, but already as a value. My knowledge of C is quite vague, so I'm not sure if this is normal.
