### ISSUE TITLE
failed with error: identify-im6.q16: width or height exceeds limit

### ISSUE THREAD

**Issue by johan-smits** [rmagick/rmagick#1125]
I had opened an issue at minimagick/minimagick#504 but it seems to be an imagemagic issue.

How are images with a really large size (19190x10790) handled? Or how to catch this gracefully?

```
A MiniMagick::Error occurred in background at 2020-03-04 01:11:28 UTC :

  `identify -format %[orientation] /tmp/ActiveStorage-81766-20200304-12-1a8fnr4[0]` failed with error:
identify-im6.q16: width or height exceeds limit `/tmp/ActiveStorage-81766-20200304-12-1a8fnr4' @ error/cache.c/OpenPixelCache/3912.

  /var/app/current/vendor/bundle/ruby/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/shell.rb:17:in `run'
```

**Comment by mockdeep** [comment]
@johan-smits it looks like you're using `MiniMagick` not RMagick. Perhaps you should report your issue [over there](https://github.com/minimagick/minimagick).

**Comment by mockdeep** [comment]
Nevermind, just saw your comment about it being an ImageMagick issue. You should instead report your issue [to them](https://github.com/ImageMagick/ImageMagick).
