### ISSUE TITLE
RMagick 4.1.0

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#1152]
I think there is no blocker any more to release RMagick 4.1.0-rc3 or RMagick 4.1.0.

@mockdeep @dlemstra

**Comment by mockdeep** [comment]
Great! I'll try to get `rc3` out this week. If we don't hear any new issues for a month we can release `4.1.0`.

**Comment by Watson1978** [comment]
Any progress on this? :)

**Comment by mockdeep** [comment]
Okay, version 4.1.0 is live: https://rubygems.org/gems/rmagick/versions/4.1.0
