### ISSUE TITLE
ERROR: Can't install RMagick 4.0.0. Can't find ImageMagick with pkg-config

### ISSUE THREAD

**Issue by MMacku** [rmagick/rmagick#1153]
Hello, I upgraded imagemagick version to `6.9.11` and when i try install rmagick gem, i get following error:

```
# mkmf.log

find_executable: checking for brew... -------------------- yes
--------------------
find_executable: checking for gcc... -------------------- yes
--------------------
find_executable: checking for pkg-config... -------------------- yes
--------------------
ERROR: Can't install RMagick 4.0.0. Can't find ImageMagick with pkg-config
```

```
current directory: /Users/michalmacku/.rvm/gems/ruby-2.6.5/gems/rmagick-4.1.0.rc2/ext/RMagick
/Users/michalmacku/.rvm/rubies/ruby-2.6.5/bin/ruby -I /Users/michalmacku/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0 -r ./siteconf20200309-20030-8vw80k.rb extconf.rb
checking for brew... yes
checking for gcc... yes
checking for pkg-config... yes


[31m[1mERROR: Can't install RMagick 4.1.0.rc2. Can't find ImageMagick with pkg-config
[0m

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/michalmacku/.rvm/rubies/ruby-2.6.5/bin/$(RUBY_BASE_NAME)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/michalmacku/.rvm/gems/ruby-2.6.5/extensions/x86_64-darwin-19/2.6.0/rmagick-4.1.0.rc2/mkmf.log

extconf failed, exit code 1
```

I had installed `pkg-config` on my system. I tried to reinstall imagemagick and pkg-config but problem persists. Similar problem looks like https://github.com/rmagick/rmagick/issues/956 but that solution not working for me. Imagemagick version `6.9.10` working without problem, but after upgrade it via Homebrew i cannot go back to previous version. 

My operating system is MacOS.

**Comment by Watson1978** [comment]
If you install ImageMagick to a custom directory, you can specify the location with `PKG_CONFIG_PATH` of `pkg-config`'s environment variable.

```
export PKG_CONFIG_PATH=$HOME/imagemagick6.9/lib/pkgconfig
```

After then, it could look up the ImageMagick library.

**Comment by MMacku** [comment]
@Watson1978 Thank you for your response. I tried `export PKG_CONFIG_PATH="/usr/local/opt/imagemagick@6/lib/pkgconfig"` from postinstall message of imagemagick:
```
For pkg-config to find imagemagick@6 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/imagemagick@6/lib/pkgconfig"
```

And i get same error message when i try to install rmagick. I also try install rmagick `4.1.0.rc2` and it shows same error.

**Comment by Watson1978** [comment]
Can you paste the following command log?

```
$ export PKG_CONFIG_PATH="/usr/local/opt/imagemagick@6/lib/pkgconfig"
$ pkg-config --list-all
```

**Comment by MMacku** [comment]
```
$ export PKG_CONFIG_PATH="/usr/local/opt/imagemagick@6/lib/pkgconfig"
$ pkg-config --list-all
zsh: segmentation fault  pkg-config --list-all
```

**Comment by Watson1978** [comment]
Looks like `pkg-config` on your sysytem have some damage...
You need to solve the segmentation fault at first.
You may solve to reinstall `pkg-config`. (ex `brew reinstall --force pkgconfig`)

**Comment by walkah** [comment]
I am seeing this same behaviour - segfault from `pkg-config --list-all`, tried force reinstalling and building from source and `--list-all` continues to segfault.

However, `pkg-config --cflags imagemagick` and `pkg-config --libs imagemagick` both work:

```
$ pkg-config --libs imagemagick
-L/usr/local/Cellar/imagemagick@6/6.9.11-0/lib -lMagickCore-6.Q16
$ pkg-config --cflags imagemagick
-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.11-0/include/ImageMagick-6
```

homebrew recently updated imagemagick to 6.9.11 ... perhaps that's related?

**Comment by Watson1978** [comment]
I tried to reproduce this on my macOS. However, I can't reproduce.
I need more information...

**Comment by volleio** [comment]
I was blocked by this as well with the same `pkg-config --list-all` segfault behavior. Changing the env variables `PKG_CONFIG_PATH` and `PKG_CONFIG_LIBDIR` didn't seem to change the paths used, which I believe can be checked by running `pkg-config --variable pc_path pkg-config`. I was able to debug that by running
`pkg-config --debug --list-all`
which segfaulted while `Parsing package file '/usr/local/lib/pkgconfig/proj.pc'`. The [package Proj](https://github.com/OSGeo/PROJ/releases) was updated 11 days ago and that running 
`pkg-config --exists --print-errors "proj"` 
results in `Variable 'datarootdir' not defined in '/usr/local/lib/pkgconfig/proj.pc'`. Removing /usr/local/lib/pkgconfig/proj.pc (renaming it to proj.pc.backup) and re-running the RMagick install succeeded! 
Will be opening an issue for `PROJ`, and attempting to downgrade `PROJ` from 7.0.0 for now. 
Hope this helps! Doesn't seem to be an issue with RMagick, although maybe the [determine_imagemagick_package](https://github.com/rmagick/rmagick/blob/24a1ef99377813e5c7a45bf6cdf5c6b05072cf45/ext/RMagick/extconf.rb#L119) method could be modified to not use `--list-all` as a workaround.

**Comment by walkah** [comment]
@volleio  just tried this and can confirm - it fixes the problem and rmagick once again installs cleanly. Thank you for taking the time to dig deeper on this!

**Comment by volleio** [comment]
@walkah Great to hear!

**Comment by volleio** [comment]
This issue is being fixed in [PROJ#2067](https://github.com/OSGeo/PROJ/pull/2067). Workaround possible by [updating proj.pc to include datarootdir](https://github.com/OSGeo/PROJ/issues/2064#issuecomment-598439532)!

**Comment by MMacku** [comment]
@volleio Thank you, renaming/removing proj.pc fixed problem with installation of gem 👍

**Comment by VictorMotogna** [comment]
Unfortunately I still get the same error and also the rmagick installation issue:
```
pkg-config --list-all
[1]    664 segmentation fault  pkg-config --list-all
```

pkg-config has version 0.29.2, I tried both removing the `proj.pc` file and changing it to the details from [this comment](https://github.com/OSGeo/PROJ/issues/2064#issuecomment-598439532).

`pkg-config --exists --print-errors "proj"` even returns nothing, so I don't think there's an error on that side. 

I managed to fix the issue by uninstall highway (`brew uninstall highway`), because it has a conflict over a variable. Running `pkg-config --debug --list-all` will show that.

**Comment by Watson1978** [comment]
@VictorMotogna I filed the issue in https://github.com/rmagick/rmagick/issues/1358

**Comment by 2voyager** [comment]
Hi @VictorMotogna  your comment was very helpful. but after unnstalling highway, and trying `gem install rmagick` I get this error

- I am using ruby 3 
- 

```
make "DESTDIR="
compiling rmagick.c
In file included from rmagick.c:13:
./rmagick.h:67:14: fatal error: 'MagickCore/MagickCore.h' file not found
    #include "MagickCore/MagickCore.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [rmagick.o] Error 1

make failed, exit code 2

**Comment by nachiket87** [comment]
> Hi @VictorMotogna your comment was very helpful. but after unnstalling highway, and trying `gem install rmagick` I get this error
> 
> * I am using ruby 3
> 
> ```
> make "DESTDIR="
> compiling rmagick.c
> In file included from rmagick.c:13:
> ./rmagick.h:67:14: fatal error: 'MagickCore/MagickCore.h' file not found
>     #include "MagickCore/MagickCore.h"
>              ^~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> make: *** [rmagick.o] Error 1
> 
> make failed, exit code 2
> ```

Hey @2voyager, you can try uninstalling highway, then installing rmagick, then reinstalling highway again.

**Comment by 2voyager** [comment]
Thanks @nachiket87  I did try un-installing and then installing rmagick but then `pkg-config` seg faults again, with same error. I will try again and update here.

**Comment by asecondwill** [comment]
is there a longer term fix planned than the current workaround to 

brew install pkg-config imagemagick
brew  uninstall highway
bundle install
brew install highway

?

**Comment by hypogealgaol** [comment]
For me, the issue was not with `proj.pc` but with `libhwy-test`. Running an Apple M1 Pro Chip. Ran the same solution as above and could install rmagick fine. I don't like the idea of just removing a file for what seems like a dependency but I will say that it worked.

```
Reading '/opt/homebrew/lib/pkgconfig/libhwy-test.pc' from file '/opt/homebrew/lib/pkgconfig/libhwy-test.pc'
Parsing package file '/opt/homebrew/lib/pkgconfig/libhwy-test.pc'
  line>prefix=/opt/homebrew/Cellar/highway/1.0.1
 Variable declaration, 'prefix' has value '/opt/homebrew/Cellar/highway/1.0.1'
  line>libdir=${exec_prefix}/lib
[1]    81028 segmentation fault  pkg-config --debug --list-all
❯ pkg-config --exists --print-errors "libhwy-test"
Variable 'exec_prefix' not defined in '/opt/homebrew/lib/pkgconfig/libhwy-test.pc'
```

**Comment by cryptic-mystic** [comment]
> is there a longer term fix planned than the current workaround to
> 
> ```
> brew install pkg-config imagemagick
> brew  uninstall highway
> bundle install
> brew install highway
> ```
> 
> ?

This worked for me!

**Comment by tpetrone** [comment]
It seems that is a long term fix on it way
https://github.com/rmagick/rmagick/pull/1359

**Comment by asecondwill** [comment]
Great.  thanks everybody!
