### ISSUE TITLE
Image#preview generate different image with ImageMagick 7

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#1160]
## Test code
https://github.com/rmagick/rmagick/blob/master/doc/ex/preview.rb

### Result
with IM6 | with IM7
-- | --
<img src="https://user-images.githubusercontent.com/199156/76685412-c665c380-6656-11ea-9dc1-9d5cd6f4d40d.jpg"> | <img src="https://user-images.githubusercontent.com/199156/76685420-d7163980-6656-11ea-90ff-e266a433c809.jpg">

**Comment by Watson1978** [comment]
@dlemstra I think the difference is related to ImageMagick internally. What do you think about this issue ?

**Comment by dlemstra** [comment]
Thanks for alterting us to this. Just pushed a patch to resolve this for ImageMagick 7.

**Comment by Watson1978** [comment]
I confirmed Magick::SolarizePreview works well with https://github.com/ImageMagick/ImageMagick/commit/d2df4d1d7a3f6ea8259caaf0547f9d4c72e3e764

**Comment by Watson1978** [comment]
When I used `CharcoalDrawingPreview`, it generates wrong images

## Test code
```ruby
require 'rmagick'

img = Magick::Image.read('images/Flower_Hat.jpg').first
preview = img.preview(Magick::CharcoalDrawingPreview)
preview.minify.write("preview.jpg")
```


### Result
with IM6 | with IM7
-- | --
<img src="https://user-images.githubusercontent.com/199156/76706048-05b01500-6728-11ea-8e9b-50f85cff6484.jpg"> | <img src="https://user-images.githubusercontent.com/199156/76706054-13659a80-6728-11ea-9f16-c02f2b64849a.jpg">

@dlemstra Can you also fix this ?

**Comment by dlemstra** [comment]
I cannot reproduce your issue on the command line with the latest version of ImageMagick 7. This works for me: `magick Flower_Hat.jpg  -preview Charcoal test.png`

**Comment by Watson1978** [comment]
Hmm, `magick Flower_Hat.jpg -preview Charcoal test.png` generates the same wrong image on my macOS.

I used ImageMagick 7 with the latest master branch code and configured with `CFLAGS='-O0 -ggdb3' ./configure --prefix=$HOME/imagemagick7.0 --without-xml`...

Something wrong?

**Comment by dlemstra** [comment]
There seems to be a difference with the OpenCL operations. If I disable OpenCL I also get the incorrect result. Will need to investigate.

**Comment by dlemstra** [comment]
This issue should be resolved in the `master` now @Watson1978.

**Comment by Watson1978** [comment]
I confirmed this issue should be fixed.

Thanks!! (https://github.com/ImageMagick/ImageMagick/commit/cc5b1c571916ac72df92206f121033796b4e9eb4)
