### ISSUE TITLE
rmagick 4.1.1: #error "<malloc.h> has been replaced by <stdlib.h>" during build native extension on FreeBSD 12.1

### ISSUE THREAD

**Issue by VVD** [rmagick/rmagick#1197]
### Description

#error "<malloc.h> has been replaced by <stdlib.h>" during build native extension

### Steps to Reproduce

gem install rmagick

### System Configuration

- ImageMagick version: 6.9.10.90
- RMagick version: 4.1.1
- Ruby version: 2.6.6
- Environment (Operating system, version and so on): FreeBSD 12.1 amd64
- Additional information: after replace "#include <malloc.h>" with "#include <stdlib.h>" in ext/RMagick/rmmain.c build and install without errors.

**Comment by VVD** [comment]
[malloc.h](https://svnweb.freebsd.org/base/releng/12.1/include/malloc.h?revision=352546&view=markup):
```
/* $FreeBSD: releng/12.1/include/malloc.h 86178 2001-11-07 23:14:31Z obrien $ */
#if __STDC__
#error "<malloc.h> has been replaced by <stdlib.h>"
#else
#include <stdlib.h>
#endif
```

**Comment by VVD** [comment]
This commit is related to this issue: https://github.com/rmagick/rmagick/commit/79f505762bdc47a3426246e5379ad5753deb2099#diff-102eb8794350d8570f3a50cc4d0483ef

**Comment by Watson1978** [comment]
I think this issue should be resolved with master code.
Can you try it ?

**Comment by VVD** [comment]
> I think this issue should be resolved with master code.
> Can you try it ?
Tested - build fine on my environment now.
Thanks!

Is release 4.1.2 soon? :-)

**Comment by Watson1978** [comment]
@mockdeep Can you release RMagick v4.1.2 to fix build error on FreeBSD?

**Comment by VVD** [comment]
I found one more bug related to ImageMagick7 on FreeBSD.
I'm preparing report now.

**Comment by VVD** [comment]
@Watson1978, #1201.
