### ISSUE TITLE
Can't install RMagick 4.1.0 after Ubuntu upgrade from 16.04 to 18.04

### ISSUE THREAD

**Issue by janosrusiczki** [rmagick/rmagick#1198]
### Description
I updated Ubuntu from 16.04 to 18.04 and now I can't install RMagick 4.1.0.

After installing what I think is necessary (imagemagick, libmagickcore-dev and libmagickwand-dev) I'm getting:

```
current directory: /home/dev/.rvm/gems/ruby-2.6.5/gems/rmagick-4.1.0/ext/RMagick
/home/dev/.rvm/rubies/ruby-2.6.5/bin/ruby -I /home/dev/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0 -r
./siteconf20200407-30084-1iqnbms.rb extconf.rb
checking for brew... no
checking for pacman... no
checking for Ruby version >= 2.3.0... yes
checking for pkg-config... yes
checking for forced use of ImageMagick 6... no
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for gcc... yes
checking for __GNUC__... yes
checking for MagickCore/MagickCore.h... no
checking for magick/MagickCore.h... no

ERROR: Can't install RMagick 4.1.0. Can't find magick/MagickCore.h.

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```
I found `MagickCore/MagitckCore.h` in `/usr/include/ImageMagick-7/` but for some reason that directory is not included in the path search.

### Steps to Reproduce
* `sudo apt install imagemagick libmagickcore-dev libmagickwand-dev`
* `bundle install`

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-0 Q16 x86_64 2020-03-15
- RMagick version: 4.1.0
- Ruby version: 2.6.5
- Environment (Operating system, version and so on): Ubuntu 18.04
- Additional information:

**Comment by janosrusiczki** [comment]
I think it's an Ubuntu upgrade issue. I spun up a new virtual machine with 18.04 and the issue disappeared.

**Comment by Watson1978** [comment]
@janosrusiczki Thank you for confirming this.

I will close this issue.
Feel free to re-open if you needed.
