### ISSUE TITLE
Build error "unable to find library -lMagickCore-7.Q16HDRI" with ImageMagick 7 on FreeBSD 12.1

### ISSUE THREAD

**Issue by VVD** [rmagick/rmagick#1201]
### Description

Error "ld: error: unable to find library -lMagickCore-7.Q16HDRI" during build native extension.

### Steps to Reproduce

gem install rmagick

### System Configuration

- ImageMagick version: 7.0.9.20
- RMagick version: 4.1.1
- Ruby version: 2.6.6
- Environment (Operating system, version and so on): FreeBSD 12.1 amd64
- Additional information:
ls /usr/local/lib/libMagickCore*
/usr/local/lib/libMagickCore-7.a
/usr/local/lib/libMagickCore-7.la
/usr/local/lib/libMagickCore-7.so
/usr/local/lib/libMagickCore-7.so.7
/usr/local/lib/libMagickCore-7.so.7.0.0

ImageMagick7 build options (with ImageMagick6 with same options rmagick build fine):
OPTIONS_FILE_SET+=16BIT_PIXEL
OPTIONS_FILE_SET+=BZIP2
OPTIONS_FILE_SET+=DJVU
OPTIONS_FILE_UNSET+=DOCS
OPTIONS_FILE_SET+=FFTW
OPTIONS_FILE_SET+=FONTCONFIG
OPTIONS_FILE_SET+=FPX
OPTIONS_FILE_SET+=FREETYPE
OPTIONS_FILE_SET+=GRAPHVIZ
OPTIONS_FILE_SET+=GSLIB
OPTIONS_FILE_SET+=HDRI
OPTIONS_FILE_SET+=HEIF
OPTIONS_FILE_SET+=JBIG
OPTIONS_FILE_SET+=JPEG
OPTIONS_FILE_SET+=JPEG2000
OPTIONS_FILE_SET+=LCMS2
OPTIONS_FILE_SET+=LQR
OPTIONS_FILE_SET+=LZMA
OPTIONS_FILE_SET+=MODULES
OPTIONS_FILE_SET+=OPENEXR
OPTIONS_FILE_SET+=OPENMP
OPTIONS_FILE_SET+=PANGO
OPTIONS_FILE_SET+=PDF
OPTIONS_FILE_SET+=PERL
OPTIONS_FILE_SET+=PNG
OPTIONS_FILE_SET+=RAQM
OPTIONS_FILE_SET+=RAW
OPTIONS_FILE_SET+=SVG
OPTIONS_FILE_UNSET+=TESTS
OPTIONS_FILE_SET+=THREADS
OPTIONS_FILE_SET+=TIFF
OPTIONS_FILE_SET+=WEBP
OPTIONS_FILE_SET+=WMF
OPTIONS_FILE_SET+=X11

After turn off HDRI it want MagickCore-7.Q16, after turn off 16BIT_PIXEL - MagickCore-7.Q8.
AFAIR, in the past rmagick had same issue with ImageMagick6 with HDRI build option on.

**Comment by Watson1978** [comment]
The installation process of RMagick depends on pkg-config.
The value returned by pkg-config doesn't seem to match the actual file.

```
% uname -a
FreeBSD watson-ghostbsd-pc 12.1-STABLE FreeBSD 12.1-STABLE GENERIC  amd64

% sudo pkg install ImageMagick7-7.0.9.20
Updating GhostBSD repository catalogue...
GhostBSD repository is up to date.
Updating GhostBSD_PKG repository catalogue...
GhostBSD_PKG repository is up to date.
All repositories are up to date.
The following 13 package(s) will be affected (of 0 checked):
....


% pkg-config --libs ImageMagick
-L/usr/local/lib -lMagickCore-7.Q16HDRI


% ls -la /usr/local/lib/libMagick*
-rw-r--r--  1 root  wheel  1068126  3月 30 23:15 /usr/local/lib/libMagick++-7.a
-rwxr-xr-x  1 root  wheel      967  3月 30 23:25 /usr/local/lib/libMagick++-7.la
lrwxr-xr-x  1 root  wheel       22  3月 30 23:15 /usr/local/lib/libMagick++-7.so -> libMagick++-7.so.4.0.0
lrwxr-xr-x  1 root  wheel       22  3月 30 23:15 /usr/local/lib/libMagick++-7.so.4 -> libMagick++-7.so.4.0.0
-rwxr-xr-x  1 root  wheel   668224  3月 30 23:15 /usr/local/lib/libMagick++-7.so.4.0.0
-rw-r--r--  1 root  wheel  4656704  3月 30 23:15 /usr/local/lib/libMagickCore-7.a
-rwxr-xr-x  1 root  wheel      981  3月 30 23:25 /usr/local/lib/libMagickCore-7.la
lrwxr-xr-x  1 root  wheel       24  3月 30 23:15 /usr/local/lib/libMagickCore-7.so -> libMagickCore-7.so.7.0.0
lrwxr-xr-x  1 root  wheel       24  3月 30 23:15 /usr/local/lib/libMagickCore-7.so.7 -> libMagickCore-7.so.7.0.0
-rwxr-xr-x  1 root  wheel  2664856  3月 30 23:15 /usr/local/lib/libMagickCore-7.so.7.0.0
-rw-r--r--  1 root  wheel  2514200  3月 30 23:15 /usr/local/lib/libMagickWand-7.a
-rwxr-xr-x  1 root  wheel      981  3月 30 23:25 /usr/local/lib/libMagickWand-7.la
lrwxr-xr-x  1 root  wheel       24  3月 30 23:15 /usr/local/lib/libMagickWand-7.so -> libMagickWand-7.so.7.0.0
lrwxr-xr-x  1 root  wheel       24  3月 30 23:15 /usr/local/lib/libMagickWand-7.so.7 -> libMagickWand-7.so.7.0.0
-rwxr-xr-x  1 root  wheel  1309320  3月 30 23:15 /usr/local/lib/libMagickWand-7.so.7.0.0
```

It is better to report this to ImageMagick or to FreeBSD package maintainer.

@dlemstra Do you know of any problems on ImageMagick for FreeBSD related to this issue?

**Comment by VVD** [comment]
```
% pkg-config --libs MagickCore
-L/usr/local/lib -lMagickCore-7
```

**Comment by Watson1978** [comment]
We are using package names that start with ImageMagick.
https://github.com/rmagick/rmagick/blob/60f613e3d0b5dc0449868ad3d90920a83ee66b59/ext/RMagick/extconf.rb#L119-L156

**Comment by VVD** [comment]
Wrote question about Q16HDRI to the maintainer - waiting answer.

Just for information:
```
$ pkg-config --libs MagickCore
-L/usr/local/lib -lMagickCore-7 
$ pkg-config --libs ImageMagick
-L/usr/local/lib -lMagickCore-7.Q16HDRI
$ pkg-config --libs MagickCore
-L/usr/local/lib -lMagickCore-6 
$ pkg-config --libs ImageMagick
-L/usr/local/lib -lMagickCore-6
```

**Comment by VVD** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245557

**Comment by VVD** [comment]
It was just fixed in FreeBSD's ports.
