### ISSUE TITLE
Gem not compatible with latest ImageMagick 7.0.10.8

### ISSUE THREAD

**Issue by julienchabanon** [rmagick/rmagick#1210]
Hi !

I am running Manjaro and the latest ImageMagick version is 7.0.10.8 which is not compatible with the gem. 

Thanks

**Comment by dlemstra** [comment]
And the error you are receiving is?

**Comment by Watson1978** [comment]
I've updated my version of CI, but there is no problem.
we need more information.

**Comment by julienchabanon** [comment]
When I fetch from rubygems, I get the version 4.1.2 which raise on rails s:
`Gem Load Error is: This installation of RMagick was configured with ImageMagick 7.0.9 but ImageMagick 7.0.10-8 is in use.`

When I fetch from git, it appears to works. But unfortunately my gemfile cant be using a git reference.

Thanks

**Comment by Watson1978** [comment]
I think you just need to reinstall RMagick after updated ImageMagick.

**Comment by julienchabanon** [comment]
@Watson1978 thanks, uninstalling and reinstalling the gem fixed the issue. Thanks for your fast answers!

**Comment by Watson1978** [comment]
Thank you for response.

we have checked the Imagemagick version that the installed version matches the runtime.

https://github.com/rmagick/rmagick/blob/4c9cd1058595c70c647d0f4e965fa1d2546e2767/ext/RMagick/rmmain.c#L1846

I will close this.
Thanks
