### ISSUE TITLE
Problem on install the Rmagick gem 4.1.2 in a rails 6 proyect

### ISSUE THREAD

**Issue by HenryGlo** [rmagick/rmagick#1237]
When i try to run *bundle install* in my rails 6 proyect i get this Error: 

![image (3)](https://user-images.githubusercontent.com/43855485/94175552-d27fd880-fe64-11ea-94e5-ea1fcfa9b61a.png)

***I TRIED*** everything: Downgrade ImageMagick to version 6.9, install the new version of ImageMagick(7.0) and reinstall all the packages of ubuntu imagemagick, libmagick++dev, etc..

PD: When i install Rmagick gem 2.13.2 i dont get any error

**PLEASE HELP ME!**

**Comment by mockdeep** [comment]
@HenryGlo can you share the versions of ImageMagick you used, including patch level? If you're not on the latest patch level there may be issues.

**Comment by HenryGlo** [comment]
> @HenryGlo can you share the versions of ImageMagick you used, including patch level? If you're not on the latest patch level there may be issues.

Version: ImageMagick 6.9.11-30 Q16 x86_64 2020-09-23 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype jbig jng jpeg lcms lqr lzma openexr png tiff wmf x xml zlib

**Comment by dlemstra** [comment]
It looks like ImageMagick 7 was used and it should then find `SetImageGray` in the headers. But for some reason this was not found?

**Comment by HenryGlo** [comment]
Thank you very much everyone for your help!, @Watson1978 solution worked perfectly for me, uninstall version 7 of ImageMagick!
