### ISSUE TITLE
error when installing rmagick on mac os

### ISSUE THREAD

**Issue by rohitkumarrana67** [rmagick/rmagick#1242]
Building native extensions. This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    current directory: /Users/rohit/.rvm/gems/ruby-2.6.3@Rails5.2.3_performance-management/gems/rmagick-3.1.0/ext/RMagick
/Users/rohit/.rvm/rubies/ruby-2.6.3/bin/ruby -I /Users/rohit/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0 -r ./siteconf20201008-41529-k85z1g.rb extconf.rb
checking for brew... yes
checking for gcc... yes
checking for pkg-config... yes

Warning: Found more than one ImageMagick installation. This could cause problems at runtime.
         /usr/local/opt/imagemagick@6/bin/Magick-config reports version 6.9.11 Q16 is installed in /usr/local/Cellar/imagemagick@6/6.9.11-33
         /usr/local/bin/Magick-config reports version 6.9.11 Q16 is installed in /usr/local/Cellar/imagemagick@6/6.9.11-33
Using 6.9.11 Q16 from /usr/local/Cellar/imagemagick@6/6.9.11-33.

checking for outdated ImageMagick version (<= 6.7.7)... no
checking for Ruby version >= 2.3.0... yes
checking for sys/types.h... yes
checking for magick/MagickCore.h... yes
checking for snprintf() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for GetImageChannelEntropy() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for SetImageGray() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
creating extconf.h
creating Makefile

======================================================================
Thu 08 Oct 20 21:44:18
This installation of RMagick 3.1.0 is configured for
Ruby 2.6.3 (x86_64-darwin19) and ImageMagick 6.9.11
======================================================================

Configured compile options: {:magick_version=>"6.9.11", :local_libs=>" -L/usr/local/Cellar/imagemagick@6/6.9.11-33/lib -lMagickCore-6.Q16", :cflags=>" -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.11-33/include/ImageMagick-6", :cppflags=>" -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.11-33/include/ImageMagick-6", :ldflags=>" -L/usr/local/Cellar/imagemagick@6/6.9.11-33/lib -lMagickCore-6.Q16", :defs=>[], :config_h=>"Makefile rmagick.h"}

current directory: /Users/rohit/.rvm/gems/ruby-2.6.3@Rails5.2.3_performance-management/gems/rmagick-3.1.0/ext/RMagick
make "DESTDIR=" clean

current directory: /Users/rohit/.rvm/gems/ruby-2.6.3@Rails5.2.3_performance-management/gems/rmagick-3.1.0/ext/RMagick
make "DESTDIR="
compiling rmagick.c
compiling rmdraw.c
compiling rmenum.c
compiling rmfill.c
compiling rmilist.c
compiling rmimage.c
compiling rminfo.c
compiling rmkinfo.c
rmkinfo.c:82:5: error: implicit declaration of function 'ZeroKernelNans' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    ZeroKernelNans((KernelInfo*)DATA_PTR(self));
    ^
1 error generated.
make: *** [rmkinfo.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/rohit/.rvm/gems/ruby-2.6.3@Rails5.2.3_performance-management/gems/rmagick-3.1.0 for inspection.
Results logged to /Users/rohit/.rvm/gems/ruby-2.6.3@Rails5.2.3_performance-management/extensions/x86_64-darwin-19/2.6.0/rmagick-3.1.0/gem_make.out

**Comment by Watson1978** [comment]
Please update RMagick instead of using 3.1.0 version.

**Comment by Watson1978** [comment]
RMagick Version 3.1.0 has not been tested with the latest ImageMagick. 
And we might not release the maintenance version for ver 3.x.

So could you please use the newest RMagick or downgrade the ImageMagick ?
