### ISSUE TITLE
Installation of ImageMagic on MAC OS

### ISSUE THREAD

**Issue by GlebNovikov** [rmagick/rmagick#1244]
Hello,
Following detailed instructions, I tried to install ImageMagic on my MAC using https://imagemagick.org/download/binaries/ImageMagick-x86_64-apple-darwin19.6.0.tar.gz
after sourcing all PATH in terminal according to 
https://imagemagick.org/script/download.php#macosx
there is still problem with some libraties

bash-3.2$ convert
dyld: Library not loaded: /ImageMagick-7.0.10/lib/libMagickCore-7.Q16HDRI.7.dylib
  Referenced from: /Users/gleb/ImageMagick-7.0.10/bin/convert
  Reason: image not found
Trace/BPT trap: 5

Should I altrnatively add all of the relevant PATH to some folder of my user .bash_sessions ?

Alternatively I tried also to use recomended way of the installation using brew but there was an error with one of the dependencies

==> Downloading https://bitbucket.org/multicoreware/x265/downloads/x265_3.2.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "x265"
Download failed: https://bitbucket.org/multicoreware/x265/downloads/x265_3.2.1.tar.gz

Thank you very much for your kind help!

**Comment by Watson1978** [comment]
Please report ImageMagick issue to https://github.com/ImageMagick/ImageMagick .
We can't solve your ImageMagick issue.
