### ISSUE TITLE
Invalid byte sequence when installing rmagick

### ISSUE THREAD

**Issue by hicklin-james** [rmagick/rmagick#1258]
### Description
When using rmagick with the latest release of imagemagick for Windows (7.0.10-58), calling `gem install rmagick` results in an exception:

```
extconf.rb:301:in `assert_has_dev_libs!': invalid byte sequence in UTF-8 (ArgumentError)
```
It appears to be due to the use of the © symbol in the `magick --version` output. Older imagemagick installs that use `C` instead of `©` seems to work fine with rmagick.
 
### Steps to Reproduce
In Windows, install latest imagemagick via official source, then run `gem install rmagick`.

I also wrote a simple program on the system that has the issue:

```
str = `magick --version`
str.valid_encoding? # false
```
which illustrates the bad encoding issue. Note that when I use an old installer for imagemagick, which uses the `C` instead of the `©`, rmagick installs perfectly.

### System Configuration

- ImageMagick version: 7.0.10-58 Q16
- RMagick version: 4.1.2
- Ruby version: 2.6.6p146
- Environment (Operating system, version and so on): Windows 10

**Comment by dlemstra** [comment]
Thanks for reporting this. The @ImageMagick team will change this back to (C) in the next release to avoid UTF8 issues.

**Comment by Watson1978** [comment]
ImageMagick 7.0.10-59 was released and I think it should solve this issue.
