### ISSUE TITLE
Unable To Create Transparent Background for New Image

### ISSUE THREAD

**Issue by mrthankyou** [rmagick/rmagick#1266]
### Description
When setting an image's background color to transparent, RMagick instead generates an image with a white background.

### Steps to Reproduce
1. Run the following code below:
```
require 'RMagick'
include Magick

img = Magick::Image.new(600, 600)
img.background_color = "transparent"
img.write("test.jpeg") 
```

2. Review the test.jpeg and you will see a white background.

### System Configuration

- ImageMagick version: 6.9.11-62 Q16 x86_64 2021-02-07
- RMagick version: 4.2.1
- Ruby version: 2.6.3p62
- Environment (Operating system, version and so on): MacOS 11.1
- Additional information: Attached at the bottom is the generated image with the white background. Also, saving it as a png did nothing and I got the same result.

![test](https://user-images.githubusercontent.com/52643283/107280719-b735f400-6a26-11eb-9b1c-8741653d4814.jpeg)

**Comment by Watson1978** [comment]
@mrthankyou Can you try following code? I think you can solve your problem.

```ruby
require 'rmagick'

img = Magick::Image.new(600, 600) do
  self.background_color = "transparent"
end

img.write("test.png")
```

**Comment by Watson1978** [comment]
I will close this.
If you still have something, feel free to re-open this issue.
