### ISSUE TITLE
deprecation warning in rvg.rb

### ISSUE THREAD

**Issue by gsar** [rmagick/rmagick#1270]
### Description

The newly introduced deprecation warning is also triggered by code shipped in rmagick itself at https://github.com/rmagick/rmagick/blob/main/lib/rvg/rvg.rb#L99

I see it being triggered via the Avatarly gem, which uses rmagick:

```
/home/gsar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rmagick-4.2.1/lib/rvg/rvg.rb:99: warning: passing a block without an image argument is deprecated
/home/gsar/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/avatarly-1.6.0/lib/avatarly.rb:51: warning: passing a block without an image argument is deprecated
```

### System Configuration

- ImageMagick version: 6.9.10-23
- RMagick version: 4.2.1
- Ruby version: 2.7.2

**Comment by mockdeep** [comment]
@gsar thanks for reporting. The deprecation warning will be removed in the next release.

**Comment by mockdeep** [comment]
Version 4.2.2 has been released.

**Comment by akicho8** [comment]
I think that it is better to refactor the code of the part where the warning comes out.
I wanted to leave the warning put.

**Comment by mockdeep** [comment]
@akicho8 I think we should refactor the code, too, but there are hundreds of places in the RMagick code that would need to be refactored. All of the docs also have `self.`. I don't think it makes sense to have a deprecation warning that our own code fails:

```sh
$ git grep self\\. | wc -l
455
```

I think we should clean up all of that and then reintroduce the warning.

**Comment by akicho8** [comment]
https://github.com/rmagick/rmagick/pull/1279 The corresponding block argument has been replaced.

    $ git grep self\\. | wc -l
    162

The remaining is `self.class.new` etc.
