### ISSUE TITLE
formats are accessible via passenger server but not avaialbe in rails console.

### ISSUE THREAD

**Issue by robertleelittleiii** [rmagick/rmagick#1282]
### Description
I was trying to run a rake task that processes some PDFs into JPEGs. The code works fine in the Passenger enviorment (as a web server process).  

I was getting this error in the console and in the rake task.

```
ArgumentError: unknown format: PDF

```

It looks like rmagick sees the available formats in the Passenger server but not in the rails console. I ran Magick::formats to get a list of available formats and this is what I got in both enviorments.

When I try to run as a rake task or in the rails console, I get a blank list of formats:

In console:
```

2.5.0 :001 > Magick::formats
 => {} 


```

In passenger server:
```

{"3FR"=>" r--", "A"=>"*rw+", "AAI"=>"*rw+", "AI"=>" rw-", "ART"=>"*rw-", "ARW"=>" r--", "AVI"=>" r--", "AVS"=>"*rw+", "B"=>"*rw+", "BGR"=>"*rw+", "BGRA"=>"*rw+", "BMP"=>"*rw-", "BMP2"=>"*-w-", "BMP3"=>"*-w-", "BRF"=>"*-w-", "C"=>"*rw+", "CAL"=>"*rw-", "CALS"=>"*rw-", "CANVAS"=>"*r--", "CAPTION"=>"*r--", "CIN"=>"*rw-", "CIP"=>"*-w-", "CLIP"=>"*-w+", "CMYK"=>"*rw+", "CMYKA"=>"*rw+", "CR2"=>" r--", "CRW"=>" r--", "CUR"=>"*rw-", "CUT"=>"*r--", "DCM"=>"*r--", "DCR"=>" r--", "DCX"=>"*rw+", "DDS"=>"*r--", "DFONT"=>"*r--", "DNG"=>" r--", "DOT"=>" ---", "DPX"=>"*rw-", "EPDF"=>" rw-", "EPI"=>" rw-", "EPS"=>" rw-", "EPS2"=>"*-w-", "EPS3"=>"*-w+", "EPSF"=>" rw-", "EPSI"=>" rw-", "EPT"=>" rw-", "EPT2"=>" rw-", "EPT3"=>" rw+", "ERF"=>" r--", "FAX"=>"*rw+", "FITS"=>"*rw-", "FRACTAL"=>"*r--", "FTS"=>"*rw-", "G"=>"*rw+", "G3"=>"*rw-", "GIF"=>"*rw+", "GIF87"=>"*rw-", "GRADIENT"=>"*r--", "GRAY"=>"*rw+", "GROUP4"=>"*rw-", "HALD"=>"*r--", "HDR"=>"*rw+", "HISTOGRAM"=>"*-w-", "HRZ"=>"*rw-", "HTM"=>"*-w-", "HTML"=>"*-w-", "ICB"=>"*rw-", "ICO"=>"*rw+", "ICON"=>"*rw-", "INFO"=>" -w+", "INLINE"=>"*r--", "IPL"=>"*rw+", "ISOBRL"=>"*-w-", "JNG"=>"*rw-", "JPEG"=>"*rw-", "JPG"=>"*rw-", "K"=>"*rw+", "K25"=>" r--", "KDC"=>" r--", "LABEL"=>"*r--", "M"=>"*rw+", "M2V"=>" rw+", "M4V"=>" rw+", "MAC"=>"*r--", "MAP"=>"*rw-", "MAT"=>" rw+", "MATTE"=>"*-w+", "MEF"=>" r--", "MIFF"=>"*rw+", "MNG"=>"*rw+", "MONO"=>"*rw-", "MOV"=>" rw+", "MP4"=>" rw+", "MPC"=>"*rw+", "MPEG"=>" rw+", "MPG"=>" rw+", "MRW"=>" r--", "MSL"=>"*rw+", "MSVG"=>" rw+", "MTV"=>"*rw+", "MVG"=>"*rw-", "NEF"=>" r--", "NRW"=>" r--", "NULL"=>"*rw-", "O"=>"*rw+", "ORF"=>" r--", "OTB"=>"*rw-", "OTF"=>"*r--", "PAL"=>"*rw-", "PALM"=>"*rw+", "PAM"=>"*rw+", "PATTERN"=>"*r--", "PBM"=>"*rw+", "PCD"=>"*rw-", "PCDS"=>"*rw-", "PCL"=>" rw+", "PCT"=>"*rw-", "PCX"=>"*rw-", "PDB"=>"*rw+", "PDF"=>" rw+", "PDFA"=>" rw+", "PEF"=>" r--", "PES"=>"*r--", "PFA"=>"*r--", "PFB"=>"*r--", "PFM"=>"*rw+", "PGM"=>"*rw+", "PICON"=>"*rw-", "PICT"=>"*rw-", "PIX"=>"*r--", "PJPEG"=>"*rw-", "PLASMA"=>"*r--", "PNG"=>"*rw-", "PNG24"=>"*rw-", "PNG32"=>"*rw-", "PNG8"=>"*rw-", "PNM"=>"*rw+", "PPM"=>"*rw+", "PREVIEW"=>"*-w-", "PS"=>" rw+", "PS2"=>"*-w+", "PS3"=>"*-w+", "PSB"=>"*rw+", "PSD"=>"*rw+", "PTIF"=>"*rw+", "PWP"=>"*r--", "R"=>"*rw+", "RADIAL-GRADIENT"=>"*r--", "RAF"=>" r--", "RAS"=>"*rw+", "RGB"=>"*rw+", "RGBA"=>"*rw+", "RGBO"=>"*rw+", "RLA"=>"*r--", "RLE"=>"*r--", "SCR"=>"*r--", "SCT"=>"*r--", "SFW"=>"*r--", "SGI"=>"*rw+", "SHTML"=>"*-w-", "SR2"=>" r--", "SRF"=>" r--", "STEGANO"=>"*r--", "SUN"=>"*rw+", "SVG"=>" rw+", "SVGZ"=>" rw+", "TEXT"=>"*rw+", "TGA"=>"*rw-", "THUMBNAIL"=>"*-w+", "TIFF"=>"*rw+", "TIFF64"=>"*rw-", "TILE"=>"*r--", "TIM"=>"*r--", "TTC"=>"*r--", "TTF"=>"*r--", "TXT"=>"*rw+", "UBRL"=>"*-w-", "UIL"=>"*-w-", "UYVY"=>"*rw-", "VDA"=>"*rw-", "VICAR"=>"*rw-", "VID"=>"*rw+", "VIFF"=>"*rw+", "VST"=>"*rw-", "WBMP"=>"*rw-", "WMF"=>"*r--", "WMV"=>" rw+", "WMZ"=>"*r--", "WPG"=>"*r--", "X3F"=>" r--", "XBM"=>"*rw-", "XC"=>"*r--", "XCF"=>"*r--", "XPM"=>"*rw-", "XPS"=>" r--", "XV"=>"*rw+", "Y"=>"*rw+", "YCbCr"=>"*rw+", "YCbCrA"=>"*rw+", "YUV"=>"*rw-"}


```

I have verified that I am running the same version of RMagick in both console and passenger:

Console:
```

2.5.0 :005 >  Magick::Long_version
 => "This is RMagick 2.16.0 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter\nBuilt with ImageMagick 6.7.5-10 2016-11-16 Q16 http://www.imagemagick.org\nBuilt for ruby 2.5.1\nWeb page: http://rmagick.rubyforge.org\nEmail: rmagick@rubyforge.org\n" 


```
Passenger:
```

This is RMagick 2.16.0 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter Built with ImageMagick 6.7.5-10 2016-11-16 Q16 http://www.imagemagick.org Built for ruby 2.5.1 Web page: http://rmagick.rubyforge.org Email: rmagick@rubyforge.org

```

I'm thinking that it may be a path issue between passenger and my local enviorment.

### Steps to Reproduce

I have tested this on 2 servers I am running with similar configurations with the same result.  

### System Configuration

- ImageMagick version:  6.7.5-10 2016-11-16 Q16
- RMagick version: 2.1.6
- Ruby version:  ruby 2.5.1p57
- Environment (Operating system, version and so on): Ubuntu 14.04.5 LTS

**Comment by mockdeep** [comment]
@robertleelittleiii RMagick version 2.1.6 is no longer supported. Are you able to upgrade to the latest version (4.2.2)? Unfortunately, we won't be able to help you debug 2.1.6.

**Comment by robertleelittleiii** [comment]
I have the same problem with RMagick 4.0.0 ( on the other server). 

Can you help me with that version? 

Thanks!

**Comment by robertleelittleiii** [comment]
I upgraded to 4.2.2 and I am still having the same problem.

**Comment by dlemstra** [comment]
The version of ImageMagick that you are using is ancient I would also advise you to upgrade that.

**Comment by robertleelittleiii** [comment]
The version being used with the upgraded RMagick is ImageMagick 6.9.8-3 Q16 (a bit newer).

I'm sure this fix is probably a config with the shell because it works perfectly in Passenger. I just can't seem to get it working in the console (and rake task).  What would cause RMagick to fail to find any of the Delegates (formats)?

**Comment by mockdeep** [comment]
@robertleelittleiii it's hard to know for sure without more context and maybe access to your environment. `Magick.formats` comes from ImageMagick, so I would expect to see the same thing when you run `convert --version`. Could you add this to your rake task and give us the output:

```rb
puts `convert --version`
```

It should output version info for ImageMagick, including a `Delegates:` line.

**Comment by robertleelittleiii** [comment]
Version: ImageMagick 6.9.8-3 Q16 x86_64 2017-08-30 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib fontconfig freetype jng jpeg ltdl png tiff wmf xml zlib

**Comment by mockdeep** [comment]
Hmm, yeah, I don't see anything suspicious there. Another thing that I'm wondering about is the `policy.xml` file. Is your passenger setup doing anything to edit the ImageMagick policy? I believe PDF support is disabled by default in more recent versions of ImageMagick.

**Comment by robertleelittleiii** [comment]
I checked it.  I changed the policy.xml file to include PDFs.  I still get an empty hash on the console for 

```
Magick::formats

```
and a full list on the passenger server (see above)

**Comment by mockdeep** [comment]
@robertleelittleiii I'm sorry, I don't know how much more we can help you with this. It doesn't strike me as an issue with RMagick. My best guess is there's some difference between the environments causing ImageMagick to behave differently. The more you can isolate those differences, the easier it will be to figure out exactly what is causing the issue. Things to check (if you haven't already):

* Accessing a `bash` console on the Passenger server
* Accessing a `bash` console on the server you're running `rake` on
* Accessing a Ruby console on both server types
* Running the `rake` code inside your application on the Passenger server
* Double check that the ImageMagick `policy.xml` is the same in both instances
* Double check that the ImageMagick version is the same in both instances
* Double check that the RMagick version is the same in both instances

**Comment by robertleelittleiii** [comment]
Thanks!  I appreciate the pointers.  I will let you know what the fix is.  What is most strange is both Amazon instances have the same issue.  Each is running multiple rails apps with different versions of the gem.

**Comment by mockdeep** [comment]
@robertleelittleiii one other thing to check is whether you're overriding `MAGICK_CONFIGURE_PATH` in one environment and not another. It allows you to specify where `policy.xml` is stored, so maybe it's falling back to the default in one place and not another.

**Comment by Watson1978** [comment]
To process PDF, I think you need to install ghostscript at first because I guess ImageMagick delegate the process to ghostscript.

**Comment by mockdeep** [comment]
@robertleelittleiii did you manage to resolve your issue?

**Comment by Watson1978** [comment]
This would be an issue related to user environment.
I will close this.

Feel free to reopen if you have still any problem.
