### ISSUE TITLE
rmagick in ubuntu 20.04, rmagick does not detect a png as an image 

### ISSUE THREAD

**Issue by diego-gonzalez-duque** [rmagick/rmagick#1283]
### System Configuration

- ImageMagick version:
- RMagick version:
- Ruby version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by mockdeep** [comment]
@diego-gonzalez-duque can you provide additional information? Which software versions are you using? Can you link the PNG image you're trying to load? I am not having any issues loading PNG images.

**Comment by jhirn** [comment]
Diggin into the gem we see it is indeed an issue with registered decode values

```
#<Magick::ImageMagickError: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/572>
/home/diego/.rvm/gems/ruby-2.7.2/gems/carrierwave-2.1.1/lib/carrierwave/processing/rmagick.rb:352:in `read'
/home/diego/.rvm/gems/ruby-2.7.2/gems/carrierwave-2.1.1/lib/carrierwave/processing/rmagick.rb:352:in `manipulate!'
/home/diego/.rvm/gems/ruby-2.7.2/gems/carrierwave-2.1.1/lib/carrierwave/processing/rmagick.rb:145:in `resize_to_limit'
```

This leads me to the idea we're just not compiling the gem with the proper installation of ImageMagick, but I'm not sure how to point it to the installation from the tarball that we configured. It's the first in the path from where we compiled the gem, but at least we know this is an environment problem =)

**Comment by mockdeep** [comment]
@jhirn yeah, it would be good to test it without CarrierWave to make sure there isn't anything weird going on with where tempfiles are being created. In general, I don't think you should need to do a whole lot of work to get RMagick up and running these days, just:

```rb
$ sudo apt-get install imagemagick
$ gem install rmagick
```

If you have lingering files from another ImageMagick installation, that could definitely cause an issue. If you compiled and installed it from source, you should run `sudo make uninstall` to clear out any files that were installed before installing a different version.

What happens when you try to read your PNG from a console?

```irb
> require 'rmagick'
> Magick::Image.read('/path/to/my/image.png')
```

**Comment by diego-gonzalez-duque** [comment]
@mockdeep when o do the .read it says this:
Magick::ImageMagickError: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/572

**Comment by mockdeep** [comment]
@diego-gonzalez-duque thanks for the followup. Are you able to share the image you're trying to read? Some additional information that might be helpful, can you share the output from:

```sh
$ convert --version
```

And in the `irb` console:

```irb
> require 'rmagick'
> Magick::Version
> Magick::Magick_version
> Magick.formats
```

**Comment by diego-gonzalez-duque** [comment]
@mockdeep thanks i can not share the image for it is company ip but the output off the convert version is:
diego@diego-ThinkBook-15-G2-ITL:~$ convert --version
Version: ImageMagick 7.0.11-5 Q16 x86_64 2021-03-28 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype jbig jng jp2 jpeg lcms lqr lzma openexr png tiff x xml zlib



and when i run the other comands in the console this is the result:

`[1] pry(main)> require 'rmagick' 
=> false
[2] pry(main)> Magick::Version
=> "RMagick 4.1.2"
[3] pry(main)> Magick::Magick_version
=> "ImageMagick 7.0.11-4 Q16 x86_64 2021-03-20 https://imagemagick.org"
[4] pry(main)> Magick.formats
=> {"3FR"=>" r-+",
 "3G2"=>" r-+",
 "3GP"=>" r-+",
 "A"=>"*rw+",
 "AAI"=>"*rw+",
 "AI"=>" rw-",
 "APNG"=>" rw+",
 "ART"=>"*rw-",
 "ARW"=>" r-+",
 "ASHLAR"=>"*-w+",
 "AVI"=>" r-+",
 "AVS"=>"*rw+",
 "B"=>"*rw+",
 "BGR"=>"*rw+",
 "BGRA"=>"*rw+",
 "BGRO"=>"*rw+",
 "BMP"=>"*rw-",
 "BMP2"=>"*rw-",
 "BMP3"=>"*rw-",
 "BRF"=>"*-w-",
 "C"=>"*rw+",
 "CAL"=>"*r--",
 "CALS"=>"*r--",
 "CANVAS"=>"*r--",
 "CAPTION"=>"*r--",
 "CIN"=>"*rw-",
 "CIP"=>"*-w-",
 "CLIP"=>"*rw+",
 "CMYK"=>"*rw+",
 "CMYKA"=>"*rw+",
 "CR2"=>" r-+",
 "CR3"=>" r-+",
 "CRW"=>" r-+",
 "CUBE"=>"*r--",
 "CUR"=>"*rw-",
 "CUT"=>"*r-+",
 "DATA"=>"*rw+",
 "DCM"=>"*r--",
 "DCR"=>" r-+",
 "DCRAW"=>" r-+",
 "DCX"=>"*rw+",
 "DDS"=>"*rw+",
 "DNG"=>" r-+",
 "DPX"=>"*rw-",
 "DXT1"=>"*rw+",
 "DXT5"=>"*rw+",
 "EPDF"=>" rw-",
 "EPI"=>" rw-",
 "EPS"=>" rw-",
 "EPS2"=>" -w-",
 "EPS3"=>" -w+",
 "EPSF"=>" rw-",
 "EPSI"=>" rw-",
 "ERF"=>" r-+",
 "FARBFELD"=>"*rw-",
 "FAX"=>"*rw+",
 "FF"=>"*rw-",
 "FILE"=>"*r-+",
 "FITS"=>"*rw-",
 "FL32"=>"*rw-",
 "FLV"=>" rw+",
 "FRACTAL"=>"*r--",
 "FTP"=>"*--+",
 "FTS"=>"*rw-",
 "G"=>"*rw+",
 "G3"=>"*rw-",
 "G4"=>"*rw-",
 "GIF"=>"*rw+",
 "GIF87"=>"*rw-",
 "GRADIENT"=>"*r--",
 "GRAY"=>"*rw+",
 "GRAYA"=>"*rw+",
 "HALD"=>"*r--",
 "HDR"=>"*rw+",
 "HISTOGRAM"=>"*-w-",
 "HRZ"=>"*rw-",
 "HTM"=>"*-w-",
 "HTML"=>"*-w-",
 "HTTP"=>"*--+",
 "HTTPS"=>"*r-+",
 "ICB"=>"*rw-",
 "ICO"=>"*rw+",
 "ICON"=>"*rw-",
 "IIQ"=>" r-+",
 "INFO"=>" -w+",
 "INLINE"=>"*rw+",
 "IPL"=>"*rw+",
 "ISOBRL"=>"*-w-",
 "ISOBRL6"=>"*-w-",
 "JNX"=>"*r-+",
 "JSON"=>" -w+",
 "K"=>"*rw+",
 "K25"=>" r-+",
 "KDC"=>" r-+",
 "LABEL"=>"*r--",
 "M"=>"*rw+",
 "M2V"=>" rw+",
 "M4V"=>" rw+",
 "MAC"=>"*r-+",
 "MAP"=>"*rw-",
 "MASK"=>"*rw+",
 "MAT"=>" rw+",
 "MATTE"=>"*-w+",
 "MEF"=>" r-+",
 "MIFF"=>"*rw+",
 "MKV"=>" rw+",
 "MONO"=>"*rw-",
 "MOV"=>" rw+",
 "MP4"=>" rw+",
 "MPC"=>"*rw+",
 "MPEG"=>" rw+",
 "MPG"=>" rw+",
 "MRW"=>" r-+",
 "MSL"=>"*--+",
 "MSVG"=>"*-w+",
 "MTV"=>"*rw+",
 "MVG"=>"*rw-",
 "NEF"=>" r-+",
 "NRW"=>" r-+",
 "NULL"=>"*rw-",
 "O"=>"*rw+",
 "ORA"=>" --+",
 "ORF"=>" r-+",
 "OTB"=>"*rw-",
 "PAL"=>"*rw-",
 "PALM"=>"*rw+",
 "PAM"=>"*rw+",
 "PANGO"=>"*---",
 "PATTERN"=>"*r--",
 "PBM"=>"*rw+",
 "PCD"=>"*rw-",
 "PCDS"=>"*rw-",
 "PCL"=>" rw+",
 "PCT"=>"*rw-",
 "PCX"=>"*rw-",
 "PDB"=>"*rw+",
 "PDF"=>" rw+",
 "PDFA"=>" rw+",
 "PEF"=>" r-+",
 "PES"=>"*r-+",
 "PFM"=>"*rw+",
 "PGM"=>"*rw+",
 "PGX"=>"*rw-",
 "PHM"=>"*rw+",
 "PICON"=>"*rw-",
 "PICT"=>"*rw-",
 "PIX"=>"*r-+",
 "PLASMA"=>"*r--",
 "PNM"=>"*rw+",
 "POCKETMOD"=>" rw+",
 "PPM"=>"*rw+",
 "PS"=>" rw+",
 "PS2"=>" -w+",
 "PS3"=>" -w+",
 "PSB"=>"*rw+",
 "PSD"=>"*rw+",
 "PWP"=>"*r-+",
 "R"=>"*rw+",
 "RADIAL-GRADIENT"=>"*r--",
 "RAF"=>" r-+",
 "RAS"=>"*rw+",
 "RAW"=>" r-+",
 "RGB"=>"*rw+",
 "RGB565"=>"*r-+",
 "RGBA"=>"*rw+",
 "RGBO"=>"*rw+",
 "RGF"=>"*rw-",
 "RLA"=>"*r--",
 "RLE"=>"*r--",
 "RMF"=>" r-+",
 "RW2"=>" r-+",
 "SCR"=>"*r--",
 "SCREENSHOT"=>"*r-+",
 "SCT"=>"*r--",
 "SFW"=>"*r--",
 "SGI"=>"*rw+",
 "SHTML"=>"*-w-",
 "SIX"=>"*rw-",
 "SIXEL"=>"*rw-",
 "SPARSE-COLOR"=>"*-w+",
 "SR2"=>" r-+",
 "SRF"=>" r-+",
 "STEGANO"=>"*r-+",
 "SUN"=>"*rw+",
 "SVG"=>"*rw+",
 "SVGZ"=>"*-w+",
 "TEXT"=>"*r-+",
 "TGA"=>"*rw-",
 "THUMBNAIL"=>"*-w+",
 "TILE"=>"*r-+",
 "TIM"=>"*r-+",
 "TM2"=>"*r-+",
 "TXT"=>"*rw+",
 "UBRL"=>"*-w-",
 "UBRL6"=>"*-w-",
 "UIL"=>"*-w-",
 "UYVY"=>"*rw-",
 "VDA"=>"*rw-",
 "VICAR"=>"*rw-",
 "VID"=>"*rw+",
 "VIFF"=>"*rw+",
 "VIPS"=>"*rw+",
 "VST"=>"*rw-",
 "WBMP"=>"*rw-",
 "WEBM"=>" rw+",
 "WMV"=>" rw+",
 "WPG"=>"*r-+",
 "X3F"=>" r-+",
 "XBM"=>"*rw-",
 "XC"=>"*r--",
 "XCF"=>"*r-+",
 "XPM"=>"*rw-",
 "XPS"=>" r--",
 "XV"=>"*rw+",
 "Y"=>"*rw+",
 "YAML"=>" -w+",
 "YCbCr"=>"*rw+",
 "YCbCrA"=>"*rw+",
 "YUV"=>"*rw-"}
(END)`

**Comment by mockdeep** [comment]
@diego-gonzalez-duque so it looks like you have RMagick compiled against a different version of ImageMagick than the one at your command line. `convert --version` gave `7.0.11-5` and `Magick::Magick_version` gave `7.0.11-4`. I'd make sure that you uninstall all versions of ImageMagick on your machine except one and then try to uninstall and reinstall RMagick.

**Comment by mockdeep** [comment]
@diego-gonzalez-duque @jhirn did you manage to resolve your issue?

**Comment by jhirn** [comment]
Closing the issue.  I imagine there a rogue version from an earlier install causing the conflict. 

Thank you for your help @mockdeep
