### ISSUE TITLE
Support for ImageMagick 7.1.x

### ISSUE THREAD

**Issue by lechuckcaptain** [rmagick/rmagick#1288]
### Description
After upgrading to [ImageMagick 7.1.0](https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.0-0) I get the following error running a ruby script that `require 'RMagick'`

```
/Users/mp/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/mp/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rmagick-4.2.2/lib/RMagick2.bundle, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.9.dylib (LoadError)
  Referenced from: /Users/mp/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rmagick-4.2.2/lib/RMagick2.bundle
  Reason: image not found - /Users/mp/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rmagick-4.2.2/lib/RMagick2.bundle
```

The folloing is the content of the `/usr/local/opt/imagemagick/lib/` directory:
                                                                                                                  
```
drwxr-xr-x   4 mp  admin      128 Jun 13 02:14 ImageMagick
-rw-r--r--   1 mp  admin   585872 Jun 15 11:13 libMagick++-7.Q16HDRI.5.dylib
-r--r--r--   1 mp  admin   912792 Jun 13 02:14 libMagick++-7.Q16HDRI.a
lrwxr-xr-x   1 mp  admin       29 Jun 13 02:14 libMagick++-7.Q16HDRI.dylib -> libMagick++-7.Q16HDRI.5.dylib
-rwxr-xr-x   1 mp  admin     1456 Jun 15 11:13 libMagick++-7.Q16HDRI.la
-r--r--r--   1 mp  admin  2015984 Jun 15 11:13 libMagickCore-7.Q16HDRI.10.dylib
-r--r--r--   1 mp  admin  3001640 Jun 13 02:14 libMagickCore-7.Q16HDRI.a
lrwxr-xr-x   1 mp  admin       32 Jun 13 02:14 libMagickCore-7.Q16HDRI.dylib -> libMagickCore-7.Q16HDRI.10.dylib
-rwxr-xr-x   1 mp  admin     1333 Jun 15 11:13 libMagickCore-7.Q16HDRI.la
-r--r--r--   1 mp  admin  1185640 Jun 15 11:13 libMagickWand-7.Q16HDRI.10.dylib
-r--r--r--   1 mp  admin  1671024 Jun 13 02:14 libMagickWand-7.Q16HDRI.a
lrwxr-xr-x   1 mp  admin       32 Jun 13 02:14 libMagickWand-7.Q16HDRI.dylib -> libMagickWand-7.Q16HDRI.10.dylib
-rwxr-xr-x   1 mp  admin     1402 Jun 15 11:13 libMagickWand-7.Q16HDRI.la
drwxr-xr-x  10 mp  admin      320 Jun 15 11:13 pkgconfig
```

I'm not an expert on rmagick code, but my guess is that the updated version of ImageMagick does requires some updates on rmagick to fully support it.

### Steps to Reproduce
- Install latest version of rmagick
- Install latest version of ImageMagick
- Run a script that `require 'RMagick'`

### System Configuration

- ImageMagick version: 7.1.0-0
- RMagick version: 4.2.2
- Ruby version: 2.6.3p62
- Environment (Operating system, version and so on): Mac OS 11.4

**Comment by Watson1978** [comment]
Seems that the library location or name was changed at ImageMagick 7.1.0.
I guess you can solve when you re-install rmagick, like

```
$ gem pristine rmagick
```

**Comment by Watson1978** [comment]
Seems RMagick works fine on ImageMagick 7.1.
So, please re-install rmagick to solve your issue.

Thanks
