### ISSUE TITLE
 Setting format to APNG fails with to_blob

### ISSUE THREAD

**Issue by akicho8** [rmagick/rmagick#1290]
### Description

Setting format to APNG fails with to_blob

### Steps to Reproduce

```ruby
require "rmagick"
require "rmagick/version"
Magick::VERSION                 # => "4.2.2"
Magick::Magick_version          # => "ImageMagick 6.9.12-17 Q16 x86_64 2021-06-25 https://imagemagick.org"
image1 = Magick::Image.new(32, 32) { |e| e.background_color = "white" }
image2 = Magick::Image.new(32, 32) { |e| e.background_color = "blue"  }
list = Magick::ImageList.new
list.concat([image1, image2])
list.format = "apng"
list.to_blob rescue $!          # => #<Magick::ImageMagickError: no decode delegate for this image format `' @ error/blob.c/ImagesToBlob/1993>
list.write("out.apng")          # OK
`exiftool out.apng | grep MIME` # => "MIME Type                       : image/apng\n"
puts list.inspect
# >> [out.apng  32x32 DirectClass 16-bit,
# >> out.apng APNG 32x32 DirectClass 16-bit]
# >> scene=1
```

Backtraces are not displayed.

It succeeds when output to a file, but I wanted to get as a BLOB, so I fail to use to_blob.

```bash
$ identify -version | head -1
Version: ImageMagick 6.9.12-17 Q16 x86_64 2021-06-25 https://imagemagick.org

$ identify -list format | grep APNG
     APNG  VIDEO     rw+   Animated Portable Network Graphics
```

### System Configuration

- ImageMagick version: ImageMagick 6.9.12-17 Q16 x86_64 2021-06-25 https://imagemagick.org
- RMagick version: 4.2.2
- Ruby version: ruby 2.6.5p114
- Environment (Operating system, version and so on): macOS 11.5

**Comment by Watson1978** [comment]
Seems that you need to specify the image format for each images, not just for APNG.

```ruby
require "rmagick"
require "rmagick/version"
Magick::VERSION                 # => "4.2.2"
Magick::Magick_version          # => "ImageMagick 6.9.12-17 Q16 x86_64 2021-06-25 https://imagemagick.org"
image1 = Magick::Image.new(32, 32) { |e| e.background_color = "white" }
image2 = Magick::Image.new(32, 32) { |e| e.background_color = "blue"  }
list = Magick::ImageList.new

####### ADD
image1.format = 'APNG' 
image2.format = 'APNG'

list.concat([image1, image2])
p list.to_blob
```

**Comment by Watson1978** [comment]
> By the way, there is an error that ffmpeg execution fails.

I think it is not related to RMagick. So, please report to ImageMagick's bug tracker.

**Comment by Watson1978** [comment]
> I had a misunderstanding.
> list.format = "apng"

I think we should fix ImageList#format to apply format each images.

**Comment by akicho8** [comment]
I reported to ImageMagick's bug tracker.
https://github.com/ImageMagick/ImageMagick/issues/4127

**Comment by akicho8** [comment]
> I think we should fix ImageList#format to apply format each images.

https://github.com/rmagick/rmagick/blob/main/lib/rmagick_internal.rb#L1651

I was to fix it. But it was a specification.
So I use while being careful about whether it is method_missing.

**Comment by akicho8** [comment]
> I reported to ImageMagick's bug tracker.
> https://github.com/ImageMagick/ImageMagick/issues/4127

The problem that the ffmpeg command fails is fixed when I changed the ImageMagick version to 6 to 7.
