### ISSUE TITLE
No such file or directory - identify -version (Errno::ENOENT)

### ISSUE THREAD

**Issue by viprasant** [rmagick/rmagick#1291]
### Description
Trying to install zxing_cpp gem in Windows.

### Steps to Reproduce
gem install zxing_cpp

### System Configuration
Windows 10 with  Ruby+Devkit 2.5.7-1 (x64) with msys2

- ImageMagick version: 7.1.0-4-Q16-HDRI-x64
- RMagick version: 2.16.0
- Ruby version: 2.5.7 (x64)
- Environment (Operating system, version and so on): Windows 10
- Additional information: 

Have ImageMagick and cmake installed.

The error is occuring at extconf.rb:141 
```
`identify -version` =~ /Version: ImageMagick (\d+\.\d+\.\d+)-+\d+ /`
```

Is identify a program that I need to have?

Here is the error log:

```
C:\Users\viprasant>gem install zxing_cpp
Fetching: rmagick-2.16.0.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing zxing_cpp:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rmagick-2.16.0/ext/RMagick
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20210805-8068-19feoe6.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby25-x64/bin/$(RUBY_BASE_NAME)
extconf.rb:141:in ``': No such file or directory - identify -version (Errno::ENOENT)
        from extconf.rb:141:in `configure_compile_options'
        from extconf.rb:16:in `initialize'
        from extconf.rb:548:in `new'
        from extconf.rb:548:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rmagick-2.16.0 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/rmagick-2.16.0/gem_make.out
```

**Comment by mockdeep** [comment]
@viprasant `identify` is provided by ImageMagick, which RMagick depends on. You'll have to first make sure ImageMagick is installed and available.

**Comment by viprasant** [comment]
@mockdeep  ImageMagick is installed and available in the path. `identify` is also working properly when used in the command line.

```
C:\Users\viprasant>magick identify wizard.jpg
wizard.jpg JPEG 480x640 480x640+0+0 8-bit sRGB 80796B 0.000u 0:00.000
```

If I pass -version to magick identify it works fine

```
C:\Users\viprasant>magick identify -version
Version: ImageMagick 7.1.0-4 Q16 x64 2021-07-18 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Visual C++: 192930038
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
```

Here it is just an argument passed to `magick` and not executed as a windows binary. But seems like the installer is doing a system call within the extconf.rb `identify -version`, so in that case we need binary right?

**Comment by mockdeep** [comment]
@viprasant yeah, RMagick depends on a top level executable for `identify`. Maybe @Watson1978 will have some better advice for you.

**Comment by dlemstra** [comment]
Can you upgrade to a more recent version and try again @viprasant?

**Comment by Watson1978** [comment]
> RMagick version: 2.16.0

You should use RMagick v4.x because v2.16.0 is not supported ImageMagick 7.x
