### ISSUE TITLE
Transparent backgrounds now black

### ISSUE THREAD

**Issue by anitagraham** [rmagick/rmagick#1292]
### Description
I've used `rmagic` for about a decade to take a sequence of pngs (with transparent backgrounds), stack them vertically, and save the result, which, until recently, also had a transparent background. We save the final image, and so we rarely produce a new one.

Recently , using the same code, the background of the new, combination image is black. How can I ensure that the transparent pixels from the source images remain transparent.

### Steps to Reproduce
I have wrapped the basic code so that it works with local files as input. Fresh, local files, with transparent backgrounds.
It can be found [here](https://github.com/anitagraham/black_backgrounds)

To run the code:
download the code and cd to it's folder.
```shell
ruby black.rb
```
A new file 'combination.png' should overwrite the current one.
Here is one of the local files, and the result of running the same code with just one file. Running the sample program combines three files.

![triangle](https://user-images.githubusercontent.com/397118/128351477-69fa2db0-c090-4db4-b80c-4a86910670da.png) ![new_triangle](https://user-images.githubusercontent.com/397118/128351487-a929995e-b6ae-4009-af15-6b18abe41102.png)

### System Configuration

- ImageMagick version: ImageMagick 7.0.11-10 Q16 x86_64 2021-04-29
- RMagick version: rmagick (4.2.2)
- Ruby version:  ruby 2.7.2p137, ruby 3.0.2p107
- Environment (Operating system, version and so on):  MacOS 11.3.1
- Additional information:

And thankyou for any help you can offer.

**Comment by dlemstra** [comment]
Did you recently switch from ImageMagick 6 to ImageMagick 7? The value for transparent is flipped in ImageMagick 7.

**Comment by anitagraham** [comment]
Yes, I would have got a new ImageMagick sometime in the past year.  

I've tried writing my objects with a transparent pixel, and also with background fill opacity set (either to 1.0 or 0.0)
My background is either shiny black, or mid-grey (RGB(151, 151, 151).
```
TXPIXEL = Magick::Pixel.from_hsla(0, 0, 100, 0.0)
RVG.new(canvas_width, canvas_height) { |canvas|
    canvas.background_fill = TXPIXEL
    canvas.background_fill_opacity = '0.0'
```

I have managed to create a white/transparent canvas using `ruby_vips` and the incantation...
```
(Vips::Image.black(1, 1, { bands: 3 }) + 255)
    .add_alpha
    .cast("uchar")
    .copy(interpretation: :srgb)
    .embed(0, 0, width, height)
```
Is there another answer to ImageMagick's decision?

**Comment by dlemstra** [comment]
I think I am going to need the help of @Watson1978 here. I am wondering if the code in `rvg` also needs some patches for `IM7`?

**Comment by Watson1978** [comment]
OK, I will also look this issue

**Comment by Watson1978** [comment]
Related to https://github.com/rmagick/rmagick/pull/756

**Comment by Watson1978** [comment]
https://github.com/rmagick/rmagick/blob/c77c3c3672fbba9e0ed3d9f64f8c326f4f744359/lib/rvg/rvg.rb#L63

Is there something wrong here? hmm.

If you set the background color using `#background_fill`, seems you can avoid the issue.

```diff
diff --git a/black.rb b/black.rb
index ca30385..682f915 100644
--- a/black.rb
+++ b/black.rb
@@ -22,6 +22,7 @@ def draw(files)
 
   rvg = Magick::RVG.new(canvas_width, canvas_height) do |canvas|
     # (density: '90', alpha: Magick::ActivateAlphaChannel)
+    canvas.background_fill = 'white'
     canvas.background_fill_opacity = 0
     ypos = canvas_height
     images.each do |image|
diff --git a/combination.png b/combination.png
index 38a4b38..c735f9c 100644
Binary files a/combination.png and b/combination.png differ
```

**Comment by anitagraham** [comment]
I'm sorry  I haven't responded to this sooner.

The suggestion to change my background fill to white doesn't help - white is no more transparent than black.

Changing the fill opacity to (0, 1,  0.5, 100%, '#ffffff00') doesn't make any difference. 

I looked at `rmagick/lib/rvg/rvg.rb`  - hoping perhaps to find `Magick::Transparent Alpha` ~ and I've spent some time today writing images without much progress.

Thanks for the suggestion.

**Comment by dlemstra** [comment]
A pull request that fixes the code that uses IM7 and resolves your issue has been merged a couple days ago. This should be resolved in the next release. As mentioned you will need to set both the `background_fill` and `background_fill_opacity`. Setting only the `background_fill_opacity` does not work.
