### ISSUE TITLE
TIFF: negative image positions unsupported when storing deskewed image

### ISSUE THREAD

**Issue by k-lyda** [rmagick/rmagick#1309]
### Description
When I try to save an image to tiff file, I receive 
```
Magick::ImageMagickError: TIFF: negative image positions unsupported
```
The image is modified using `deskew()` function.

Storing to .jpeg works fine. Only when I try to save as tiff, I receive this error.

### Steps to Reproduce
1. Use `deskew()` method on sample image.
2. Try to save a file as tiff. 

Sample code:
```
class TestImageTransformations < Minitest::Test
  include Magick

  def test_image_deskew
    sample_image =  Image.read('tests/sample_data/sample_ocr_image_skewed.jpg').first
    sample_image = sample_image.deskew(40)

    tempfile = Tempfile.new(['image', '.tiff'])
    sample_image.write(tempfile.path)

    assert_path_exists(tempfile.path)
  end
end
```

This results in error as below:
```
Minitest::UnexpectedError: Magick::ImageMagickError: TIFF: negative image positions unsupported /var/folders/qf/tvrq_mbx32vbc00zmr0r86440000gq/T/image20211103-84568-5ana6v.tiff @ error/tiff.c/WriteTIFFImage/3870
    /Users/klyda/ocr/tests/test_image_transformation.rb:15:in `write'
    /Users/klyda/ocr/tests/test_image_transformation.rb:15:in `test_image_deskew'
/Users/klyda/ocr/tests/test_image_transformation.rb:15:in `write'
/Users/klyda/ocr/tests/test_image_transformation.rb:15:in `test_image_deskew'
```

### System Configuration

- ImageMagick version: ImageMagick 7.1.0-10 Q16-HDRI x86_64 2021-10-10 https://imagemagick.org
- RMagick version: 4.2.3
- Ruby version: 3.0.2
- Environment (Operating system, version and so on): Mac OS Monterey 12.0.1
- Additional information:
The sample image, that I use: https://i.imgur.com/81ICW8y.jpg

**Comment by Watson1978** [comment]
Since the image has been adjusted by `Magick::Image#deskew`, seems the image has negative image positions.
By ImageMagick CLI tool, seems you can fix `+repage` (https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=25961)

If you can use Magick::Image#crop, I guess it has same effect in RMagick.

```ruby
require 'rmagick'

sample_image =  Magick::Image.read('sample.jpg').first
changed_image = sample_image.deskew(40)
out_image = changed_image.crop(Magick::CenterGravity, changed_image.columns, changed_image.rows, true)
out_image.write('out.tiff')
```

**Comment by k-lyda** [comment]
Thanks, that solved the issue.
