### ISSUE TITLE
Exit ruby without raise when convert HEIC to FLIF

### ISSUE THREAD

**Issue by fitmap** [rmagick/rmagick#1321]
### Description

Exit ruby without raise when convert HEIC to FLIF

### Steps to Reproduce

Download [input file](https://filesamples.com/samples/image/heic/sample1.heic)
Run these script:
```
require 'rmagick'
image = Magick::Image.read('sample1.heic').first
image.write('sample1.flif')
puts 'Okay'
```
You will not see Okay, but alse not raised error.
CMD window:
```
dir sample1.flif
```
2022-02-23  15:39         1,993,548 sample1.flif
```
magick.exe sample1.heic sample2.flif
echo %errorlevel%
```
0
```
fc.exe /b sample1.flif sample2.flif
```
Comparing files sample1.flif and SAMPLE2.FLIF
FC: no differences encountered

### System Configuration

- ImageMagick version: ImageMagick 7.1.0-25 Q16-HDRI x64 2022-02-16 https://imagemagick.org
- RMagick version: rmagick (4.2.4)
- Ruby version: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
- Environment (Operating system, version and so on): Windows 10 Professional
Version No:	21H1
Install date:	‎2021-‎08-‎22
OS inner version:	19043.1503
Experience:	Windows Feature Experience Pack 120.2212.4170.0

- Additional information:
I can view sample1.flif via ImageGlass, it is okay.
Convert sample1.heic to other formats (jpg, png, webp, jxl, avif) had not encounter this issue.

**Comment by Watson1978** [comment]
Seems the Ruby process will be terminated by ImageMagick when the image is output in FLIF format.

@dlemstra Do you know something?

**Comment by dlemstra** [comment]
On windows we removed support for the `FLIF` format because of this (https://flif.info/):

>FLIF development has stopped since FLIF is superseded by FUIF and then again by [JPEG XL](https://jpeg.org/jpegxl), which is based on a combination of [Pik](https://github.com/google/pik) and [FUIF](https://github.com/cloudinary/fuif). For more information, see [Jon's JXL info page](https://sneyers.info/jxl) or visit the [JPEG XL Discord server](https://discord.gg/DqkQgDRTFu).

You can still create flif files but that will require a custom build of ImageMagick. When a format is not available the image will be written in the same format as the input image (probably `avif` in this case). But I don't know what is causing this to break inside ruby.
