### ISSUE TITLE
Part of image turns black when converting through pdf

### ISSUE THREAD

**Issue by bv-hemant** [rmagick/rmagick#1328]
### System Configuration

- ImageMagick version:
- RMagick version: 4.2.3
- Ruby version:
- Environment (Operating system, version and so on):  linux
- Additional information:

```
pdf_images = Magick::ImageList.new("/tmp/report_black.pdf")
temp_dir = "/tmp/report_images/"
pdf_images.each_with_index { |screenshot, index|
       page_path = "#{temp_dir}#{index}.jpeg"
       screenshot.write(page_path)
 }
```
pdf image
<img width="544" alt="Screenshot 2022-03-31 at 12 38 27 PM" src="https://user-images.githubusercontent.com/85125871/160997736-0b871dd8-4e27-408e-bd46-31231d95b9f2.png">

Converted image
![5](https://user-images.githubusercontent.com/85125871/160997469-01d78813-7dc9-4b02-96bb-7e641791342f.jpeg)

pdf file
[report_black.pdf](https://github.com/rmagick/rmagick/files/8386787/report_black.pdf)

**Comment by Watson1978** [comment]
I have tried but can't seem to reproduce it in my environment.
I assume that ImageMagick has interrupted the process for some reason.
Can you attach more detailed behavior, such as error logs?

**Comment by bv-hemant** [comment]
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org

**Comment by Watson1978** [comment]
I converted your PDF file to png using `convert` command in ImageMagick.

```
# convert --version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib

# convert report_black.pdf convert-result.jpg
```

It generated following image file.

![tmp-5](https://user-images.githubusercontent.com/199156/162572380-4066f897-3102-4fac-8823-8a59b63f7366.jpg)

Seems your issue is related to ImageMagick.
