### ISSUE TITLE
Read a simple file causes no method error (bytesize)

### ISSUE THREAD

**Issue by frmichetti** [rmagick/rmagick#1337]
### Description

Read a simple file causes
<NoMethodError: undefined method `bytesize' for data/bjpeg.jpeg JPEG 2479x3508 2479x3508+0+0 DirectClass 8-bit 642kb:Magick::Image

            next if part.bytesize.zero?

### Steps to Reproduce

ImageList.new('data/bjpeg.jpeg')

### System Configuration

- ImageMagick version:
- RMagick version: 2.16.0
- Ruby version: 3.1.0p0
- Environment (Operating system, version and so on): Ubuntu 20.04
- Additional information:

**Comment by Watson1978** [comment]
RMagick does not provide a `bytesize` method.
Maybe you want a String object using `to_blob` method?

```ruby
require 'rmagick'

file = 'sample.jpg'
image = Magick::ImageList.new(file).first
p image.filesize
p image.to_blob.bytesize
```
