### ISSUE TITLE
color_floodfill not working ?

### ISSUE THREAD

**Issue by Liteo** [rmagick/rmagick#1339]
### Description
The color_floodfill feature no longer seems to work.

### Steps to Reproduce
I tried many thing, but the example from http://www.simplesystems.org/RMagick/doc/image1.html#color_floodfill doesn't work.
Everything runs smoothly, but the two images look identical (the size is slightly different though)

### System Configuration
The test was made on two different stations and they produced the same results.

- ImageMagick version: ImageMagick 7.1.0-37 Q16-HDRI x86_64 20104
- RMagick version: 4.2.5
- Ruby version: 3.1.1p18
- Environment (Operating system, version and so on): Ubuntu 20.04
- Additional information: One Ubuntu was running in WSL2, the other Ubuntu was installed natively

**Comment by Watson1978** [comment]
It works as expected when using ImageMagick 6.
Is there a miss in the implementation of ImageMagick 7 support?

@dlemstra Do you know something for this issue?

**Comment by dlemstra** [comment]
Running some tests in the codespaces and I am getting the following output:
```
@dlemstra [IM 6.9.12-54]➜ /workspaces/rmagick (codespaces ✗) $ compare -metric rmse before.jpg after.jpg null:
11685.3 (0.178306)

@dlemstra [IM 7.1.0-39]➜ /workspaces/rmagick (codespaces ✗) $ compare -metric rmse before.jpg after.jpg null:
11685.3 (0.178306)
```

With this code sample:

```ruby
before = Magick::Image.new(200, 200) { |info| info.background_color = 'white' }
before.border!(1,1,'black')

circle = Magick::Draw.new
circle.fill('transparent')
circle.stroke_width(2)
circle.stroke('black')
circle.circle(100,100,180,100)
circle.fill('plum1')
circle.stroke('transparent')
circle.circle( 60,100, 40,100)
circle.circle(140,100,120,100)
circle.circle(100, 60,100, 40)
circle.circle(100,140,100,120)
circle.draw(before)

before.write('/workspaces/rmagick/before.jpg')

aquamarine = Magick::Pixel.from_color('aquamarine')
after = before.color_floodfill(100,100, aquamarine)

after.write('/workspaces/rmagick/after.jpg')
```

**Comment by dlemstra** [comment]
Can we close this @Liteo?

**Comment by Watson1978** [comment]
The original code save as `gif`.
https://github.com/rmagick/rmagick/blob/main/doc/ex/color_floodfill.rb

Why does it work as expected when changed to `png` or `jpg` ? 🤔

**Comment by mtasaka** [comment]
I've tried this with ImageMagick 7.1.0-62 and rubygem-rmagick 5.2.0, with a bit modified as below:

```
#!/usr/bin/ruby

require 'rmagick'

# Demonstrate the Image#color_floodfill method

before = Magick::Image.new(200, 200) { |info| info.background_color = 'white' }
before.border!(1, 1, 'black')

circle = Magick::Draw.new
circle.fill('transparent')
circle.stroke_width(2)
circle.stroke('black')
circle.circle(100, 100, 180, 100)
circle.fill('plum1')
circle.stroke('transparent')
circle.circle(60, 100, 40, 100)
circle.circle(140, 100, 120, 100)
circle.circle(100, 60, 100, 40)
circle.circle(100, 140, 100, 120)
circle.draw(before)

before_dup = before.dup
before.write('color_floodfill_before1.png')
before.write('color_floodfill_before.gif')
before.write('color_floodfill_before2.png') # differs from before1.png
before_dup.write('color_floodfill_before_dup.png') # same as before1.png

aquamarine = Magick::Pixel.from_color('aquamarine')
after = before.color_floodfill(100, 100, aquamarine)
after_dup = before_dup.color_floodfill(100, 100, aquamarine)

after.write('color_floodfill_after.png') # bad, and same as before2.png!!
after_dup.write('color_floodfill_after_dup.png') # good    
exit
```

and md5sum is actually:

```
4c1185d6f960b2c1256de9a630e4fd4f  color_floodfill_before1.png
4c1185d6f960b2c1256de9a630e4fd4f  color_floodfill_before_dup.png
5e1adc9b6389d0eb32194b797dc5655e  color_floodfill_after.png
5e1adc9b6389d0eb32194b797dc5655e  color_floodfill_before2.png
9020fd3cdcd594ff29d092f81b63cc7e  color_floodfill_after_dup.png
```

So I guess `before.write('color_floodfill_before.gif')` somehow "destroys" the original `before` image.

**Comment by mtasaka** [comment]
So further analysis shows that writing image with gif format by `before.write('color_floodfill_before.gif')` calls ImageMagick `WriteGIFImage()`, which sets `ImageType` to `PaletteType` via calling `SetImageType()`, which internally does `QuantizeImage()`. ref:

https://github.com/ImageMagick/ImageMagick/blob/c5d5e7117fb07096158bcad05e1086f0c2fff172/coders/gif.c#L1615-L1616
https://github.com/ImageMagick/ImageMagick/blob/c5d5e7117fb07096158bcad05e1086f0c2fff172/MagickCore/attribute.c#L2199

So what happens when saving to gif is:

```
#!/usr/bin/ruby

require 'rmagick'

# Demonstrate the Image#color_floodfill method

before = Magick::Image.new(200, 200) { |info| info.background_color = 'white' }
before.border!(1, 1, 'black')

circle = Magick::Draw.new
circle.fill('transparent')
circle.stroke_width(2)
circle.stroke('black')
circle.circle(100, 100, 180, 100)
circle.fill('plum1')
circle.stroke('transparent')
circle.circle(60, 100, 40, 100)
circle.circle(140, 100, 120, 100)
circle.circle(100, 60, 100, 40)
circle.circle(100, 140, 100, 120)
circle.draw(before)

quantized = before.quantize()

aquamarine = Magick::Pixel.from_color('aquamarine')
after = quantized.color_floodfill(100, 100, aquamarine)

after.write('color_floodfill_after.png')
exit
```

With this, color_floodfill works with ImageMagick 6.9.12-77, not with ImageMagick 7.1.0-62, so perhaps ImageMagick quantization method changed.

So the questions are:

* whether color_floodfill is expected to work for quantized image
* whether rmagick `img.write` is expected to modify the original `img`. If yes, that means that user is expected to explicitly call `img.dup` when user does more modification after writing the image. If no, then rmagick may have to duplicate the image internally when `img.write` is called.

**Comment by Watson1978** [comment]
@dlemstra Can you look the above report?

**Comment by dlemstra** [comment]
Can you still reproduce this @Watson1978?

**Comment by Watson1978** [comment]
@dlemstra IM6 and IM7 seem to create different results when saving to gif with https://github.com/rmagick/rmagick/blob/main/doc/ex/color_floodfill.rb

**Comment by dlemstra** [comment]
I finally figured out what was causing this. I just created a PR (#1591) to fix this.
