### ISSUE TITLE
Color inconsistency when reading colormap colors

### ISSUE THREAD

**Issue by evanmcallaway** [rmagick/rmagick#1400]
### Description
I would like to be able to accurately pull color values from an image's colormap so that I can accurately replace them to recolor images.

When attempting to read colors from a colormap, there appears to be a compliance mismatch that causes at least one color to be read inaccurately.

### Steps to Reproduce

Start by building an image that includes `#BEBEBE` grey.
`convert -size 50x50 xc:#BEBEBE xc:red -append -type palette test.tiff`

Verify that image has the colors we provided.
```ruby
i = Magick::Image.read('test.tiff').first
i.color_histogram.keys.map { |c| c.to_color(Magick::AllCompliance, false, 8, true) }
=> ["#FF0000", "#BEBEBE"]
```

Now pull the colors from the colormap.  Note that we get color names here because we have specified colors that have exact matches for color names.
```ruby
i = Magick::Image.read('test.tiff').first
(0...i.colors).map { |c_idx| i.colormap(c_idx) }
=> ["red", "gray"]
```

Now convert those color names into color values.
```ruby
i = Magick::Image.read('test.tiff').first
(0...i.colors).map { |c_idx| Magick::Pixel.from_color(i.colormap(c_idx)).to_color(Magick::AllCompliance, false, 8, true) }
=> ["#FF0000", "#7E7E7E"]
```

Notice how we get `#7E7E7E` instead of `#BEBEBE`.

---

The issue appears to be that there are multiple mappings for "gray" with different compliance types.
```c
{ "gray", 126, 126, 126, 1, SVGCompliance },
{ "gray", 190, 190, 190, 1, X11Compliance | XPMCompliance },
{ "grey", 190, 190, 190, 1, SVGCompliance | X11Compliance }
```

When we read the colormap, we get a color name using `rm_pixelcolor_to_color_name` which uses `X11Compliance`, giving us "gray" for `#BEBEBE`.  `Magick::Pixel.from_color` reads the color with `AllCompliance`, giving us `#7E7E7E` from the SVGCompliance mapping.

---

Is there a better way to accurately extract colors from the image's colormap with RMagick?  Pulling pure color values or Magick::Pixels would be excellent for my usecase as I do not care about the actual names.

I can work around this by setting my image format to JSON or YAML and dumping the image metadata with `to_blob` but it is far from ideal.

### System Configuration

- ImageMagick version: 7.1.0-62
- RMagick version: 5.2.0
- Ruby version: 3.0.6p216
- Environment (Operating system, version and so on):  Ubuntu 18.04.6 LTS

**Comment by mockdeep** [comment]
@dlemstra is this something you can help with?

**Comment by dlemstra** [comment]
Probably but this feels like something that should be decided on the RMagick side. Maybe `GetColorTuple` should be used instead of `QueryColorname` to make sure you always get a hex color? Or maybe this should be made an option that defaults to false to make sure you don't break code for people that expect names instead?
