### ISSUE TITLE
Magick::Image's compression= setter is not respected when writing TIFF files

### ISSUE THREAD

**Issue by evanmcallaway** [rmagick/rmagick#1404]
### Description
Assigning a compression type via Magick::Image's `compression=` setter does not result in written TIFF files with the appropriate compression type.

### Steps to Reproduce
Build an image, assign compression, and write it to disk.
```ruby
i = Magick::Image.new(50, 50)
i.compression = Magick::LZWCompression
i.write('rmagick_lzw.tiff')
```

Now check the compression on the resulting file.
```bash
$ identify -format "%C\n" rmagick_lzw.tiff
None
```

Let's do it again, but this time using Magick::Info's compression setter during the write.
```ruby
i = Magick::Image.new(50, 50)
i.write('rmagick_lzw_via_info.tiff') { |info| info.compression = Magick::LZWCompression }
```

And we can verify that compression is set appropriately.
```bash
$ identify -format "%C\n" rmagick_lzw_via_info.tiff
LZW
```

The issue appears to be isolated to TIFF files.  PNG files can still be given ZIP compression using the image's setter.

### System Configuration

- ImageMagick version:
```
Version: ImageMagick 7.1.0-62 Q16 x86_64 74b3683a4:20230211 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): fontconfig freetype jbig jng jp2 jpeg lcms ltdl lzma png tiff webp x xml zlib
Compiler: gcc (7.5)
```
- RMagick version: 5.2.0
- Ruby version: ruby 3.0.6p216
- Environment: Ubuntu 18.04.6 (Bionic Beaver)

**Comment by evanmcallaway** [comment]
Agreed, removing the setter would make this much more clear.

**Comment by Watson1978** [comment]
`image->compression` is referenced in ImageMagick 6 when write tiff file.

```c
    /*
      Initialize TIFF fields.
    */
    (void) IsMonochromeImage(image,&image->exception);
    if ((image_info->type != UndefinedType) &&
        (image_info->type != OptimizeType) &&
        (image_info->type != image->type))
      (void) SetImageType(image,image_info->type);
    compression=UndefinedCompression;
    if (image->compression != JPEGCompression)
      compression=image->compression;
```

https://github.com/ImageMagick/ImageMagick6/blob/a1de90f73136b01a74fe6b888872200485de2ef6/coders/tiff.c#L3268-L3278

However, in ImageMagick 7, it refers  `image_info->compression`.

```c
    /*
      Initialize TIFF fields.
    */
    if ((image_info->type != UndefinedType) &&
        (image_info->type != OptimizeType) &&
        (image_info->type != image->type))
      (void) SetImageType(image,image_info->type,exception);
    compression=image_info->compression;
```

https://github.com/ImageMagick/ImageMagick/blob/b41bdbb44c0fa96eb0d827c3f095294e7e3e3ef4/coders/tiff.c#L3517-L3524

To align behavior with RMagick, we have to sync Image and Info attributtes.
