### ISSUE TITLE
Huge memory consumption with latest imagemagick@6

### ISSUE THREAD

**Issue by ccbcreg** [rmagick/rmagick#1408]
[Same as Issue 1401](https://github.com/rmagick/rmagick/issues/1401)

Long running ruby process creating images with rmagick consumes massive amounts of memory since most recent ImageMagick-6.9.12-90.tar.gz release.

I've tried the 5.3.0 (Thank you @Watson1978) release and the issue still persists at a marginally slower rate but it still consumes all memory until process is killed.  I can confirm that 5.3.0 works great with ImageMagick-6.9.12-67 which is what I have installed locally using mac OS.

On Ubuntu 20 LTS, the downgraded packages 6.9.10.23 work fine with RMagick 5.3.0 as well.

I'm beginning to think this is an ImageMagick memory leak.

Please let me know what I can provide to help you.

**Comment by dlemstra** [comment]
There is no need to open a new issue. There was also a fix inside ImageMagick and it looks like you did not test this with the latest release?

**Comment by ccbcreg** [comment]
>There was also a fix inside ImageMagick and it looks like you did not test this with the latest release?

Ah, sorry, I didn't know there was an update to ImageMagick as well (guessing it is ImageMagick-6.9.12-91).  I'll have to wait until the release is pushed to homebrew and Ubuntu 20.04 focal-updates/universe in order to test.

Thank you @dlemstra, I'll close this down.....
