### ISSUE TITLE
Threading deadlock between RMagick & Open3

### ISSUE THREAD

**Issue by jdelStrother** [rmagick/rmagick#1417]
### Description

I'm experiencing a very strange deadlock between RMagick & Open3, where if they're used at the same time, `Open3.capture3("echo hello")` can block indefinitely [waiting on t.value](https://github.com/ruby/ruby/blob/e51f9e9f75cc1dde9234836fa92077d71b3c5141/lib/open3.rb#L675).

### Steps to Reproduce

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "rmagick"
end

require "open3"

SAMPLE_FILE = "sample.jpg"

if !File.exist?(SAMPLE_FILE)
  require "open-uri"
  File.binwrite(SAMPLE_FILE, URI.open("https://filesampleshub.com/download/image/jpg/sample2.jpg").read)
end

image_read = Thread.new {
  pp Magick::Image.read(SAMPLE_FILE)
}
puts "Running echo..."
Open3.capture3("echo hello") # <- never completes!
puts "Done"
image_read.join
```

### System Configuration

- ImageMagick version: 7.1.1-21 Q16-HDRI aarch64
- RMagick version: 5.3.0
- Ruby version: 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
- Environment (Operating system, version and so on): macOS Sonoma 14.1.2
- Additional information:
I've not been able to reproduce this on Linux, and it appears fixed in the ruby 3.3 preview version. I'm not sure if it's a bug in ruby's process handling, or if there's something weird RMagick is doing that's triggering it.
I can reproduce the bug in RMagick 5.1, but not 5.0, so I'm guessing it might be related to the GVL changes?

**Comment by Watson1978** [comment]
I suspect that there may be a conflict with the io used by ImageMagick.
Unfortunately, I don't know the details of ImageMagick.

You might need to invoke `Open3.capture3` after Magick::Image.read is completely finished.

```
Thread.new {
  pp Magick::Image.read(SAMPLE_FILE)
}.join

puts "Running echo..."
Open3.capture3("echo hello") # <- never completes!
puts "Done"
```

**Comment by Watson1978** [comment]
RMagick is only a bridge between Ruby and ImageMagick.
I think it is impossible to know how much computing resources both sides will use.
It would be almost impossible to solve this problem.

Please use workaround in above comment or another way.

**Comment by jdelStrother** [comment]
That seems to imply that RMagick is completely unsuited for use in a multithreaded environment - eg in a Rails app, where one thread might be servicing a request that reads an image with RMagick, and another request might be doing something with Open3.

In practice, I'm sure that isn't the case - lots of people use RMagick in Rails. Hopefully it's just limited to a weird bug in that specific ruby / macos combination.
