### ISSUE TITLE
Install fails on Ubuntu - solved

### ISSUE THREAD

**Issue by innersund** [rmagick/rmagick#1420]
### Description
Installing RMagick on Ubuntu fails due to missing dependencies

### Steps to Reproduce
$ sudo gem install rmagick
Building native extensions. This could take a while...
ERROR: Error installing rmagick:
ERROR: Failed to build gem native extension.
[... long list of not very helpful messages ...]
checking for brew... no
checking for pacman... no
checking for Ruby version >= 2.3.0... yes
*** extconf.rb failed ***

### System Configuration
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"

$ identify --version
Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org

### Solution
Found the solution on 
https://stackoverflow.com/questions/4899376/installing-rmagick-gem

$ sudo apt install libmagickwand-dev
... 63 new packages ...

and then
$ sudo gem install rmagick
Building native extensions. This could take a while...
Successfully installed rmagick-5.3.0

Thought it worth mentioning in case newbees like me stumble upon the same problem.

**Comment by Watson1978** [comment]
The library must be installed in advance by following the instructions in the link.
https://github.com/rmagick/rmagick?tab=readme-ov-file#ubuntu
