### ISSUE TITLE
2.15.4 Installation Error

### ISSUE THREAD

**Issue by SamKomesarook** [rmagick/rmagick#1493]
Hello!

I am attempting to install rmagick 2.15.4 via Bundler 1.17.3 and Ruby 2.7.8, however I am getting the following two errors from the build: `incompatible-function-pointer-types` and `int-conversion`.

I have added the ignore flags to my bundle config, and have tried to install rmagick independently through gem with the ignore flag, however it seems as though the flags have no effect on the build.

When I run the build manually (running `make` in the dir) with the flags added in the Makefile, it builds perfectly.

Is this an issue with the project Makefile?

**Comment by mockdeep** [comment]
@SamKomesarook unfortunately we cannot support old versions of RMagick anymore. More recent versions should be much easier to install. Are you able to upgrade to the latest version?

**Comment by SamKomesarook** [comment]
Unfortunately not, the project is a bit outdated... Is there some way you'd recommend to hard-code those flags into the buildfile? Every time I do a bundle install, the makefile is generated from scratch, so I can't update it... @mockdeep

**Comment by Watson1978** [comment]
> Unfortunately not, the project is a bit outdated... Is there some way you'd recommend to hard-code those flags into the buildfile? Every time I do a bundle install, the makefile is generated from scratch, so I can't update it...

Basically, there would be no such way.
Maybe, you will need following work:

1. fork RMagick via 2.15.4 git tag to your repository.
2. fix `ext/RMagick/extconf.rb` that you want the compile flag.
3. change the Gemfile so that the bundler installs from your repositories

**Comment by alfonso-iFoodDS** [comment]
``
