### ISSUE TITLE
Version 2.13.4 fails to install on CentOS 6

### ISSUE THREAD

**Issue by hannken** [rmagick/rmagick#150]
Version 2.13.4 fails to install on CentOS 6 (ruby 1.8.7, ImageMagick 6.5.4-7) as the script extconf.rb uses a regular expression (line 153) with (?<Version>...).  This format is invalid for this ruby version.

Output is:

extconf.rb:153: undefined (?...) sequence: /^Version: ImageMagick\s+(?<Version>\d+\.\d+\.\d+\-\d+)\s+(?<Unknown>\S+)\s+(?<Arch>\S+)\s+(?<Date>\S+)/

**Comment by vassilevsky** [comment]
Latest version should work fine.

**Comment by linduxed** [comment]
@hannken, can you confirm whether the latest version works or not?

**Comment by hannken** [comment]
Confirm the latest version 2.15.4 builds fine on ruby 1.8.7 / CentOS 6.

Thanks.
--
J. Hannken-Illjes - hannken@eis.cs.tu-bs.de - TU Braunschweig (Germany)

**Comment by vassilevsky** [comment]
Thanks 👌
