### ISSUE TITLE
Change in maintainers?

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#1519]
I was removed as an owner from rubygems 
I haven't been active for a long time
But was surprised and now there's only one owner.
@Watson1978 checking in

**Comment by mockdeep** [comment]
Yeah, that was me. I went through and removed everybody who hasn't been active for several years to reduce risk. I'm happy to add @Watson1978 though, since he's the most active developer at the moment.

**Comment by Watson1978** [comment]
I don't know if I would release the new version...
However, I would be happy to receive the authorization :)

**Comment by mockdeep** [comment]
I'm happy to keep doing releases, but if you want me to add you to Rubygems, feel free to give me your username.

**Comment by bf4** [comment]
Honestly I was most concerned that *all* owners had been removed and I
couldn't tell who the remaining owner was.  As someone who helped revive
this library when it was first orphaned... :)

**Comment by mockdeep** [comment]
@bf4 yeah, that's understandable. I'd love to have a couple of people on there who are active maintainers. But I'm fairly responsive at least on that front, so it should be alright for now.

**Comment by mockdeep** [comment]
@Watson1978 I've added you as an owner. I'm happy to continue releasing. If you want to do it, you just run `rake release` and it does it for you.

**Comment by Watson1978** [comment]
Thanks

**Comment by Watson1978** [comment]
Unfortunately, it didn't seem to have been added to the owner yet.

https://rubygems.org/gems/rmagick

![image](https://github.com/rmagick/rmagick/assets/199156/24b8eef8-db9e-4e74-a677-bd773d82c918)

**Comment by Watson1978** [comment]
Ah, I had to visit a link included in the confirmation email.

OK, added
