### ISSUE TITLE
RMagick versions on Heroku

### ISSUE THREAD

**Issue by mockdeep** [rmagick/rmagick#158]
I don't know if this is an issue, per se, but I just noticed that the version of ImageMagick running on Heroku is sorely out of date, `6.5.7-8` by default. There is a [buildpack](https://github.com/mcollina/heroku-buildpack-imagemagick) available, which is more recent, at `6.8.1-10`, but still hasn't been updated in a couple of years. Should `rmagick` be testing against these versions?

**Comment by vassilevsky** [comment]
https://devcenter.heroku.com/articles/cedar-ubuntu-packages

The new stack has 6.7.7.10 which is already in our `.travis.yml` :)

**Comment by linduxed** [comment]
I take it this can be closed then?

**Comment by mockdeep** [comment]
Yep.
