### ISSUE TITLE
Documentation missing in the README

### ISSUE THREAD

**Issue by joallard** [rmagick/rmagick#160]

**Comment by bf4** [comment]
Huh?

**Comment by ioquatix** [comment]
Well, clearly it was there, and has since gone missing. Time to file a police report.

**Comment by joallard** [comment]
A link to documentation (methods, classes, etc.)

**Comment by bf4** [comment]
I actually looked through the history and didn't see it, but https://rubygems.org/gems/rmagick, which we link to, http://www.rubydoc.info/gems/rmagick/2.13.4 which is correct. I can add a link to http://www.rubydoc.info/gems/rmagick/

**Comment by mockdeep** [comment]
Closing for now. Feel free to make a PR if you feel our documentation needs an update.
