### ISSUE TITLE
ImageMagick detection error on FreeBSD

### ISSUE THREAD

**Issue by hs** [rmagick/rmagick#1617]
### Description
Updating rmagick 5.5.0 to 6.0.0 on FreeBSD failed with error:
<pre>
Updating rmagick

Building native extensions. This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.1/gems/rmagick-6.0.0/ext/RMagick
/usr/local/bin/ruby31 extconf.rb
checking for brew... no
checking for pacman... no
checking for Ruby version >= 3.0.0... yes

ERROR: Can't install RMagick 6.0.0. Can't find ImageMagick with pkg-config

*** extconf.rb failed ***
</pre>

Because there is no suitable .pc file
<pre>
# pkg-config --list-all | grep ImageMagick
MagickCore                     MagickCore - MagickCore - C API for ImageMagick (ABI Q16HDRI)
Magick++-7                     Magick++ - Magick++ - C++ API for ImageMagick (ABI Q16HDRI)
ImageMagick                    ImageMagick - ImageMagick - convert, edit, and compose images (ABI Q16HDRI)
Magick++                       Magick++ - Magick++ - C++ API for ImageMagick (ABI Q16HDRI)
ImageMagick-7                  ImageMagick - ImageMagick - convert, edit, and compose images (ABI Q16HDRI)
MagickCore-7                   MagickCore - MagickCore - C API for ImageMagick (ABI Q16HDRI)
MagickWand                     MagickWand - MagickWand - C API for ImageMagick (ABI Q16HDRI)
MagickWand-7                   MagickWand - MagickWand - C API for ImageMagick (ABI Q16HDRI)
</pre>

I checked rmagick-5.5.0 and found IM6_7_PACKAGES in extconf.rb and it seems to be looking for the existing "ImageMagick" package, so that's not a problem.

ext/RMagick/extconf.rb(5.5.0)
<pre>
    # ImageMagick 6.7 package
    IM6_7_PACKAGES = ['ImageMagick'].freeze
  :
    def determine_imagemagick_package
      packages = [installed_im7_packages, installed_im6_packages].flatten

      if packages.empty?
        # ImageMagick 6.7 does not have package file like ImageMagick-6.Q16.pc
        packages = detect_imagemagick_packages(IM6_7_PACKAGES)
      end
  :
</pre>

I believe that reverting the code above or applying the patch below will resolve the issue.

[ext_RMagic_extconf.rb.patch](https://github.com/rmagick/rmagick/files/15302106/ext_RMagic_extconf.rb.patch)

### Steps to Reproduce

> gem update rmagick

### System Configuration

- ImageMagick version: 7.1.1
- RMagick version: 6.0.0
- Ruby version: 3.1.4p223
- Environment (Operating system, version and so on): FreeBSD 13.2-RELEASE-p11

**Comment by Watson1978** [comment]
Hmm, It seems that freebsd apply the patch to rename the pc file.
<img width="543" alt="スクリーンショット 2024-05-15 8 40 58" src="https://github.com/rmagick/rmagick/assets/199156/e5049b3f-e530-4c8c-935f-d1c150036b6a">
https://svnweb.freebsd.org/ports/head/graphics/ImageMagick7/Makefile?revision=559789&view=markup

**Comment by Watson1978** [comment]
Certainly looks different from the original filename.
<img width="1092" alt="スクリーンショット 2024-05-15 8 32 20" src="https://github.com/rmagick/rmagick/assets/199156/8e76247a-fe63-41a2-89b5-03c02ac523eb">

**Comment by Watson1978** [comment]
Applied your patch. thanks.
