### ISSUE TITLE
Testing preferences?

### ISSUE THREAD

**Issue by mockdeep** [rmagick/rmagick#162]
I'm hoping to spend some time working on buffing up the tests soon, and I was wondering if there was any consensus as to testing preferences. If people are open, I'd be happy to port the suite over to rspec. I prefer to break the specs down by method something like:

```
spec/
  my_lib/
    my_class/
      class_methods/
        my_class_method_spec.rb
      my_instance_method_spec.rb
```

Or there's the more conventional route of `spec/my_lib/my_class_spec.rb`. Any thoughts?

**Comment by linduxed** [comment]
I tend to use the latter for file names (`spec/path/to/file_spec.rb`) and then organize the files the following way:
```ruby
require 'spec_helper'

describe TheClass do
  describe '.a_class_method' do
    it 'is tested before the instance methods' do
      # test here
    end
  end

  describe '#an_instance_method' do
    it 'is tested after the class methods' do
      # test here
    end
  end
end
```

**Comment by mockdeep** [comment]
Yeah, I do that on a couple of projects, though I've been moving more towards the first. It makes it really easy to use a fuzzy finder to go directly to the specs you're interested in, as well as focusing mutation testing.

**Comment by bf4** [comment]
I like the approach that guard-rspec promotes as a simple convention, reflecting on `lib/gem_name/foo.rb` having a spec in `spec/gem_name/foo_spec.rb`.  No need to think about it is a win for me, at least for 'unit' tests.

**Comment by bf4** [comment]
Also, I'd love if you used RSpec 3.1 e.g. https://github.com/bf4/Notes/blob/master/code/ruby/every_app/spec/spec_helper.rb#L22-L30

**Comment by mockdeep** [comment]
Okay, cool. I'll see about getting RSpec up and running then and go the `spec/my_lib/my_class_spec.rb` route.

**Comment by vassilevsky** [comment]
@mockdeep is doing a good job with RSpec and this is no longer an issue.

**Comment by linduxed** [comment]
I agree.
