### ISSUE TITLE
6.0.1 causes NoDecodeDelegateForThisImageFormat `JPEG'

### ISSUE THREAD

**Issue by DalenW** [rmagick/rmagick#1630]
### Description
After upgrading to 6.0.1, I am unable to load images in rmagick due to the error `NoDecodeDelegateForThisImageFormat `JPEG'`. Issue is resolved by simply downgrading back to 6.0.0.

### Steps to Reproduce
It happens with this line: 

```ruby
new_card = Magick::ImageList.new(Rails.root.join('card_generation', 'card_templates', 'card.jpg'))
```

### System Configuration

- ImageMagick version: 7.1.1-33
- RMagick version: 6.0.1
- Ruby version: 3.3.1
- Environment (Operating system, version and so on): MacOS, latest
- Additional information: Simply downgrading back to 6.0.0 fixes the issue.

**Comment by Watson1978** [comment]
It is ImageMagick that throws `NoDecodeDelegateForThisImageFormat`.
Have you updated your version of ImageMagick, or have you updated the configuration or version of the libraries that ImageMagick depends on?

I guess it recognized right configuration by reinstallation of rmagick.
I think that clean install of RMagick 6.0.1 would solve your problem.
