### ISSUE TITLE
pango with -define pango:markup=false | no problem, I need help

### ISSUE THREAD

**Issue by VladFomenko** [rmagick/rmagick#1635]
I need to translate text into pictures, but I want to be able to convert emojis, Arabic, Japanese, and for this I use pango. the problem is that those two characters & and < are triggers for pango. They need to be shielded (which doesn't work very well), or use the command to disable tag reading (that's why it can't read < because it's the sign of the opening tag).
in the console it works like this

`magick -background none -fill black -font Arial -pointsize 48 -define pango:markup=false "pango:<'" combined_test.png`

and everything is fine, no errors occur
how should I use it, for example, in this case

```
 Magick::Image.read("pango :<") do |img|
     how to pass -define pango:markup=false here
 end
```

- ImageMagick 7.1.1-33 Q16-HDRI x86_64 e31ad5194:20240524
- RMagick version: 6.0.1
- Ruby version: ruby-3.2.2
- Environment (Operating system, version and so on): Ubuntu 22.04.4 LTS

**Comment by Watson1978** [comment]
```ruby
require 'rmagick'

img = Magick::Image.read("pango: <'") do |info|
  info.define('pango', 'markup', 'false')
end.first

img.write("pango.png")
```

Try above code.

**Comment by VladFomenko** [comment]
I am very grateful to you! It works!
