### ISSUE TITLE
Question: Fastest way to draw individual pixels

### ISSUE THREAD

**Issue by forthrin** [rmagick/rmagick#1636]
### Description

1. Drawing individual pixels (as outlined below) is -immensely- slow. (Why?)
2. Assume this is why "import_pixels" exists, and that this is insanely fast in comparison, but how does one feed HSL values to it? (Or rather, convert HSL values to RGB in advance, which seems more probable.)

### Steps to Reproduce
```ruby
  m = Magick::Image.new(w = 320, h = 240)
  h.times do |y|
    w.times do |x|
      draw = Magick::Draw.new
      draw.fill = 'hsl(180, 50%, 50%)'
      draw.point(x, y)
      draw.draw(m)
    end
  end
  m.write("#{Dir.home}/foo.png")
```

### System Configuration

- ImageMagick version: ImageMagick 7.1.1-33
- RMagick version: RMagick 6.0.1
- Ruby version: ruby 3.3.2
- Environment (Operating system, version and so on): System Version: macOS 14.5 (23F79)
- Model Identifier: MacBookAir10,1

**Comment by Watson1978** [comment]
I think you should onlycall Draw#point inside the loop.

```ruby
m = Magick::Image.new(w = 320, h = 240)
draw = Magick::Draw.new
draw.fill = 'hsl(180, 50%, 50%)'
h.times do |y|
  w.times do |x|
    draw.point(x, y)
  end
end
draw.draw(m)
m.write("#{Dir.home}/foo.png")
```

Create instance and drawing the image might be heavy operation.

**Comment by forthrin** [comment]
Reopen.

Should have pointed out that the color should be different for each pixel, and moving the `.new` outside the loops doesn't work then. Everything becomes one color.

So, what approach is suitable given this new information?

```ruby
  m = Magick::Image.new(w = 360, h = 240)
  h.times do |y|
    w.times do |x|
      draw = Magick::Draw.new
      draw.fill = "hsl(#{x}, 50%, 50%)"
      draw.point(x, y)
      draw.draw(m)
    end
  end
  m.write("#{Dir.home}/foo.png")
```

**Comment by Watson1978** [comment]
You need to use `Draw#fill` method instead of `fill` attribute to set the color each time.

```ruby
require 'rmagick'

m = Magick::Image.new(w = 320, h = 240)
draw = Magick::Draw.new
h.times do |y|
  w.times do |x|
    draw.fill("hsl(#{Random.rand(180)}, 50%, 50%)")
    draw.point(x, y)
  end
end
draw.draw(m)
m.write("#{Dir.home}/foo.png")
```

Seems it is slow. Therefore, it would be better to use it only when necessary.

**Comment by Watson1978** [comment]
It would be faster to replace the image pixel directly.

```
require 'rmagick'

img = Magick::Image.new(w = 320, h = 240)
img.each_pixel { |pixel, col, row|
  color = Magick::Pixel.from_hsla(Random.rand(180), '50%', '50%', 0)
  img.store_pixels(col, row, 1, 1, [color])
}
img.write('output.png')
```

**Comment by forthrin** [comment]
@Watson1978: The latter is quite fast. Thanks! Is this about as fast as writing integers directly into a raw RGB array?

**Comment by Watson1978** [comment]
Magick::Pixel.from_hsla creates a Pixel instance. The cost would be big if performed within a loop.
If you can calculate RGBA values, it would be better to manipulate the values directly

```ruby
require 'rmagick'

img = Magick::Image.new(w = 320, h = 240)
img.each_pixel { |pixel, col, row|
  pixel.red = Random.rand(Magick::QuantumRange)
  pixel.green = Random.rand(Magick::QuantumRange)
  pixel.blue = Random.rand(Magick::QuantumRange)
  img.store_pixels(col, row, 1, 1, [pixel])
}
img.write('output.png')
```

**Comment by Watson1978** [comment]
It would be even better to reduce the number of calls to store_pixels.

```ruby
require 'rmagick'

img = Magick::Image.new(w = 320, h = 240)

pixels = []
img.each_pixel { |pixel, col, row|
  pixel.red = Random.rand(Magick::QuantumRange)
  pixel.green = Random.rand(Magick::QuantumRange)
  pixel.blue = Random.rand(Magick::QuantumRange)
  pixels << pixel
}

img.store_pixels(0, 0, img.columns, img.rows, pixels)

img.write('output.png')
```

**Comment by forthrin** [comment]
Very nice. I do need to go from HSL to RGB, but if I needed it to go -really- fast, I could use Crystal to write directly to a memory block.
