### ISSUE TITLE
Alpha Channel Removed When Saving Fully Opaque Image

### ISSUE THREAD

**Issue by linkillhz** [rmagick/rmagick#1657]
### Description

When saving an image with a fully opaque alpha channel, the alpha channel is removed. 
I wrote code to add an alpha channel to an image and save it, but after saving and reloading the image, the alpha channel is not present.

### Steps to Reproduce

When I check image.alpha? before saving, it returns true, but the saved file and the reloaded image have alpha? set to false.

```
require 'rmagick'

# Read the image
image = Magick::Image.read('input_image_path.png').first

# Set the alpha channel to fully opaque
unless image.alpha?
  image.alpha(Magick::OpaqueAlphaChannel)
end

# Confirm the alpha channel is set
puts "image.alpha?: #{image.alpha?}" # true

# Save as PNG
output_path = 'output_image.png'
image.write(output_path)

# Read the saved image
created_image = Magick::Image.read(output_path).first
puts "created_image.alpha?: #{created_image.alpha?}" # false
```

### System Configuration

- ImageMagick version: 6.9.13
- RMagick version: 5.1.0
- Ruby version: 3.1.2
- Environment (Operating system, version and so on): macOS
- Additional information:

### Questions

1. Why is the alpha channel removed when saving an image with a fully opaque alpha channel?
2. Is there a way to save an image with a fully opaque alpha channel without the alpha channel being removed?

Thank you for your help and for maintaining RMagick!

**Comment by Watson1978** [comment]
Hmm, I can't reproduce...
Could you attach `input_image_path.png` in this issue due to reproduce your problem?

**Comment by linkillhz** [comment]
Thank you for looking into this. I have attached input_image_path.png to this issue to help reproduce the problem.

![input](https://github.com/user-attachments/assets/230b50a8-12a1-4d6a-b787-d3624799ff4f)

I appreciate your assistance in investigating this issue.

**Comment by Watson1978** [comment]
Even if you set `image.alpha(Magick::OpaqueAlphaChannel)`,
seems that ImageMagick will judge the alpha channel is unnecessary if no transparent color is used.

https://github.com/ImageMagick/ImageMagick6/blob/39f08e42a1889c0a6f9cf1ae2430158efa2137d1/coders/png.c#L10341-L10354

You can check number of transparent color by `Magick.set_log_event_mask("all")`.

```ruby
require 'rmagick'

# Read the image
image = Magick::Image.read('input.png').first

# Set the alpha channel to fully opaque
unless image.alpha?
  image.alpha(Magick::OpaqueAlphaChannel)
end

# Confirm the alpha channel is set
puts "image.alpha?: #{image.alpha?}" # true

# Enable ImageMagick log
Magick.set_log_event_mask("all")

# Save as PNG
output_path = 'output_image.png'
image.write(output_path)
```

```
$ ruby test.rb
...
2024-08-04T07:30:24+00:00 0:00.015 0.020u 6.9.13 Coder ruby[11843]: png.c/WriteOnePNGImage/9398/Coder
        number_transparent     = 0
2024-08-04T07:30:24+00:00 0:00.015 0.020u 6.9.13 Coder ruby[11843]: png.c/WriteOnePNGImage/9407/Coder
        number_opaque          = 48
2024-08-04T07:30:24+00:00 0:00.015 0.020u 6.9.13 Coder ruby[11843]: png.c/WriteOnePNGImage/9416/Coder
        number_semitransparent = 0
...
```

`number_transparent + number_semitransparent` should be non zero.

**Comment by Watson1978** [comment]
> Why is the alpha channel removed when saving an image with a fully opaque alpha channel?

As explained in the comment above, the behavior is derived from ImageMagick

> Is there a way to save an image with a fully opaque alpha channel without the alpha channel being removed?

Seems there is no way.

Much of the behavior comes from ImageMagick.You may want to ask a question in ImageMagick's forum.

**Comment by Watson1978** [comment]
Feel free to reopen if you have anythning about this.
