### ISSUE TITLE
Minor ImageMagick pgrade on Ubuntu Causes Magick::ImageMagickError in Ruby

### ISSUE THREAD

**Issue by NielsKSchjoedt** [rmagick/rmagick#1658]
After a recent security update to ImageMagick on our Ubuntu server, we started encountering an issue with our Ruby code. We upgraded the ImageMagick package from version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3 to 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5. Post-upgrade, the following code began to fail:

```
require "rvg/rvg"

rvg = Magick::RVG.new(600, 600) do |canvas|
  canvas.background_fill = "white"
  bullets_graphic = ::Magick::Image.read(Rails.root.join("app/assets/images/score_5.png")).first
  canvas.image(bullets_graphic)
end

image = rvg.draw # failure points to this line
image.format = 'jpg'
image.to_blob do |img|
  img.quality = 90
  img.depth = 8
end
```

We receive the following error:

`Magick::ImageMagickError: unable to open image 5335': No such file or directory @ error/blob.c/OpenBlob/2924 [GEM_ROOT]/gems/rmagick-5.5.0/lib/rvg/misc.rb:528:in draw'`

**Note**: If I do not do the `canvas.image` call, then it works.

The error references this line in the rmagick source code: [rmagick/rvg/misc.rb#L528](https://github.com/rmagick/rmagick/blob/main/lib/rvg/misc.rb#L528).

Our environment details:

•   Ubuntu Version: 22.04
•   Ruby Version: 3.2.2
•   MiniMagick Version: 4.13.2
•   RMagick Version: 5.5.0

We have tried the following troubleshooting steps without success:

1.  Reinstalled/compiled RMagick

Has anyone else encountered a similar issue after an ImageMagick upgrade? Any suggestions on how to resolve this error would be greatly appreciated.

**Comment by NielsKSchjoedt** [comment]
Update: it seems to be an issue with the default `imagemagick` package in Ubuntu 22.04. Upgrading to the newer version 6.9.13 (by building from source), it solves the problem.

**Comment by Watson1978** [comment]
I could investigate this issue over this weekend, maybe.
Thank you for your report.

**Comment by Watson1978** [comment]
I confirmed an error can be reproduced.

If it occurs an error after the package was updated, 
it may be a bad patch by debian. hmm.
https://launchpad.net/ubuntu/+source/imagemagick/8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5

**Comment by NielsKSchjoedt** [comment]
Yes, agree, where do we report that?

**Comment by Watson1978** [comment]
Seems we should report to https://bugs.launchpad.net/ubuntu/+source/imagemagick

**Comment by Watson1978** [comment]
This is reproduce command without RMagick:

```
convert -size 100x100 xc:white -stroke snow4 \
        \( -size 60x60 gradient:chartreuse1-chartreuse4 -rotate -90 -write mpri:1 +delete \) \
        -draw 'image over 0,0 0,0 "mpri:1"' \
        draw_image.gif
```

Result:
```
# convert -size 100x100 xc:white -stroke snow4 \
        \( -size 60x60 gradient:chartreuse1-chartreuse4 -rotate -90 -write mpri:1 +delete \) \
        -draw 'image over 0,0 0,0 "mpri:1"' \
        draw_image.gif
convert-im6.q16: unable to open image `1': No such file or directory @ error/blob.c/OpenBlob/2924.
```
![image](https://github.com/user-attachments/assets/49393375-7357-4a62-8bb8-4d593c424864)

**Comment by Watson1978** [comment]
Slightly simplified

```
convert -size 100x100 xc:white  \
        \( -size 60x60 gradient:orange  -write mpri:1 +delete \) \
        -draw 'image over 0,0 0,0 "mpri:1"' \
        draw_image.gif
```

**Comment by Watson1978** [comment]
I reported to https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/2077224

So, I will close this issue.
