### ISSUE TITLE
Issues when PC name contains cyrillic chars in names.

### ISSUE THREAD

**Issue by sergtk** [rmagick/rmagick#173]
Hello,

I tried to install rmagick under Windows 7 x86 with following command:

    gem install rmagick -v 2.13.4 --platform=ruby -- '--with-opt-dir="C:\ImageMagick-6.7.9-Q16"'

I got following output

		Temporarily enhancing PATH to include DevKit...
		Building native extensions with: '--with-opt-dir="C:\ImageMagick-6.7.9-Q16"'
		This could take a while...
		ERROR:  Error installing rmagick:
				ERROR: Failed to build gem native extension.

			C:/Ruby21/bin/ruby.exe extconf.rb --with-opt-dir="C:\ImageMagick-6.7.9-Q16"
		checking for Ruby version >= 1.8.5... yes
		checking for stdint.h... yes
		checking for sys/types.h... yes
		checking for wand/MagickWand.h... yes
		checking for snprintf() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand
		/MagickWand.h... yes
		checking for AcquireImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,
		wand/MagickWand.h... yes
		checking for AffinityImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h
		,wand/MagickWand.h... yes
		checking for AffinityImages() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.
		h,wand/MagickWand.h... yes
		checking for AutoGammaImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys
		/types.h,wand/MagickWand.h... *** extconf.rb failed ***
		Could not create Makefile due to some reason, probably lack of necessary
		libraries and/or headers.  Check the mkmf.log file for more details.  You may
		need configuration options.

		Provided configuration options:
				--with-opt-dir
				--with-opt-include
				--without-opt-include=${opt-dir}/include
				--with-opt-lib
				--without-opt-lib=${opt-dir}/lib
				--with-make-prog
				--without-make-prog
				--srcdir=.
				--curdir
				--ruby=C:/Ruby21/bin/ruby
		C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:395:in `system': Invalid argument - ruby_setenv(USERDOMAIN) (Errno:
		:EINVAL)
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:395:in `block in xsystem'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:321:in `open'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:385:in `xsystem'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:463:in `try_do'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:742:in `try_func'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:1027:in `block in have_func'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:321:in `open'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:321:in `open'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
				from C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:1026:in `have_func'
				from extconf.rb:281:in `block in <main>'
				from extconf.rb:280:in `each'
				from extconf.rb:280:in `<main>'

		extconf failed, exit code 1

		Gem files will remain installed in C:/Ruby21/lib/ruby/gems/2.1.0/gems/rmagick-2.13.4 for inspection.

		Results logged to C:/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/rmagick-2.13.4/gem_make
		.out

Following string from error output is key: 

		C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:395:in `system': Invalid argument - ruby_setenv(USERDOMAIN) (Errno::EINVAL)

After renaming my PC (in fact USERDOMAIN) using just English alphabet the error disappears.

But after this I get new similar error:

    C:/Ruby21/lib/ruby/2.1.0/mkmf.rb:395:in `system': Invalid argument - ruby_setenv(LOCALAPPDATA) (Errno::EINVAL)

The reason is similar. User name contains cyrilic chars.
It would be good to have this fixed so I should not rename my PC and user name.

I am not sure if this is exactly rmagick gem error. Probably this is error of other component of Ruby, but I have installed other gems successfully.

I am not Ruby developer, I just need to install one RoR app.

**Comment by u338steven** [comment]
Could you please run the following:
```
ruby -e 'puts Encoding.find("filesystem")'
ruby -e 'puts Encoding.find("locale")'
```

If the two values is not same, the solution is probably that you need to set command prompt encoding(locale encoding) appropriately.

Command:
```
chcp [code page identifier]
```

<cite>[Code Page Identifiers (Windows)](https://msdn.microsoft.com/en-us/library/dd317756(VS.85).aspx)</cite>

e.g.:
```
chcp 866
gem install rmagick -v 2.13.4 --platform=ruby -- '--with-opt-dir="C:\ImageMagick-6.7.9-Q16"'
```

possibly ```chcp 855```

**Comment by sergtk** [comment]
Yes, you are right I have different values for encodings. Thanks.

I have following output:

    C:\>ruby -e 'puts Encoding.find("filesystem")'  
    Windows-1251  
    C:\>ruby -e 'puts Encoding.find("locale")'  
    IBM866

I worked around this by renaming user and related folders with ASCII chars only according to instructions at http://social.technet.microsoft.com/wiki/contents/articles/19834.how-to-rename-a-windows-7-user-account-and-related-profile-folder.aspx.
This is acceptable in my case.

Fist time experienced such kind of issues.

**Comment by vassilevsky** [comment]
Такая же проблема в Vagrant :( Он из-под русских аккаунтов не запускается :( Не умеют американцы писать код, работающий вне америки :(

**Comment by sergtk** [comment]
@u338steven 

I tried to install rmagick one more time.
This time I run the following command before installing rmagick:

    chcp 1251

After this rmagick installed successfully. Thanks!
