### ISSUE TITLE
HDRI can't install w/o it apparently

### ISSUE THREAD

**Issue by tejasmanohar** [rmagick/rmagick#178]
This is the PKGBUILD i installed ImageMagick from, https://gist.github.com/tejasmanohar/7a1707d0ba5cf27cfee2

Still, I can't install rmagick, it keeps telling me that HDRI is enabled. I even removed the enable-hdri flag as you can see in that PKGBUILD...

**Comment by linduxed** [comment]
If this is the same issue as rmagick/rmagick#18, then this should have been fixed a long time ago.

Are you using the latest version of RMagick? Unless I'm mistaken the ImageMagick straight from the `[extra]` repository should work.

**Comment by tejasmanohar** [comment]
Um. I'm on latest arch linux, and i did `pacman -S imagemagick` and this error comes. I also tried building it like in the gist, still errors.

gemfile - https://gist.github.com/tejasmanohar/1cf978f048bc6a61e23c

**Comment by tejasmanohar** [comment]
errors -> https://gist.github.com/tejasmanohar/bd7a940da135380ce8eb

**Comment by tejasmanohar** [comment]
@linduxed i uninstalled all imagemagick traces and reinstalled w/ `pacman -S imagemagick` and indeed, it goes back to the original error.

https://gist.github.com/tejasmanohar/af76747f496dac7075b3

>checking for HDRI disabled version of ImageMagick... no (see more in gist)

**Comment by igrep** [comment]
> errors -> https://gist.github.com/tejasmanohar/bd7a940da135380ce8eb

Seems you're installing the older version which causes the error.
Does `bundle update rmagick` change something?

**Comment by linduxed** [comment]
@tejasmanohar Did you try @igrep's suggestion?

**Comment by mockdeep** [comment]
Closing for now. Please open a new issue if you are still having problems.
