### ISSUE TITLE
test_optimize_layers(ImageList2_UT) fails in `/test/ImageList2.rb`

### ISSUE THREAD

**Issue by linduxed** [rmagick/rmagick#186]
```
  1) Failure:
test_optimize_layers(ImageList2_UT) [/home/travis/build/gemhome/rmagick/test/ImageList2.rb:277]:
<2> expected but was
<1>.
```

This problem is blocking #176.

**Comment by u338steven** [comment]
I think the cause might be this:
> When two consecutive frames are identical, the second one will be turned into an empty frame. In this case, the empty frame should be skipped when comparing layers. This patch should fix the problem.


> We can reproduce the problem you posted and have a patch in **ImageMagick 6.9.1-1** Beta, available by sometime tomorrow. Thanks.

<cite>[Skip empty frames when comparing layers - ImageMagick](http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=27234)</cite>


with ImageMagick 6.9.1-1:
```sh
c:\>ruby foo.rb
Version: ImageMagick 6.9.1-1
CompareAnyLayer res.length = 1
CompareClearLayer res.length = 1
CompareOverlayLayer res.length = 1
```

with ImageMagick 6.9.0-9:
```sh
c:\>ruby foo.rb
Version: ImageMagick 6.9.0-9
CompareAnyLayer res.length = 2
CompareClearLayer res.length = 2
CompareOverlayLayer res.length = 2
```

foo.rb:
```ruby
require 'rmagick'

`convert -version` =~ /(Version: ImageMagick \d+\.\d+\.\d+-\d)+ /
puts $1

layer_methods = [
  Magick::CompareAnyLayer,
  Magick::CompareClearLayer,
  Magick::CompareOverlayLayer,
]

ilist = Magick::ImageList.new
ilist << Magick::Image.new(5,5)
ilist << Magick::Image.new(5,5)

layer_methods.each do |method|
  res = ilist.optimize_layers(method)
  puts "#{method} res.length = #{res.length}"
end
```

**Comment by Watson1978** [comment]
Closed with https://github.com/rmagick/rmagick/pull/471
