### ISSUE TITLE
Magick::Image.read hangs with nil argument

### ISSUE THREAD

**Issue by zloyrusskiy** [rmagick/rmagick#200]
`Magick::Image.read(nil)` hangs with no exceptions...

**Comment by vassilevsky** [comment]
Thanks for the report! Could you send a pull request with a failing spec? Feel free to create the necessary spec files — we just started the transition to RSpec and there are just a few specs there.

**Comment by zloyrusskiy** [comment]
Yes, i'll send failing spec some time later.

**Comment by linduxed** [comment]
@zloyrusskiy Do you have a failing spec that we could work with?

**Comment by zloyrusskiy** [comment]
[tests](https://github.com/rmagick/rmagick/pull/230)
