### ISSUE TITLE
support for ImageMagick morphology option

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#21]
<a href="https://github.com/goodwillta"><img src="https://avatars.githubusercontent.com/u/1164364?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [goodwillta](https://github.com/goodwillta)**
_Tuesday Nov 01, 2011 at 08:15 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/35_

----

morphology option is powerful and extremely handy, and has been available since ImageMagick 6.6.0-1. Are there any plans to include the option in rmagick? It would be greatly appreciated.

**Comment by linduxed** [comment]
@vassilevsky Do you feel we can close this, considering the discussion in #184?

**Comment by vassilevsky** [comment]
Yes, there is no use in keeping this issue open.
