### ISSUE TITLE
"stack level too deep" when calling Magick::Image.read within a fiber (Ruby 1.9.3-p0)

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#22]
<a href="https://github.com/mamu"><img src="https://avatars.githubusercontent.com/u/12643?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mamu](https://github.com/mamu)**
_Wednesday Nov 30, 2011 at 01:28 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/38_

---

Hi!

I'm not exactly sure what's going on since I get inconsistent results between my Linux dev box and my OS X dev box, both running the same version of Ruby (1.9.3-p0), both using rvm, both running the same version of RMagick (2.13.1), and both running the same version of ImageMagick (6.7.1, compiled from source).

My OS X dev box plays along nicely, but my Linux dev box throws a "stack level too deep" exception when I call Magick::Image.read within a fiber. I'm using the fiber to untangle evented code in a fashion quite similar to igrigorik's em-synchrony project), so this is all being done within the context of EventMachine's event loop. If I downgrade to Ruby 1.9.2-p290 on my Linux box, RMagick begins to work fine again.

Really at quite a loss why OS X would behave but Linux wouldn't. I don't know what else I ought to provide to help track down the issue, but I'd be happy to post anything extra anyone requests.

Thanks!

**Comment by Watson1978** [comment]
I tried the test code in https://github.com/rmagick/rmagick/issues/22#issuecomment-50021997.

```ruby
require 'rmagick'

def load_image
  image_data = File.open('sample.jpg','rb') { |f| f.read }
  Magick::Image.from_blob(image_data)
end

x = load_image # => [ JPEG 500x500 500x500+0+0 DirectClass 8-bit 71kb]

f = Fiber.new { load_image }
x = f.resume # SystemStackError: stack level too deep

p Magick::Version
p :ok
```

However, I can't the reproduce this issue with Ruby 2.3 and RMagick 3.0.0.

```
$ ruby -v thumbnail.rb
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin18]
"RMagick 3.0.0"
:ok
```

I will close this issue. But, feel free to reopen if you met the same issue.
