### ISSUE TITLE
ImageMagick 6.9.1 - gem not installing due to libMagickWand

### ISSUE THREAD

**Issue by ZipoKing** [rmagick/rmagick#223]
After my system has upgraded ImageMagick to version 6.9.1 (Slackware64 current) I haven't been able to reinstall rmagick gem.
After some investigation I've found that libMagickWand is not being added to libraries list during compilation. But when I've removed /usr/bin/Magick-config and symlinked /usr/bin/MagickWand-config to it gem has compiled.
I think that during compilation additional check if MagickWand-config is present should be made as Magick-config will not work.

**Comment by mockdeep** [comment]
@ZipoKing is this still an issue for you as of RMagick 3.0.0?

**Comment by mockdeep** [comment]
No response, so I'm closing this for now. If it still fails for you on RMagick >= 3.0, please open a new issue.
