### ISSUE TITLE
compile error on Windows

### ISSUE THREAD

**Issue by Lafunamor** [rmagick/rmagick#225]
I get a compile error on windows (and a lot of warnings...):
rmimage.c:9911:21: error: invalid type argument of unary '*' (have 'int')

any idea how I can resolve this?

**Comment by bf4** [comment]
Can you tell us a bit more about your development environment and which rmagick you are installing?

**Comment by NobodysNightmare** [comment]
Same error for me:

* Windows 10
* `ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]` (via RailsInstaller)
* ImageMagick-6.9.2-7-Q16-x64-dll
* latest RMagick (whatever rubygems would give me today)

Please tell me which other details you could use...

Reading the above, I might be trying to use a 64 Bit ImageMagick with a 32 Bit ruby.
Investigating... (will edit when I find out more)

**Comment by linduxed** [comment]
Closing since #228 was merged.
