### ISSUE TITLE
Image#write doesn't work for svg string 

### ISSUE THREAD

**Issue by sonalkr132** [rmagick/rmagick#226]
I am trying to get back my svg file from its blob. However it doesn't seem to work. I have following code and corresponding output:

``` Ruby
image = Magick::Image.read("public/logo.svg").first
 => public/logo.svg SVG 64x64 64x64+0+0 DirectClass 16-bit 4kb
blob_image = Magick::Image.from_blob(image.to_blob).first
 =>  SVG 64x64 64x64+0+0 DirectClass 16-bit 187kb
blob_image.write "public/new_logo.svg"
=> public/new_logo.svg SVG 64x64 64x64+0+0 DirectClass 16-bit 260kb 
```

Now if I try to open "new_logo.svg" I get following error (in gimp):

> Could not open '/some-path/public/new_logo.svg' for reading: Error domain 1 code 73 on line 4051 column 20 of file:///some-path/public: Couldn't find end of Start Tag circle

There is also a significant increase in file size (from 4kb to 260kb).

**Comment by Watson1978** [comment]
This problem should be reported to ImageMagick.
The broken file is saved when SVG is processed and saved with ImageMagick commands.

```
convert -density 100 -background none Ghostscript_Tiger.svg test.svg
```
