### ISSUE TITLE
setting density doesn't appear to work

### ISSUE THREAD

**Issue by dkniffin** [rmagick/rmagick#227]
I'm trying to write some code that will take in an svg, resize it up, and output a png.

[source svg file](https://gist.github.com/dkniffin/e39cabf3512d3fb7a79a)

This works fine using imagemagick's convert command:

```
convert -density 600 -sample 1600x1600 circle.svg out.png
```

![convert_out](https://cloud.githubusercontent.com/assets/1680080/10667636/5341ee6c-78a6-11e5-84eb-c9695612b2de.png)

But when I use rmagick to do the same thing:

``` ruby
image = Magick::Image.read("oval.svg"){|a| a.density = "600"}.first
image.sample! 100
image.write("out.png")
```

I get pixelation problems
![rmagick_out](https://cloud.githubusercontent.com/assets/1680080/10667654/626ec68a-78a6-11e5-982d-de3a63f75649.png)

I'm pretty sure the root problem here is that rmagick isn't respecting the density attribute properly.

This issue has appeared in a bunch of places around the web, but I've yet to find a solution that works:
- http://stackoverflow.com/questions/6237540/setting-density-upon-image-read-with-rmagick
- https://www.ruby-forum.com/topic/73965
- https://github.com/rmagick/rmagick/issues/67
- https://github.com/rmagick/rmagick/issues/29

**Comment by tamagokun** [comment]
Also having density issues. Trying to output an image at something other than 72 dpi, and nothing seems to work. I've tried `self.density` `x_resolution` `y_resolution` and `resample` and none of them changed the output dpi.

**Comment by tamagokun** [comment]
Need to specify the units beforehand! This bugged the crap out of me for weeks..

Something like this should work..

```ruby
image = Magick::Image.read("oval.svg") {
  self.units = Magick::PixelsPerInchResolution
  self.density = "600"
}.first
```

**Comment by Watson1978** [comment]
If at least one argument is given to the sample method, its value means scale.

```
 * @overload sample(scale)
 *   @param scale [Numeric] You can use this argument instead of specifying the desired width and
 *     height. The percentage size change. For example, 1.25 makes the new image 125% of the size of
 *     the receiver. The scale factor 0.5 makes the new image 50% of the size of the receiver.
```

So, `image.sample! 100` resize to 10000% size. Looks for me that it is not same with `covert` command sample.
