### ISSUE TITLE
This installation of RMagick was configured with ImageMagick 6.8.9 but ImageMagick 6.9.0-3 is in use. (RuntimeError)

### ISSUE THREAD

**Issue by timproctor** [rmagick/rmagick#234]
I'm getting this error at runtime: 

``` shell
This installation of RMagick was configured with ImageMagick 6.8.9 but ImageMagick 6.9.0-3 is in use. (RuntimeError)
```

I recognize that I could reinstall a version of ImageMagick that is older than a year, but what fun is that? I also recognize that I could submit a pull request with my own fix, but admittedly I'm not sure where to begin. 

I'd rather fix the issue than work-around it, just need some guidance. For example, the error is being reported from `rmagick-2.15.4/lib/rmagick_internal.rb, line 12` but when I investigate line it is this: ` `  `require 'RMagick2.so'` and then reading further there is a comment that says: 

``` ruby
#   Notes:      RMagick2.so defines the classes. The code below adds methods
#                    to the classes.
```

digging deeper in the gem I found my work-around but using it means that I ignore a test that seems useful:

``` c
/**
 * Ensure the version of ImageMagick we're running with matches the version we
 * were compiled with.
 *
 * No Ruby usage (internal function)
 *
 * Notes:
 *   - Bypass the test by defining the constant RMAGICK_BYPASS_VERSION_TEST to
 *     'true' at the top level, before requiring 'RMagick'
 */
```

so in the app that uses rmagick, I set `RMAGICK_BYPASS_VERSION_TEST = true` and the Runtime Error is gone and everything works. I know, total hack.

Again, if anyone has guidance they can give me on reworking gem itself that would be great.

**Comment by zenry** [comment]
In case somebody stumbles upon this, just reinstall `rmagick` and it will work again

https://github.com/rmagick/rmagick/issues/245#issuecomment-217435978

**Comment by mockdeep** [comment]
@timproctor were you able to work around this issue?

**Comment by ugifractal** [comment]
Got same issue. seem this happen because identify version doesn't same with Magick-config version.
I tried to compare
```
identify -version
```

and

```
Magick-config --version
```

When they have different version, the error raised.

I ended up using version 6.9.10-23 for ImageMagick where identify and Magick-config have same version.
