### ISSUE TITLE
Proposal: Draw#primitives accessor

### ISSUE THREAD

**Issue by zverok** [rmagick/rmagick#239]
It's a bit unholy idea, but...
- `primitives` is already a Ruby string, and reading/writing it will not be much of complex C code;
- it will allow advanced techniques like "remove unnecessary primitive", or "rescale all/some primitives to another sizes" and so on;
- I can't see any Really Bad Consequences in idea: I assume (though, need check) ImageMagick will just raise some kind of error on malformed primitves string, which can be just converted to Ruby exception.

WDYT?

**Comment by Watson1978** [comment]
I can't think of a useful use case for supporting this.
Editing primitives directly requires familiarity with ImageMagick, so I think it is tough to use.

Feel free to reopen if you have any idea.
