### ISSUE TITLE
Image#morphology and Image#morphology_channel

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#24]
<a href="https://github.com/naquad"><img src="https://avatars.githubusercontent.com/u/20373?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [naquad](https://github.com/naquad)**
_Friday Dec 02, 2011 at 14:57 GMT_
_Originally opened as https://github.com/rmagick/rmagick/pull/40_

---

Implementation of Image#morphology and Image#morphology_channel methods, also implemented KernelInfo class used by morphology and bitwise or for enums.

---

_**[naquad](https://github.com/naquad)** included the following code: https://github.com/rmagick/rmagick/pull/40/commits_

**Comment by macbar** [comment]
any update on this one would be greatly appreciated

Thanks

**Comment by Watson1978** [comment]
Seems that Image#morphology and Image#morphology_channel were implemented
