### ISSUE TITLE
Unable to extend cache error when processing more than a single image

### ISSUE THREAD

**Issue by pratik60** [rmagick/rmagick#240]
Is there a way to increase memory size?

Failure/Error: Unable to find matching line from backtrace
     Magick::ImageMagickError:
       unable to extend cache `fixtures/images/logo.png': No space left on device @ error/cache.c/OpenPixelCache/3691
     # /Users/pratikbothra/.rvm/gems/ruby-2.2.2/gems/rmagick-2.15.4/lib/rmagick_internal.rb:1681:in`scale'

This happened right after I tried to process two small images in different threads. Weirdly, if I try to do multiple operations on the same image in different threads, that works just fine.

Anything else what I can do to fix the error?

**Comment by carsonreinke** [comment]
Try setting the [`Magick.set_cache_threshold`](http://www.rubydoc.info/gems/rmagick/2.15.4/Magick#set_cache_threshold-class_method) or [`Magick.limit_resource`](http://www.rubydoc.info/gems/rmagick/2.15.4/Magick#limit_resource-class_method).

**Comment by Watson1978** [comment]
The memory usage of RMagic was improved by https://github.com/rmagick/rmagick/pull/836
And you can control it by [Magick.set_cache_threshold](http://www.rubydoc.info/gems/rmagick/2.15.4/Magick#set_cache_threshold-class_method) or [Magick.limit_resource](http://www.rubydoc.info/gems/rmagick/2.15.4/Magick#limit_resource-class_method).

Feel free to reopen the issue if you still have a problem.
