### ISSUE TITLE
Image.read does not report "data not returned" for HTTPS URI when the image doesn't exist

### ISSUE THREAD

**Issue by thedrow** [rmagick/rmagick#242]
When performing
`ruby
Magick::Image.read 'https://google.com/1.jpg'
`
I expect to get the following error message:

> Magick::ImageMagickError: no data returned `https://google.com/1.jpg' @ error/url.c/ReadURLImage/264
> If I do the same for a site served with HTTP e.g.
> ``ruby
> Magick::Image.read 'http://cnn.com/1.jpg'
> ``
> I do get the expected error message.

Instead the following error message is supplied:

> Magick::ImageMagickError: unable to open image `/var/tmp/magick-20428fjy5iHtQV8l0': No such file or directory @ error/blob.c/OpenBlob/2702

The latter error message is less informative and doesn't provide the correct insight about what went wrong when downloading the image.

**Comment by Watson1978** [comment]
I believe this stems from the way ImageMagick retrieves data via HTTP.
Please report this to ImageMagick team.
