### ISSUE TITLE
build error according to readme badge

### ISSUE THREAD

**Issue by matkoniecz** [rmagick/rmagick#247]
https://github.com/rmagick/rmagick#rmagick

**Comment by linduxed** [comment]
Most of the builds seem to be failing with the same error that was supposed to be resolved with #229. I don't know why this is the case.

We also have a build failing to run basically because it's using Ruby 1.8, which we should have dropped in #232.

**Comment by vassilevsky** [comment]
I fixed it by pinning some dependencies to older versions
