### ISSUE TITLE
is it semantically versioned?

### ISSUE THREAD

**Issue by matkoniecz** [rmagick/rmagick#249]
During building my gem I encountered

```
WARNING:  pessimistic dependency on rmagick (~> 2.15.2) may be overly strict
  if rmagick is semantically versioned, use:
    add_runtime_dependency 'rmagick', '~> 2.15', '>= 2.15.2'
```

In readme and in repository search I failed to find answer for this question.

**Comment by vassilevsky** [comment]
Yes, we use Semantic Versioning. So if you want to have a working version 2.x of the gem, you can specify `'rmagick', '~> 2.0'`.

**Comment by vassilevsky** [comment]
I have added the necessary information to README:

https://github.com/rmagick/rmagick#versioning
