### ISSUE TITLE
While reading image file,colorspace will not be set in block 

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#25]
<a href="https://github.com/rempargo"><img src="https://avatars.githubusercontent.com/u/261394?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rempargo](https://github.com/rempargo)**
_Thursday Dec 29, 2011 at 21:20 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/41_

---
# this doesn't work,

```
image = Magick::Image.new(100,100){
 self.colorspace = Magick::LABColorspace
}
p image.colorspace == Magick::LABColorspace
```
# this works

```
image = Magick::Image.new(100,100)
image.colorspace = Magick::LABColorspace
p image.colorspace == Magick::LABColorspace
```

Why can't the colorspace be set during the block? Is this a bug or intended (if so, why?).

**Comment by mockdeep** [comment]
I can confirm that this is still an issue on RMagick 3.1. Slight difference, though, in that `LABColorspace` has been renamed to `LabColorspace`:

```irb
image = Magick::Image.new(100,100){ self.colorspace = Magick::LabColorspace }
image.colorspace # => sRGBColorspace=13
image.colorspace = Magick::LabColorspace
image.colorspace # => UndefinedColorspace=5
```
