### ISSUE TITLE
error installing on windows with ImageMagick-7.0.2-Q16

### ISSUE THREAD

**Issue by aronlmin** [rmagick/rmagick#254]
there was no MakeFile, the output of my gem_make.out file is the following:

C:/Ruby22/bin/ruby.exe -r ./siteconf20160722-5376-17dhnqb.rb extconf.rb --with-opt-dir="C:\Program Files (x86)\ImageMagick-7.0.2-Q16"
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=C:/Ruby22/bin/$(RUBY_BASE_NAME)
extconf.rb:110:in ``': No such file or directory - identify -version (Errno::ENOENT)
    from extconf.rb:110:in`configure_compile_options'
    from extconf.rb:16:in `initialize'
    from extconf.rb:517:in`new'
    from extconf.rb:517:in `<main>'

extconf failed, exit code 1

**Comment by mockdeep** [comment]
Closing, you can follow https://github.com/rmagick/rmagick/issues/256 for progress on ImageMagick 7 support.
