### ISSUE TITLE
Building Rmagick with specific version of IM

### ISSUE THREAD

**Issue by bwalton** [rmagick/rmagick#260]
Hello everyone!

**My issue:**
I'm using an updated version of IM on my Heroku app, but Rmagick only builds with the older system version that's present.

**Detail:**
On my Heroku app, I've used a buildpack to update the old system version of ImageMagick (6.7.7) with my preferred version (6.8.9). This particular buildpack puts the new IM in `/app/vendor/imagemagick` and sets all the paths accordingly.

This seems to work great, as I can do login into my app instance and get this:
```
convert --version
Version: ImageMagick 6.8.9-10 Q16 x86_64 2016-12-24 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC OpenMP
Delegates: bzlib djvu fontconfig freetype jbig jng jpeg lcms lqr lzma openexr png tiff x xml zlib
```

But it seems that when building Rmagick (I've tried 2.16 and 2.15.4), it always uses the "system" version of IM:
```
irb(main):002:0> Magick::Long_version
"This is RMagick 2.15.4 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 6.7.7-10 2016-11-29 Q16 http://www.imagemagick.org
Built for ruby 2.1.8
Web page: http://rmagick.rubyforge.org\nEmail: rmagick@rubyforge.org\n"
```

I've ran the **extconf.rb** manually to see what's going on and it finds multiple versions, which is correct:
```
Warning: Found more than one ImageMagick installation. This could cause problems at runtime.
         /app/vendor/imagemagick/bin/Magick-config reports version 6.8.9 Q16 is installed in /app/vendor/imagemagick
         /usr/bin/Magick-config reports version 6.7.7 Q16 is installed in /usr
Using 6.8.9 Q16 from /app/vendor/imagemagick.
```
_(I've simplified the temp paths that Heroku sticks my app in)_

And here are my config options it prints out at the end:
`{:magick_config=>true, :pkg_config=>false, :magick_version=>"6.8.9", :local_libs=>" -lMagickCore  ", :cflags=>" -fopenmp -I/usr/include/ImageMagick  ", :cppflags=>" -fopenmp -I/usr/include/ImageMagick  ", :ldflags=>" -lMagickCore  ", :defs=>[], :config_h=>"Makefile rmagick.h"}
`

Is my issue paths? Looking at the options above, cflags and cppflags are pointing to `/usr/include/ImageMagick`. Wouldn't I need it to point to my separate version of IM at `/app/vendor/imagemagick/include`?

Any help or guidance would be my appreciated. Thanks for reading!

**Comment by Watson1978** [comment]
You can use ImageMagick installed in a special directory by setting `PKG_CONFIG_PATH` environment variable properly.

Ex)
```
$ export PKG_CONFIG_PATH=$HOME/imagemagick6.9/lib/pkgconfig
```

If you use Linux system, you might need to set `LD_LIBRARY_PATH` additionally.
```
export LD_LIBRARY_PATH=$HOME/imagemagick6.9/lib
```
