### ISSUE TITLE
Need documentation for Hex Code

### ISSUE THREAD

**Issue by melaniegershman** [rmagick/rmagick#262]
I'm using `#to_color` to get a hex code; how can I exclude `compliance, matte, depth` from the output? @snuggs @janz93

**Comment by Watson1978** [comment]
You can see the document in [Pixel#to_color](https://rmagick.github.io/struct.html#Pixel:~:text=G%2B0.114*B.-,to_color,-pixel.to_color).

Unfortunately, you will need to set all arguments even if you only want to set `hex=true`.
