### ISSUE TITLE
Building native extensions.  This could take a while... ERROR:  Error installing rmagick:

### ISSUE THREAD

**Issue by rekha014** [rmagick/rmagick#272]
ruby-1.9.3-p551

Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    /home/rekha/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -r ./siteconf20170728-25028-v8lcql.rb extconf.rb

**Comment by linduxed** [comment]
Hello @rekha014! We do not support Ruby versions lower than 2.0.0.
