### ISSUE TITLE
unable to install RMagick on macOS High Sierra

### ISSUE THREAD

**Issue by unbewusst** [rmagick/rmagick#276]
mkmf.log says 
ld: can't map file, errno=22 file '/usr/local/opt/openssl/include' for architecture x86_64

however this directory includes 
$ ls -al /usr/local/opt/openssl/include
total 0
drwxr-xr-x   3 yt  admin    96B 10 oct 09:01 .
drwxr-xr-x  13 yt  admin   416B  8 oct 15:56 ..
drwxr-xr-x  77 yt  admin   2,4K  8 oct 11:29 openssl

with 
$ ls -al /usr/local/opt/openssl/include/openssl
total 3704
drwxr-xr-x  77 yt  admin   2,4K  8 oct 11:29 .
drwxr-xr-x   3 yt  admin    96B 10 oct 09:01 ..
-rw-r--r--   1 yt  admin   6,0K 25 mai 14:55 aes.h
-rw-r--r--   1 yt  admin    62K 25 mai 14:55 asn1.h
-rw-r--r--   1 yt  admin    24K 25 mai 14:55 asn1_mac.h

[...]

-rw-r--r--   1 yt  admin    52K 25 mai 14:55 x509.h
-rw-r--r--   1 yt  admin    29K 25 mai 14:55 x509_vfy.h
-rw-r--r--   1 yt  admin    39K 25 mai 14:55 x509v3.h

the whole mkmf.log being
$ cat /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0/rmagick-2.16.0/mkmf.log
find_executable: checking for clang... -------------------- yes
--------------------
find_executable: checking for Magick-config... -------------------- no
--------------------
find_executable: checking for pkg-config... -------------------- yes
--------------------
configure_compile_options: checking for outdated ImageMagick version (<= 6.4.9)... -------------------- no
Detected ImageMagick version: 7.0.7
--------------------
configure_compile_options: checking for presence of MagickWand API (ImageMagick version >= 6.9.0)... -------------------- no
Detected 6.9+ version, using MagickWand API--------------------
assert_minimum_ruby_version!: checking for Ruby version >= 1.8.5... -------------------- yes
--------------------
"clang -o conftest -I/usr/local/Cellar/ruby/2.4.2/include/ruby-2.4.0/x86_64-darwin17 -I/usr/local/Cellar/ruby/2.4.2/include/ruby-2.4.0/ruby/backward -I/usr/local/Cellar/ruby/2.4.2/include/ruby-2.4.0 -I.  -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.7-7/include/ImageMagick-7 /usr/local/opt/openssl/include -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.7-7/include/ImageMagick-7 conftest.c  -L. -L/usr/local/Cellar/ruby/2.4.2/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib /usr/local/opt/openssl/lib -L/usr/local/Cellar/imagemagick/7.0.7-7/lib -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI    -L/usr/local/Cellar/imagemagick/7.0.7-7/lib -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI  -lruby.2.4.2  -lpthread -ldl -lobjc "
ld: can't map file, errno=22 file '/usr/local/opt/openssl/include' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

my ImageMagick version is 7.0.7-7 (installed by homebrew)
$ /usr/local/bin/magick --version
Version: ImageMagick 7.0.7-7 Q16 x86_64 2017-10-08 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib

and my ruby version
$ /usr/local/bin/ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

and my macOS version is High Sierra Version 10.13 (17A405)

I'm stuck ))

**Comment by hugobarthelemy** [comment]
I had the same problem and I found this solution:
https://stackoverflow.com/questions/39494672/rmagick-installation-cant-find-magickwand-h

**Comment by seliverstov-maxim** [comment]
see: https://github.com/rmagick/rmagick/pull/284

I just solve problem with installing rmagick on OS X. I was faced with incompatible rmagick with imagemagick 7.x.x ver.
I had to rollback the imagemagick version to 6.9.6-5.

brew switch imagemagick 6.9.6-5

**Comment by mockdeep** [comment]
Closing, you can follow https://github.com/rmagick/rmagick/issues/256 for progress on ImageMagick 7 support.
