### ISSUE TITLE
Install with bundler on Windows

### ISSUE THREAD

**Issue by boneandrea** [rmagick/rmagick#277]
https://github.com/rmagick/rmagick/wiki/Installing-on-Windows

>gem install rmagick -- '--with-opt-dir="[path to ImageMagick]"'

how can i do this with bundler?
I tried:
>bundle config --local build.rmagick '--platform=ruby --with-opt-dir="%MAGICKDIR%"'
>bundle install

but i couldn't find magick-config.

>checking for Magick-config... no
> Can't install RMagick 2.7.1. Can't find Magick-config in $PATH

**Comment by boneandrea** [comment]
append:

>gem install rmagick -- '--with-opt-dir="[path to ImageMagick]"'

this worked well, but i want to do with bundler.

**Comment by mockdeep** [comment]
Hi @boneandrea, thanks for reporting. Is this still an issue for you as of RMagick version 3.0.0?

**Comment by mockdeep** [comment]
No response, so I'm closing this for now. If it still fails for you on RMagick >= 3.0, please open a new issue.

**Comment by boneandrea** [comment]
hmm, I didn't try the version.
