### ISSUE TITLE
Resize very slow

### ISSUE THREAD

**Issue by park9140** [rmagick/rmagick#281]
I have an image that is 3000x9000

I want to stretch it out

So I run
```
rescale_method = 'LagrangeFilter';
image.resize(
     6000,
      12693,
      Magick.const_get(rescale_method)
    )
```

This takes 600+ seconds in rmagick!

In convert directly it takes 7 seconds.  
```
/usr/bin/time -l convert download.png -filter Lagrange -resize 12693x6000\! test.png
        7.74 real         7.08 user         0.59 sys
1150365696  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
    323193  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         3  block output operations
         0  messages sent
         0  messages received
         0  signals received
         0  voluntary context switches
      9917  involuntary context switches
```

Am I missing something?

**Comment by Watson1978** [comment]
I think this problem is related to memory usage.
If the free memory is not enough spece available, OS will repeat swap in/out and processing will take longer.
And it causes a longer time for processing.

I believe your problem will be solved by https://github.com/rmagick/rmagick/pull/697

**Comment by Watson1978** [comment]
I think you can solve your issue with RMagick 3.2.0 and ImageMagick 6.9.10-49+.

If you can not introduce  ImageMagick 6.9.10-49+, I think you can solve with starting Ruby GC manually before resizing.

ie)
```ruby
GC.start # Add

rescale_method = 'LagrangeFilter';
image.resize(
     6000,
      12693,
      Magick.const_get(rescale_method)
    )
```

**Comment by mockdeep** [comment]
@park9140 are you still seeing this issue on RMagick >= 3.2 and ImageMagick >= 6.9.10-49?

**Comment by park9140** [comment]
We ended up abandoning Rmagic because of this bug.  We don't require access to a bunch of the tighter integrations rmagic provides so it was simple to switch to minimagick so we did in order to bypass this issue.

**Comment by mockdeep** [comment]
Okay, thanks for following up.
