### ISSUE TITLE
Installing rmagick in a centos:7 docker

### ISSUE THREAD

**Issue by disastrous-charly** [rmagick/rmagick#282]
Hi there, 

I have an issue when I want to install rmagick in a centos:7 docker container.
convert --version
Version: ImageMagick 6.7.8-9 2016-06-16  

ruby -v
ruby 2.4.2p198

The issue : 
`gem install rmagick
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    current directory: /usr/lib64/ruby/gems/2.4.0/gems/rmagick-2.16.0/ext/RMagick
/usr/bin/ruby -r ./siteconf20171121-145-4dfhmn.rb extconf.rb
checking for gcc... yes
checking for Magick-config... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
extconf.rb:189:in ``': No such file or directory - which (Errno::ENOENT)
	from extconf.rb:189:in `has_graphicsmagick_libmagick_dev_compat?'
	from extconf.rb:66:in `configure_compile_options'
	from extconf.rb:16:in `initialize'
	from extconf.rb:548:in `new'
	from extconf.rb:548:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/lib64/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/rmagick-2.16.0/mkmf.log`

I have ImageMagick ImageMagick-devel ImageMagick-c++ ImageMagick-c++-devel in the container, no issue in installing other gems.

Any Idea ?

**Comment by yasuhiroki** [comment]
> extconf.rb:189:in ``': No such file or directory - which (Errno::ENOENT)

You should install `which` command with `yum install which`.

**Comment by mockdeep** [comment]
@disastrous-charly were you able to resolve your issue?

**Comment by mockdeep** [comment]
Closing for now. If you can provide more information, please let us know and we can re-open.
