### ISSUE TITLE
Tests are starting to fail with recent ImageMagick 6.x releases

### ISSUE THREAD

**Issue by mooninite** [rmagick/rmagick#288]
Sometime inbetween ImageMagick 6.9.9-19 and 6.9.9-22 a test in Rubygem-rmagick fails that previously passed. More tests are failing with ImageMagick 6.9.9-28 and higher. I do not have time to fully debug, diagnose, and patch the issue so I need to request someone here to assist.

ImageMagick issue: https://github.com/ImageMagick/ImageMagick/issues/857

First test failure:
/usr/share/gems/gems/rmagick-2.16.0/test/ImageList1.rb:36:in ```test_iterations'

New test failure: 
/usr/share/gems/gems/rmagick-2.16.0/test/ImageList2.rb:205:in ````test_montage'

**Comment by mockdeep** [comment]
We're tracking build failures for 6.9 in #340.
