### ISSUE TITLE
Resolution management

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#29]
<a href="https://github.com/daniel2d2art"><img src="https://avatars.githubusercontent.com/u/1036505?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [daniel2d2art](https://github.com/daniel2d2art)**
_Saturday Feb 11, 2012 at 21:40 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/46_

---

Hi

I've next resource: 

file: 300dpi.jpg 
dimensions: 1782px x 1181px 
size: 304539 bytes 
resolution: 300dpi x 300dpi

when I use:   

``` ruby
image.resize_to_fill!(460, 345)
```

I get:
file: 300dpi_conversion_1.jpg 
dimensions: 460px × 345px
size: 21718 bytes
resolution: 300dpi x 300dpi
Result: Ok expected

Now I want to try reduce the resolution, I use: 

``` ruby
image.density="72x72"
image.resize_to_fill!(460, 345)
```

I get:
file: 300dpi_conversion_2.jpg 
dimensions: 460px × 345px
size: 21718 bytes
resolution: 72dpi x 72dpi
Result: resolutions seems change but size its the same at 300x300

No I try to reduze adding resample too, I use: 

``` ruby
image.resample(72.0, 72.0)
image.density="72x72"
image.resize_to_fill!(460, 345)
```

I get:
file: 300dpi_conversion_3.jpg 
dimensions: 460px × 345px
size: 21718 bytes
resolution: 72dpi x 72dpi
Result: resolutions seems the same 72x72 as above test, but size its the same at 300x300 too

???
How change resolutions works???, I don't get clareance about it on documentation, it's working ok?
How can I upload a image file (JPG, GIF, PNG) optional (TIFF, BMP), and transform they change resolution and resize?

Thanks

**Comment by Watson1978** [comment]
I think the DPI will not affect the file size of the image.
https://en.wikipedia.org/wiki/Dots_per_inch

If you want a more small file size, I think you need to narrow the image or reduce quality.
