### ISSUE TITLE
Supressing error messaging

### ISSUE THREAD

**Issue by AsWali** [rmagick/rmagick#290]
The pdf file I work with gives me the following error : 
`   **** Error: /BBox has zero width or height, which is not allowed.
               Output may be incorrect.
`
Is there a way to turn this off ? I have tried using the gs command sOutputfile, but it doens't supress the error message.

**Comment by Watson1978** [comment]
I'm guessing this is related to https://bugs.ghostscript.com/show_bug.cgi?id=697359
Please upgrade ghostscript version.
