### ISSUE TITLE
Installed rmagick gem can't find library modules (Windows)

### ISSUE THREAD

**Issue by deining** [rmagick/rmagick#291]
Hi,

I'm on Windows server 2012 with ruby 2.4.3 from rubyinstaller2.

```
C:\>ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [i386-mingw32]
```

I managed to succesfully install rmagick gem

```
C:\>gem list rmagick

*** LOCAL GEMS ***

rmagick (2.16.0)
```
However, when using the gem, it complains about a missing module file 'RMagick.so'. This file 'RMagick2.so is present on my system, however:

```
C:\>irb
irb(main):001:0> require "RMagick"
LoadError: 126: Das angegebene Modul wurde nicht gefunden.   - C:/Ruby2.4.3/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0/lib/RMagick2.so
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby2.4.3/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0/lib/rmagick_internal.rb:12:in `<top (required)>'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby2.4.3/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0/lib/RMagick.rb:1:in `<top (required)>'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby2.4.3/bin/irb.cmd:19:in `<main>'
irb(main):002:0>
```

I tried to fix this by copying all Imagemagick dll's into ruby's bin directory, to no avail.

Any ideas how to fix that?

Thanks
Andreas

**Comment by bf4** [comment]
how did you install RMagick? have you tried ` require "rmagick"`?

try `gem uninstall -aIx rmagick; gem install rmagick`

**Comment by deining** [comment]
> how did you install RMagick?

```
C:\>gem install rmagick
Fetching: rmagick-2.16.0.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
Successfully installed rmagick-2.16.0
Parsing documentation for rmagick-2.16.0
Installing ri documentation for rmagick-2.16.0
Done installing documentation for rmagick after 3 seconds
1 gem installed
```
> have you tried require "rmagick"?

Yes, to no avail.

> try gem uninstall -aIx rmagick; gem install rmagick

I tried this, same result.

No idea what's wrong here. It used to work with ruby 2.3.

**Comment by deining** [comment]
It seems like I'm not the only one who is experiencing difficulties here. See:

https://medium.com/ruby-on-rails-web-application-development/install-rmagick-gem-on-windows-7-8-10-imagemagick-6-9-4-q16-hdri-5492c3fef202

Lower part, section titled "UPDATE 2017 (RMAGICK2.so Error)"

The author recommends to copy Imgemagick dll's into Ruby's bin directory to cure the problem. This didn't work for me, however.

**Comment by deining** [comment]
Eventually, I could solve my issue by copying **all** dlls to ruby's bin directory.

So if you are affected, be sure to copy **all** dll files to the directory, not only those dll files starting with CORE_RL..._ !!!

**Comment by LItterBoy-GB** [comment]
use windows api `SetDllDirectory` to  add dll path.
```cpp
require 'fiddle/import'
require 'fiddle/types'
module WinAPI
  extend Fiddle::Importer
  dlload 'kernel32.dll'
  include Fiddle::Win32Types
  extern 'int SetDllDirectory(LPCSTR)'
end
WinAPI.SetDllDirectory('C:/Program Files/ImageMagick-7.1.1-Q16-HDRI')
```
