### ISSUE TITLE
Error saving valid gDrive image using rmagick/CarrierWave

### ISSUE THREAD

**Issue by rebase-master** [rmagick/rmagick#293]
I am getting the following error when I try to add a valid google drive image to another column that triggers the **Carrierwave** mount_uploader. When I try to save the object it raises the following error:

`Validation failed: S3 image Failed to manipulate with rmagick, maybe it is not an image? Original Error: no decode delegate for this image format /app/public/uploads/tmp/23823/thumb_open-uri234223 @ error/constitute.c/ReadImage/544`

**Gem/Software Versions in use:**

Ruby: 2.3.1
Rails: 4.2.7.1
rmagick: 2.16.0
ImageMagick: 6.7.7-10

It used to work fine earlier. We haven't changed any gem versions. Can you provide some insight into this sort of error?

**Comment by Watson1978** [comment]
I'm guessing the error may be due to old ImageMagick.
Or maybe the target image file didn't exist.

Feel free to reopen if you have still any problem.
