### ISSUE TITLE
Stack corruption

### ISSUE THREAD

**Issue by itaibenari** [rmagick/rmagick#301]
this https://github.com/rmagick/rmagick/blob/develop/ext/RMagick/rmimage.c#L5396 will cause stack corruption if no profiles exist on the image.

**Comment by mockdeep** [comment]
Hey @itaibenari thanks for reporting. Is there any chance you can provide a code sample the reproduces the issue?

**Comment by Watson1978** [comment]
https://github.com/rmagick/rmagick/blob/ff60984be5792a91a4853ee15bbb203a97dd6afd/ext/RMagick/rmimage.c#L5396

Your issue was fixed with https://github.com/rmagick/rmagick/pull/737
Thank you.
