### ISSUE TITLE
unable to install rmagick 2.15.4 in rails even after installing Imagemagick 6.9.x  in windows 

### ISSUE THREAD

**Issue by saieswar** [rmagick/rmagick#302]
unable to install rmagick 2.15.4 in rails even after installing Imagemagick 6.9.x  in windows 
cpath and lib path was also set but it cannot build native libraries .

ERROR:

This could take a while...
ERROR:  Error installing rmagick:
        ERROR: Failed to build gem native extension.

    current directory: U:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rmagick-2.16.0/ext/RMagick
U:/Ruby23-x64/bin/ruby.exe -r ./siteconf20180817-10316-124fhcr.rb extconf.rb --with-opt-dir="U/Image
Magick-6.9.3-Q16-HDRI"

**Comment by mockdeep** [comment]
Hi @saieswar, are you still having problems installing in Windows as of version 3.0.0?

**Comment by mockdeep** [comment]
Closing for now. If you're still seeing issues, let us know and we can reopen.
