### ISSUE TITLE
Install instruction for windows

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#31]
<a href="https://github.com/wingfire"><img src="https://avatars.githubusercontent.com/u/177376?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wingfire](https://github.com/wingfire)**
_Saturday Mar 31, 2012 at 01:58 GMT_
_Originally opened as https://github.com/rmagick/rmagick/pull/50_

---

Hi,
i combined the available install instructions to a file in the code.

---

_**[wingfire](https://github.com/wingfire)** included the following code: https://github.com/rmagick/rmagick/pull/50/commits_

**Comment by mockdeep** [comment]
Original PR is here: https://github.com/rmagick-temp/rmagick/pull/50
