### ISSUE TITLE
After image resize new images are partially greyed out

### ISSUE THREAD

**Issue by ramesh-choudhary** [rmagick/rmagick#313]
gem 'rmagick', '~> 2.15.4'

Occasionally (about 1 in 100 times) an image does not resize correctly and the bottom half of it becomes grey (although not the grey I was setting for the background) and also the image becomes blurry sometimes.

Here's my sample code:

url_img = open(URI.encode(object.url))
image = Magick::ImageList.new
image.from_blob(url_img.read)
final_image_name = image_name(object, object_type)
img_size = [image[0].columns, image[0].rows]

if img_size[0] > img_size[1]
dimensions = [size[1],(size[1] * img_size[1]/img_size[0])]
else
dimensions = [(size[2]*img_size[0]/img_size[1]),size[2]]
end
resized_image = image.resize(dimensions[0],dimensions[1])
resized_image = resized_image.strip!

watermarked_image = resized_image
watermarked_image.units = Magick::PixelsPerInchResolution
watermarked_image.set_channel_depth(Magick::AllChannels,8)
watermarked_image.density = "72"
watermarked_image.write(temp_file_path)

Original Image: https://i.stack.imgur.com/hVorA.jpg

Generated Image: https://i.stack.imgur.com/es95r.jpg

**Comment by Watson1978** [comment]
I wonder if ImageMagick encountered an error when saving the image.
Unfortunately, I can't reproduce this problem...

Feel free to reopen if you have still any problem.
