### ISSUE TITLE
Maintainer(s) needed

### ISSUE THREAD

**Issue by vassilevsky** [rmagick/rmagick#316]
This project clearly needs new maintainers.

I came to help this project in August of 2014 after reading [this article](http://linduxed.com/blog/2014/07/25/the-state-of-rmagick-development/). I was working on a big Ruby on Rails-based application at the time, which was using RMagick as a dependency. I did what I could: merged some old PRs, asked issue authors to open new ones, documented the project a bit, autocorrected source code formatting with RuboCop a bit, released a few versions of the gem.

That was never enough. This project is serious, huge, has a lot of C (which I barely can understand), and needs a lot of quality work. I always felt that I wasn't doing enough, and my only excuse is that I never received any money or other form of compensation for this work.

Then our application stopped using RMagick (as far as I remember, it switched to MiniMagick, like many others). And last year I started maintaining many Erlang and Elixir-based projects at work. So now I have neither personal interest, nor any free time to be an active maintainer of this project.

If you have any of those, please comment below and we'll go from there.

**Comment by mockdeep** [comment]
Hey @vassilevsky, thanks for all of the work that you've put into RMagick!

I'm pretty rusty on C and was never particularly well versed to begin with, but unless more qualified candidates come along I'd be up for taking it on to the best of my ability. We rely on it pretty heavily internally. Despite its foibles, for the heavy image processing we handle RMagick was by far the most performant without having to move to another language.

If it ends up in my hands, I'd probably want to move it over to [our organization for orphaned projects](https://github.com/thread-pond). I might even be able to sucker more of our team into spending some time on it.

**Comment by vassilevsky** [comment]
Thanks, Robert. You already have write access to both repositories of this organization. I will add you to the gem owners list on RubyGems if you tell me your email there (you can email me at vassilevsky@gmail.com).

Moving this repository again would not be cool. We got help from Github support team to move it to the current nice **rmagick/rmagick** path. It was occupied by the old unmaintained repository to which we could not get access, so they renamed it to "rmagick-temp" and put this fork there instead. The fork was previously in https://github.com/gemhome — another organization for orphaned projects :) I think that the current position is the best.

This organization will happily accept your teammates :)

**Comment by mockdeep** [comment]
Alright, email sent.

> I think that the current position is the best.

Okay, we'll leave it where it is for now. I'll talk it over with my team and see who wants to be added here.

**Comment by vassilevsky** [comment]
The `develop` branch has a lot of breaking changes. I wanted to release it as version 3.0.

**Comment by mockdeep** [comment]
Thanks for the update @linduxed.

@vassilevsky I'm looking over the diff between v2.16.0 and the `develop` branch. As near as I can tell, the only breaking change is dropping support for ruby versions < 2.2. Does that sound about right? Aside from that, it's mostly Rubocop refactors and a handful of minor additions.

**Comment by bf4** [comment]
I'm not very active these days myself.  As @mockdeep makes clear, projects with maintainers who use them stand a better chance of being maintained

**Comment by bf4** [comment]
Also, *fwiw*, I got image magick to point here https://www.imagemagick.org/script/develop.php#ruby --> https://rmagick.github.io

**Comment by Watson1978** [comment]
Can I help you as a maintainer? :)

I'm working to prepare the pull request that it migrates RMagick from ImageMagick 6 to 7 in several months. 
https://github.com/Watson1978/rmagick/pull/1

Thank you.

**Comment by mockdeep** [comment]
@Watson1978 absolutely! You've done some great work so far and I'd love to have you on board. I've invited you as a member to the organization.

For what it's worth, here's my more immediate intentions:

1) get the build passing
2) deploy a 3.0 release

Until 3.0, I'd like to avoid adding any new features, though bug fixes like fixing memory leaks are good. I'll open an issue soon to track the 3.0 release.

**Comment by Watson1978** [comment]
Thank you to invite me to great team!
