### ISSUE TITLE
Fix Build

### ISSUE THREAD

**Issue by mockdeep** [rmagick/rmagick#326]
We've got several build failures, so we'll use this as a tracking issue to manage them for the 3.0 release.

These were produced on CircleCI using `IMAGEMAGICK_VERSION=6.7.7-10` and `image: circleci/ruby:2.4.1-stretch-node-browsers`:

- [] **`rspec ./spec/rmagick/image/channel_entropy_spec.rb:4 # returns a channel entropy`**
    `expect(res).to eq([0.5285857222715863])`
    => `expected: [0.5285857222715863], got: [0.5285857233828243]`

- [] **`test/Image2.rb#test_compress_colormap!`**
    `assert_equal(Magick::PseudoClass, @img.class_type)`
    => `<PseudoClass=2> expected but was <DirectClass=1>`

- [] **`test/Image2.rb#test_gray?`**
    `assert(gray.gray?)` => `<false> is not true.`

- [] **`test/ImageList2.rb#test_optimize_layers`**
    `assert_equal(2, res.length)` => `<2> expected but was <1>`

- [] **`test/Image_attributes.rb#test_background_color`**
    `assert_equal('#DFDFDFDFDFDF', @img.background_color)`
    => `<"#DFDFDFDFDFDF">(UTF-8) expected but was <"#DFDFDFDFDFDFFFFF">(ASCII-8BIT)`

- [] **`test/Image_attributes.rb#test_border_color`**
    `assert_equal('#DFDFDFDFDFDF', @img.border_color)`
    => `<"#DFDFDFDFDFDF">(UTF-8) expected but was <"#DFDFDFDFDFDFFFFF">(ASCII-8BIT)`

- [] **`test/Image_attributes.rb#test_image_type`**
    `assert_equal(Magick::GrayscaleMatteType, @img.image_type)`
    => `<GrayscaleMatteType=3> expected but was <TrueColorMatteType=7>`

- [] **`test/Magick.rb#test_limit_resources`**
    `assert_equal(3_221_225_472, new)` => `<3221225472> expected but was <1073741824>`

**Comment by Watson1978** [comment]
I think we can remove `IMAGEMAGICK_VERSION=6.6.9-10` lanes in travis.

The build error has been occurred in compiling ImageMagick 6.6.9 on travis.
Then, test cases continue to run using system default ImageMagick in travis.


```
In file included from magick/blob.c:69:0:
/usr/include/zlib.h:1385:21: note: expected ‘gzFile’ but argument is of type ‘struct FILE *’
 ZEXTERN int ZEXPORT gzputc OF((gzFile file, int c));
                     ^
magick/blob.c:4029:11: warning: passing argument 1 of ‘gzputc’ from incompatible pointer type [enabled by default]
           c=gzputc(image->blob->file,(int) *p++);
           ^
In file included from magick/blob.c:69:0:
/usr/include/zlib.h:1385:21: note: expected ‘gzFile’ but argument is of type ‘struct FILE *’
 ZEXTERN int ZEXPORT gzputc OF((gzFile file, int c));
                     ^
make[1]: *** [magick/magick_libMagickCore_la-blob.lo] Error 1
make[1]: Leaving directory `/home/travis/build/rmagick/rmagick/ImageMagick-6.6.9-10'
make: *** [install] Error 2
```

See https://travis-ci.org/rmagick/rmagick/jobs/486918213#L1802

**Comment by mockdeep** [comment]
@Watson1978 yeah, I'm fine with dropping `IMAGEMAGICK_VERSION=6.6.9-10`. Do you think we should also drop the `6.7` versions? Right now it looks like the default version on Heroku and Ubuntu is `6.8.9-9`, so maybe we could make that our min supported version.

**Comment by Watson1978** [comment]
> Do you think we should also drop the `6.7` versions? Right now it looks like the default version on Heroku and Ubuntu is `6.8.9-9`, so maybe we could make that our min supported version.

Sounds great!! 👍

**Comment by mockdeep** [comment]
Yeah, I'm seeing the same: https://travis-ci.org/rmagick/rmagick/jobs/487775221.

**Comment by mockdeep** [comment]
Closing this. We can track progress on the Ruby 2.5 build in #339 and ImageMagick 6.9 in #340.
