### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by mockdeep** [rmagick/rmagick#334]
## 3.0

- [x] get build passing on CircleCI for ImageMagick 6.8, Ruby 2.3, 2.4
- [x] get build passing on AppVeyor for ImageMagick 6.8, Ruby 2.3, 2.4
- [x] get build passing on TravisCI for ImageMagick 6.8, Ruby 2.3, 2.4

## 3.1

- [x] get build passing for ImageMagick 6.9
- [x] get build passing for Ruby 2.5
- [x] switch primary branch from `develop` to `master`
- [x] enable branch protection on `master`
- [ ] add support for MacOS build?

**Comment by mockdeep** [comment]
@Watson1978 now that we know which versions are passing, I put together a proposed plan for the next couple of releases. Please let me know what you think.

I'm really eager to get out a minimal 3.0 release because we've got almost 200 commits that haven't been released, starting from more than 7 years ago! It'll be good to get those out the door and in front of users. It shouldn't really change users' experience, since it's mostly code quality and memory management fixes.

I left off explicit support for ImageMagick 6.9 and Ruby 2.5, but if users are already using them, it should continue to work. After the 3.0 release we can work our way up to more recent versions of both. I think it makes sense to focus on one version of ImageMagick at a time, since it'll probably be easier to gradually add support incrementally. After 3.0, I'm imagining having a release at least once a month with whatever changes we have made during that month.

**Comment by mockdeep** [comment]
Hmm, looks like maybe 2.4 segfaults, too. Should we release 3.0 with just 2.3 passing?

https://travis-ci.org/rmagick/rmagick/jobs/487781188

**Comment by mockdeep** [comment]
Okay, I've got TravisCI passing for ImageMagick 6.8 and Ruby 2.3/2.4. I've added branch protection for TravisCI now, so all PRs will have to pass that build going forward.

**Comment by mockdeep** [comment]
@Watson1978 I've released RMagick version 3.0. Can you verify that it installs okay on Windows?

**Comment by Watson1978** [comment]
@mockdeep Thank you for your works!!! It works fine!

**Comment by Watson1978** [comment]
@mockdeep I think it is time to merge `develop` branch to `master`. How do you think?

(The some badges in https://github.com/rmagick/rmagick/blame/develop/README.textile#L3 expect that we works in `master` branch.)

**Comment by mockdeep** [comment]
@Watson1978 I've merged `develop` into `master`. I've also made `master` the default branch now, so you can make any new PRs directly to `master`.

**Comment by Watson1978** [comment]
Thanks!!!

**Comment by mockdeep** [comment]
3.0 and 3.1 have been released, so closing this.
