### ISSUE TITLE
Annotating fails when '@' is first character

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#38]
<a href="https://github.com/VxJasonxV"><img src="https://avatars.githubusercontent.com/u/1882?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [VxJasonxV](https://github.com/VxJasonxV)**
_Thursday Nov 08, 2012 at 10:44 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/59_

---

I had a script in use for years that would record data from Last.fm, and build an image out of various song information.

Some time ago, on the order of months, this script would keep showing the current song being played, but would simply stop working when showing historical playback data.

After poking around, it appears that this was due to a leading `@` character when using the annotate method. The rest of the data following the at-symbol does not appear to have any affect.

When invoked, Ruby would return this information:

```
bin/lastfmsig.rb:14:in `annotate': no text (ArgumentError)
        from bin/lastfmsig.rb:14:in `text'
        from bin/lastfmsig.rb:42
        from bin/lastfmsig.rb:37:in `each'
        from bin/lastfmsig.rb:37

shell returned 1
```

Changing the first three characters to be " @ " (space-at-space, really any character leading besides @) appears to have fixed this issue.

**Comment by Watson1978** [comment]
ImageMagick does special processing for `@` in annotating string. 
Especially with old ImageMagick (ie v6.7.x), the string starting with `@` will not work as expected.

The old ImageMagick has following code and looks for me it cause this issue.
```c
MagickExport char *InterpretImageProperties(const ImageInfo *image_info,
  Image *image,const char *embed_text)
{
...

  /* handle a '@' replace string from file */
  if (*p == '@') {
     p++;
     if (*p != '-' && (IsPathAccessible(p) == MagickFalse) ) {
       (void) ThrowMagickException(&image->exception,GetMagickModule(),
           OptionError,"UnableToAccessPath","%s",p);
       return((char *) NULL);
     }
     return(FileToString(p,~0,&image->exception));
  }
```

**Comment by Watson1978** [comment]
Seems there is no way to avoid this issue with before ImageMagick 6.9.0.
Please update ImageMagick to 6.9.0+.

**Comment by mockdeep** [comment]
@Watson1978 could escape `@` inside of RMagick for older versions of ImageMagick?

**Comment by Watson1978** [comment]
ImageMagick is processing characters following ＠ as a file.
If escape `@` in RMagick, then `＠` for the file will not work, I think....
