### ISSUE TITLE
The fall of a Rails application

### ISSUE THREAD

**Issue by afuno** [rmagick/rmagick#386]
Previous discussion in another library: https://github.com/moiristo/deep_cloneable/issues/103

Today updated to version 3.0.0. It did not help. Previously used version 2.16.0.

I will describe the situation briefly. There is a set of this kind:
```
blog -> posts -> pages -> blocks -> uploads
```

The uploads table contains .gif files (the problem is with .gif files).

Using the deep_cloneable library, I need to clone the entire blog. As a result, .gif files for this blog can accumulate about 10-15 pieces.

This causes the Rails application to crash:

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

**Comment by mockdeep** [comment]
Hi @afuno, looking at the original issue, I don't get the impression that this is a problem with RMagick. It's probably something to do with the way that you're handling the copying of images, or maybe something inside of CarrierWave. If you can share a repo I'd be happy to take a deeper look.

**Comment by bf4** [comment]
> > If you are the application owner check the logs for more information.
what's in the logs?

**Comment by mockdeep** [comment]
@afuno going to close this for now, as it doesn't seem to be an issue with RMagick. Please let us know if you think this is a mistake or you can give us more information to help us debug.
