### ISSUE TITLE
Diff Image not getting effected by fuzz

### ISSUE THREAD

**Issue by bv-deepak** [rmagick/rmagick#388]
img1       = Magick::Image.read("img1.png").first
img2       = Magick::Image.read("img1.png").first
img1.fuzz  = "25%"
img, float = img1.compare_channel(img2, Magick::AbsoluteErrorMetric)
img.save('result.png')

=========================================
The above ruby code works fine, and it gives me the desired float value, but the resulting image does not get effected by fuzz.

**Comment by Watson1978** [comment]
`compare_channel` method compare two image.
If you specify the fuzz are, the method just returns 0.0 for float value of `distortion` with same two images.

I think this is not RMagick issue. Please report to ImageMagick project.
