### ISSUE TITLE
RMagick 2.13.2 on Windows 7 x64

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#39]
<a href="https://github.com/bodrovis"><img src="https://avatars.githubusercontent.com/u/646942?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bodrovis](https://github.com/bodrovis)**
_Monday Feb 04, 2013 at 11:24 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/66_

---

Hello. I just noticed that RMagick was updated to 2.13.2 and that it should support ImageMagick 6.8. So i uninstalled my old ImageMagick, downloaded a new one (6.8.2-3-Q16-x64-dll) and installed in with C/C++ headers. Then i tried to install RMagick using instructions found in the Wiki (it helped me to install rmagick 2.13.1), but got the following error:

``` ruby
======================================================================
Mon 04Feb13 15:18:18
This installation of RMagick 2.13.2 is configured for
Ruby 1.9.3 (i386-mingw32) and ImageMagick 6.8.2
======================================================================



make
generating RMagick2-i386-mingw32.def
compiling rmagick.c
In file included from P:\ImageMagick/include/magick/magick-config.h:25:0,
                 from P:\ImageMagick/include/magick/MagickCore.h:29,
                 from rmagick.h:47,
                 from rmagick.c:13:
P:\ImageMagick/include/magick/magick-baseconfig.h:181:14: error: conflicting types for 'ssize_t'
p:\devkit\mingw\bin\../lib/gcc/mingw32/4.5.2/../../../../include/sys/types.h:118:18: note: previous declaration of 'ssize_t' was here
rmagick.c: In function 'Magick_colors':
rmagick.c:42:5: warning: passing argument 2 of 'GetColorInfoList' from incompatible pointer type
P:\ImageMagick/include/magick/color.h:75:5: note: expected 'size_t *' but argument is of type 'long unsigned int *'
rmagick.c: In function 'Magick_fonts':
rmagick.c:90:5: warning: passing argument 2 of 'GetTypeInfoList' from incompatible pointer type
P:\ImageMagick/include/magick/type.h:98:5: note: expected 'size_t *' but argument is of type 'long unsigned int *'
rmagick.c: In function 'Magick_init_formats':
rmagick.c:178:5: warning: passing argument 2 of 'GetMagickInfoList' from incompatible pointer type
P:\ImageMagick/include/magick/magick.h:125:5: note: expected 'size_t *' but argument is of type 'long unsigned int *'
make: *** [rmagick.o] Error 1
```

Exactly the same error i got when trying to use ImageMagick x86. My Ruby version is 1.9.3-p374. I recall, that when trying to use ImageMagick 6.8 with older rmagick 2.13.1 i got the same (or near the same) error about conflicting types.

Any clues about this issue?

**Comment by ABaumgaertner** [comment]
take a look at  #175

**Comment by ABaumgaertner** [comment]
take a look at #175

**Comment by mockdeep** [comment]
Closing this for now. Feel free to open a new issue if you are still seeing problems installing on Windows.
