### ISSUE TITLE
Requirements is wrong?

### ISSUE THREAD

**Issue by urimaro** [rmagick/rmagick#392]
### Environment

- Ruby 2.3.1
- ImageMagick 6.7.7

### Steps to reproduce

1. Add Gemfile `gem "rmagick"`
2. Execute `bundle install`

### Actual behavior

When I executed `bundle` command, the following message was shown.

```
> bundle install --path vendor/bundle --without development test
…
Installing rmagick 3.0.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/rails/redmine-4.0.1_tmp/vendor/bundle/ruby/2.5.0/gems/rmagick-3.0.0/ext/RMagick
/home/app/.rvm/rubies/ruby-2.5.1/bin/ruby -r ./siteconf20190220-7621-1s5j1bz.rb extconf.rb
checking for gcc... yes
checking for Magick-config... yes
checking for outdated ImageMagick version (<= 6.8.9)... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/app/.rvm/rubies/ruby-2.5.1/bin/$(RUBY_BASE_NAME)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/rails/redmine-4.0.1_tmp/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/rmagick-3.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/rails/redmine-4.0.1_tmp/vendor/bundle/ruby/2.5.0/gems/rmagick-3.0.0 for inspection.
Results logged to /var/rails/redmine-4.0.1_tmp/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/rmagick-3.0.0/gem_make.out

An error occurred while installing rmagick (3.0.0), and Bundler cannot continue.
Make sure that `gem install rmagick -v '3.0.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rmagick
```

In `mkmf.log` , the following message is written.

```
Detected ImageMagick version: 6.7.7
Can't install RMagick 3.0.0. You must have ImageMagick 6.8.9 or later.
```

Is requiremets in the README.textile wrong? 🤔

**Comment by Watson1978** [comment]
RMagick v3.0.0 does not support ImageMagick 6.7 or lower.

**Comment by schneems** [comment]
To anyone running on Heroku who hits this error, you'll need to upgrade your stack to not use cedar-14. You can see the installed versions of libraries at this link https://devcenter.heroku.com/articles/stack-packages. The heroku-16 or heroku-18 stack should work fine.

**Comment by urimaro** [comment]
@Watson1978 
Thanx.
I understood that RMagick v3.0.0 supports ImageMagick 6.8.9 or newer coz PR #393 was merged.

---

Is RMagick 2.x no longer maintained?:thinking:
If RMagick 2.x will be maintained,
Could you let me know..
- Which version of 2.x will be maintained
- Which version of ImageMagick the 2.x supports

**Comment by Watson1978** [comment]
> Is RMagick 2.x no longer maintained?
Did you mean you need old ImageMagick?

We have no plan to support them.
At least, ImageMagick 6.8.9 was released at nearly 4 years ago.
Please upate your system🙇

I think it might tough to support many old versions with small team....

**Comment by urimaro** [comment]
> Did you mean you need old ImageMagick versions?
> We have no plan to support them.

No, I don't need supports for old ImageMagick for now.
I just want to know..
- Which RMagick version will maintain
- Which ImageMagick version will you support  

About the first one,  I understood you plan to maintain only RMagick 3.x.

How about second one?
As you know, the ImageMagick project continues to maintain two version, 7.0.z and 6.9.z.
Do you plan to support both of them?

As I've said before, I don't need supports for old ImageMagick for now.
But I think some users want to know this information.
And if it is mentioned in the README, I think it'll be useful for them.

> Please update your system🙇

Copy that.
I'll try to update:+1:

Thanx.

**Comment by Watson1978** [comment]
RMagick v3 will be maintained for a while for ImageMagick v6.
For ImageMagick 7, we need to discussion. but not yet. 
(I think RMagick v4 will support ImageMagick 7, and we will maintain RMagick v3 and v4 both)

**Comment by mockdeep** [comment]
I don't think we'll want to drop support for ImageMagick 6.8 until 2020 or after depending on usage. Even if we release RMagick 4 this year, it will probably still support 6.8.
