### ISSUE TITLE
Infinity when no resolution or resolution 0.0 informed by the image file

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#45]
<a href="https://github.com/daniel2d2art"><img src="https://avatars.githubusercontent.com/u/1036505?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [daniel2d2art](https://github.com/daniel2d2art)**
_Sunday Mar 31, 2013 at 06:40 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/73_

---

https://github.com/rmagick/rmagick/blob/master/lib/RMagick.rb#L985
https://github.com/rmagick/rmagick/blob/master/lib/RMagick.rb#L986

Previous produces Infinity result if image file don't informs x_resolution or y_resolution. This produces  a float Inf out of range of integer when resize(width, height) is called.

**Comment by Watson1978** [comment]
Now there is a guard where it is divided by x_resolution.

https://github.com/rmagick/rmagick/blob/2f037983b33af59b5ceaec45587c76920f68bd48/ext/RMagick/rmimage.c#L11283-L11286

So, I think this issue should be solved.
