### ISSUE TITLE
don't conflate SetImageColorspace and TransformImageColorspace

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#46]
<a href="https://github.com/smparkes"><img src="https://avatars.githubusercontent.com/u/4292?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [smparkes](https://github.com/smparkes)**
_Sunday Apr 21, 2013 at 23:04 GMT_
_Originally opened as https://github.com/rmagick/rmagick/pull/75_

---

rmagick is conflating SetImageColorspace and TransformImageColorspace. This is the difference between "convert foo.png -set colorspace rgb ..." and "convert foo.png -colorspace rgb ..."

The former is like a reinterpret-cast in C++: it doesn't change the data, it just says the data is the given colorspace. The latter is a transform that changes the data based on the original image colorspace and the parameter.

I need SetImageColorspace and in the current code, it's not available if TransformImageColorspace is available.

This is a partial patch. I didn't wire in or test image.transform_colorspace(colorspace). If you're interested, I can ...

---

_**[smparkes](https://github.com/smparkes)** included the following code: https://github.com/rmagick/rmagick/pull/75/commits_

**Comment by linduxed** [comment]
Original PR here: https://github.com/rmagick-temp/rmagick/pull/75
