### ISSUE TITLE
`monitor` feature skips on stack errors

### ISSUE THREAD

**Issue by mockdeep** [rmagick/rmagick#464]
We ran into an issue when trying to integrate Ruby 2.5 where using `monitor` was causing `SEGV` errors. The temporary solution was to skip calling the monitor callback when the stack was too deep, but it would be good to dig deeper and figure out exactly why the stack was too deep, or whether there are other reasons `SEGV` was getting triggered.

https://github.com/rmagick/rmagick/pull/462

**Comment by Watson1978** [comment]
monitor feature will be removed by https://github.com/rmagick/rmagick/pull/1353
