### ISSUE TITLE
How get pixel color when background are transparent

### ISSUE THREAD

**Issue by letarg0** [rmagick/rmagick#466]
I have image greate with rmagick. Transparent color and black shape.
Whet I read pixel I alvays get black. Any functions return only black color
.intensity too.

How create transparent image with for example black chars
and get pixel colors

**Comment by Watson1978** [comment]
@letarg0 Could you please attach sample code to reproduce your problem ?

**Comment by mockdeep** [comment]
Closing for now. If you are still having the issue, please provide some more context and we can reopen it.
