### ISSUE TITLE
Image#remap produces unreasonable result

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#5]
<a href="https://github.com/jxtps"><img src="https://avatars.githubusercontent.com/u/90846?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jxtps](https://github.com/jxtps)**
_Wednesday Jun 09, 2010 at 02:49 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/8_

---

`Image#remap` produces an unreasonable result for the attached images. The pixel at 0,0 is remapped from (254, 254, 254) -> (255, 227, 0) despite there being a (255, 255, 255) in the `remap_image` ("colors" below), which is much closer in RGB space than the color picked. 

See: http://www.imagemagick.org/RMagick/doc/image3.html#remap 

RMagick command sequence: 

```
j@ubuntu:~/work/test$ irb

irb(main):001:0> require 'RMagick'
puts Magick::Long_version
=> true

irb(main):002:0> puts Magick::Long_version
This is RMagick 2.13.1 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 6.6.2-3 2010-06-08 Q8 http://www.imagemagick.org
Built for ruby 1.9.1
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org
=> nil

irb(main):003:0> img = Magick::Image.read('input.png').first
=> input.png PNG 36x41 36x41+0+0 DirectClass 8-bit 1kb

irb(main):004:0> img.pixel_color(0,0)
=> red=254, green=254, blue=254, opacity=0

irb(main):005:0> colors = Magick::Image.read('colors.png').first
=> colors.png PNG 454x1 454x1+0+0 DirectClass 8-bit 1kb

irb(main):006:0> colors.pixel_color(413,0)
=> red=255, green=255, blue=255, opacity=0

irb(main):007:0> img.remap(colors, Magick::NoDitherMethod)
=> input.png PNG 36x41 36x41+0+0 PseudoClass 454c 8-bit 1kb

irb(main):008:0> img.pixel_color(0,0)
=> red=255, green=227, blue=0, opacity=0

irb(main):009:0> img.write('output.png')
=> input.png=>output.png PNG 36x41 36x41+0+0 PseudoClass 454c 8-bit 1kb
```

(Can't attach images to github issues, included them in the report emailed to the rmagick rubyforge email address)

**Comment by mockdeep** [comment]
Sounds like this was a bug in ImageMagick, so closing. Please update if it's closed in error.
