### ISSUE TITLE
Missing line when scaling 0.5 and setting stroke-antialias 0

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#50]
<a href="https://github.com/donv"><img src="https://avatars.githubusercontent.com/u/57275?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [donv](https://github.com/donv)**
_Thursday Aug 01, 2013 at 10:24 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/82_

---

Hi!

Using rmagick (2.13.2) with ImageMagick 6.8.6 on OS X 10.8.4.  Given the following example:

``` Ruby

script = <<EOF
scale 0.5,0.5
stroke-antialias 0
line 63.2031,377.2 780,377.2
line 63.2031,335 780,335
line 63.2031,292.8 780,292.8
EOF
require 'rmagick'
d = Magick::Draw.new
script.each_line { |line| d.primitive line }
base_image = Magick::Image.new(400, 300)
d.draw(base_image)
base_image.write('three_lines.png')
```

I get the following image:

![three_lines](https://f.cloud.github.com/assets/57275/893045/30d20868-fa94-11e2-8308-090c5c49b5da.png)

I expect three lines to be drawn, but there are only two. Any idea why?

Any help is appreciated.

**Comment by Watson1978** [comment]
Seem that this issue is related to `stroke-antialias`.
If I use `stroke-antialias 1`, the sample code generates following image.

![three_lines](https://user-images.githubusercontent.com/199156/77435174-51984380-6e25-11ea-947d-07c64891b963.png)

**Comment by Watson1978** [comment]
ImageMagick command generates same image with sample code.
```sh
imagemagick6.9/bin/convert -size 400x300  xc:white -fill white -stroke black \
-draw 'scale 0.5,0.5
       stroke-antialias 0
       line 63.2031,377.2 780,377.2
       line 63.2031,335 780,335
       line 63.2031,292.8 780,292.8' test.png
```

![test](https://user-images.githubusercontent.com/199156/77436236-95d81380-6e26-11ea-80e0-2d440c46d857.png)

I think this is a problem or limitation of ImageMagick.

**Comment by Watson1978** [comment]
@dlemstra What do you think about this issue?

**Comment by dlemstra** [comment]
This should be resolved by this commit: https://github.com/ImageMagick/ImageMagick/commit/7972d4427db89ca401ca46326ba6c5e0766ecbf8

**Comment by Watson1978** [comment]
I confirmed the patch was committed into IM6 https://github.com/ImageMagick/ImageMagick6/commit/19e8b60756dfb86447849feb096b9f492a7063ea

Thanks
