### ISSUE TITLE
ImageList_fx should be moved to Image_fx.

### ISSUE THREAD

**Issue by dlemstra** [rmagick/rmagick#508]
The method ImageList_fx suggests that this works on an image list but this method only works on the first image of the list. I think we should remove the `ImageList_fx` method from the `ImageList` class and add the method to the `Image` class instead.

**Comment by Watson1978** [comment]
1. You add implementation of Image_fx. And add deprecate message into ImageList_fx
2. Later, remove its method

**Comment by dlemstra** [comment]
Okay will do this later today.
