### ISSUE TITLE
using Image.compare_channel raised RuntimeError "ImageMagick library function failed to return a result."

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#52]
<a href="https://github.com/rajsahae"><img src="https://avatars.githubusercontent.com/u/394822?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rajsahae](https://github.com/rajsahae)**
_Friday Aug 09, 2013 at 01:26 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/84_

---

I have the following ruby script:

``` ruby
#!/usr/bin/env ruby
# encoding: UTF-8

require 'RMagick'
include Magick

image1 = Image.ping(ARGV[0])[0]
image2 = Image.ping(ARGV[1])[0]

diff, float = image1.compare_channel(image2, RootMeanSquaredErrorMetric)
diff.write(ARGV[2])
```

Which I then call from the command line and it produces an error

``` bash
$: ./test-compare_channel.rb image1.jpg image2.jpg image3.jpg
./test-compare_channel.rb:10:in `compare_channel': ImageMagick library function failed to return a result. (RuntimeError)
    from ./test-compare_channel.rb:10:in `<main>'
```

**Comment by Watson1978** [comment]
You should use `Image.ping` to refer the properties of an image.
If you want to transform the image or something with actual pixels, you have to use `Image.read` instead.
