### ISSUE TITLE
Can anyone provide binary gem for Windows?

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#53]
<a href="https://github.com/hongliang-goudou"><img src="https://avatars.githubusercontent.com/u/4746298?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hongliang-goudou](https://github.com/hongliang-goudou)**
_Thursday Aug 15, 2013 at 09:23 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/85_

---

I do see some old binary gems for ruby 1.8.x on the old rubyforge.org website. But since then there's no binary gems for ruby 1.9.3 and 2.0.0. Can anyone provide some binary gems? And it would be much better if the binary gem is bound with a working ImageMagick. This would make the installation much easier.

I know most of the developers are on Mac or Linux. But some of the projects needs to be run on Windows at our customers' office. So please don't ignore us. :-)

**Comment by mockdeep** [comment]
@Watson1978 @dlemstra I'm trying to understand this issue. Are they looking for pre-compiled binaries on Windows? Is that a thing we can do? Is it a thing we should do?

**Comment by dlemstra** [comment]
I suspect they are looking for a static build of RMagick where everything is included in the binaries which means that you don't need to install ImageMagick on the machine that you are using it on.

**Comment by Watson1978** [comment]
I don't like fat gem a bit. I think maintenance is tough

**Comment by mockdeep** [comment]
Okay, I guess we can close this then. If people are having trouble installing on Windows, please open a new issue with as much information as you can provide.
