### ISSUE TITLE
Archive old RMagick repo

### ISSUE THREAD

**Issue by mockdeep** [rmagick/rmagick#533]
The old RMagick repo is still hanging around as `rmagick-temp`. If we can find somebody with access to it, we should probably archive it.

https://github.com/rmagick-temp/rmagick

**Comment by mockdeep** [comment]
@bf4 do you know who has access to the `rmagick-temp` organization?

**Comment by dlemstra** [comment]
@mockdeep `rmagick-temp` is a user not an organization.

**Comment by mockdeep** [comment]
Do we know who is in control of that user? Are they the old maintainers who were unresponsive?

**Comment by dlemstra** [comment]
Maybe we could detach this fork? https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork.

**Comment by mockdeep** [comment]
Thanks for the suggestion @dlemstra. I've contacted support to see if they'll detach the fork for us, as well as asking them to archive it if possible.

**Comment by linduxed** [comment]
I think that `rmagick-temp` was added by Github when @bf4 contacted them (IIRC) to have this repo become the main RMagick repo. The `rmagick` repo under the `rmagick-temp` organization is still controlled by @mmaiza, who is likely still inactive.

**Comment by dlemstra** [comment]
@mockdeep Did you not get an answer from support yet?

**Comment by mockdeep** [comment]
@dlemstra I did. They unlinked the repo, so you'll see it no longer shows the "forked" link. However they said they couldn't archive it for us.

**Comment by Watson1978** [comment]
Congratulations 🎉
