### ISSUE TITLE
 Draw.scale doesn't seem to do anything

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#54]
<a href="https://github.com/Thermatix"><img src="https://avatars.githubusercontent.com/u/5038613?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Thermatix](https://github.com/Thermatix)**
_Wednesday Sep 11, 2013 at 15:53 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/87_

---

this is what i'm doing
shape_drawer.scale(@sx.to_f / self.marker_height, @sy.to_f / self.marker_width) 

I don't want to scale the image as that just blurs it horribly.
so scaling the vector path is the only option, but the output never changes.
what am i doing wrong?

**Comment by Watson1978** [comment]
I think you need to call `Draw#scale` just before the one you want to change.

```
require 'rmagick'

img = Magick::Image.new(300, 220, Magick::HatchFill.new('white', 'lightcyan2'))
gc = Magick::Draw.new

gc.stroke('red')
gc.pointsize(50)

# This will change the 'Hello' scale
#gc.scale(2, 2)

gc.text(0, 50, 'Hello')

gc.draw(img)

img.write('scale.png')
```

* Without `gc.scale(2, 2)`
<img src="https://user-images.githubusercontent.com/199156/77433813-3d534700-6e23-11ea-9ee4-6f6b296be044.png">

 * With `gc.scale(2, 2)`
<img src="https://user-images.githubusercontent.com/199156/77433851-4a703600-6e23-11ea-993e-c456733cba38.png">

* With `gc.scale(4, 2)`
<img src="https://user-images.githubusercontent.com/199156/77433869-53610780-6e23-11ea-8e8b-b7e7a8550bbf.png">
