### ISSUE TITLE
Better coverage for C part

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#542]
I think we need better coverage tests for C-lang source codes to detect breaking change easily.

### How to get result of coverage
```
# Run tests with gcov flags.
$ rake clobber
$ LDFLAGS="-fprofile-arcs" CFLAGS="-coverage -fprofile-arcs -ftest-coverage -g -O0" rake


$ cd ./tmp/x86_64-linux/RMagick2/2.5.3/
$ gcov rmimage.gcda
File '../../../../ext/RMagick/rmimage.c'
Lines executed:84.49% of 4738
Creating 'rmimage.c.gcov'
Cannot open source file ../../../../ext/RMagick/rmimage.c

File '/home/watson/.rvm/rubies/ruby-2.5.3/include/ruby-2.5.0/ruby/ruby.h'
Lines executed:84.91% of 53
Creating 'ruby.h.gcov'


# After `gcov` command, you can look the detail with favorite editor.
$ vi rmimage.c.gcov


# Use LCOV to generate HTML report file
$ cd ./tmp/x86_64-linux/RMagick2/2.5.3/
$ lcov -c -d . -o RMagick.info
$ genhtml RMagick.info -o coverage
```

### Coverage rate (2019/04/05)

<img width="580" src="https://user-images.githubusercontent.com/199156/55666492-a21c3700-588a-11e9-9c9b-2c2a53410d8b.png">

### Coverage rate (2019/04/15)
<img width="580" src="https://user-images.githubusercontent.com/199156/56096884-92ef5600-5f28-11e9-8cd0-ec3d38fa781b.png">

### Coverage rate (2019/04/26)
<img width="580" src="https://user-images.githubusercontent.com/199156/56792167-f12f0980-6843-11e9-9425-10f7b1e3e4cd.png">

**Comment by mockdeep** [comment]
Yes! I didn't realize we could run C coverage with Ruby tests.

**Comment by mockdeep** [comment]
We might want to see if we can track this with a 3rd party service like CodeClimate or Coveralls.
