### ISSUE TITLE
Can't configuration with IM6.7 via PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#557]
I just install RMagick with IM 6.7 on macOS.

1. My machine already installed IM 6.9 via `brew`
```
$ brew install imagemagick@6
```

2. Configure with that specify IM6.7 directory via PKG_CONFIG_PATH. However, it refer IM6.9 installed with `brew`
```
$ PKG_CONFIG_PATH="$HOME/imagemagick6.7/lib/pkgconfig" ruby extconf.rb
checking for brew... yes
checking for clang... yes
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.7.7)... no
Usage: file [bcCdEhikLlNnprsvzZ0] [-e test] [-f namefile] [-F separator] [-m magicfiles] [-M magicfiles] file...
       file -C -m magicfiles
Try `file --help' for more information.
checking for Ruby version >= 2.3.0... yes
checking for sys/types.h... yes
checking for magick/MagickCore.h... yes
checking for snprintf() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for GetImageChannelEntropy() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
checking for SetImageGray() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,sys/types.h,magick/MagickCore.h... yes
creating extconf.h
creating Makefile


======================================================================
Wed 10 Apr 19 01:31:18
This installation of RMagick 3.0.0 is configured for
Ruby 2.3.8 (x86_64-darwin18) and ImageMagick 6.9.10
======================================================================


Configured compile options: {:magick_version=>"6.9.10", :local_libs=>" -L/usr/local/Cellar/imagemagick@6/6.9.10-27/lib -lMagickCore-6.Q16", :cflags=>" -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.10-27/include/ImageMagick-6", :cppflags=>" -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.10-27/include/ImageMagick-6", :ldflags=>" -L/usr/local/Cellar/imagemagick@6/6.9.10-27/lib -lMagickCore-6.Q16", :defs=>[], :config_h=>"Makefile rmagick.h"}
```

----

Seems IM6.7 does not have `ImageMagick-6xxx` as package name.

```
$ PKG_CONFIG_PATH="$HOME/imagemagick6.7/lib/pkgconfig" pkg-config --list-all | grep ImageMagick
ImageMagick                         ImageMagick - ImageMagick - Convert, Edit, and Compose Images
Wand                                Wand - MagickWand - C API for ImageMagick
MagickCore                          MagickCore - MagickCore - C API for ImageMagick
MagickWand                          MagickWand - MagickWand - C API for ImageMagick
ImageMagick++                       ImageMagick++ - Magick++ - C++ API for ImageMagick
Magick++                            Magick++ - Magick++ - C++ API for ImageMagick
```

Therefore the following points do not work as expected, I think.

https://github.com/rmagick/rmagick/blob/96c30d058eb9155e64fba598d9f239e516058958/ext/RMagick/extconf.rb#L165

**Comment by Watson1978** [comment]
@dlemstra Do you have any idea for this issue ?

**Comment by Watson1978** [comment]
i wonder whether we need this line.... 🤔 
https://github.com/rmagick/rmagick/blob/96c30d058eb9155e64fba598d9f239e516058958/ext/RMagick/extconf.rb#L165

If remove it, it works as I expected.

**Comment by dlemstra** [comment]
This is how pkg-config works? As far as I know you are extending the `PKG_CONFIG_PATH` when you set the variable and not setting that as the only search folder. And then it finds both ImageMagick `6.9.10` and `6.7.7` and because of the search order it prefers the latest version and that is a good thing.

**Comment by Watson1978** [comment]
1．I specify `PKG_CONFIG_PATH`="$HOME/imagemagick6.7/lib/pkgconfig"
2．RMagick add `PKG_CONFIG_PATH` in
https://github.com/rmagick/rmagick/blob/96c30d058eb9155e64fba598d9f239e516058958/ext/RMagick/extconf.rb#L31

`PKG_CONFIG_PATH` will have "$HOME/imagemagick6.7/lib/pkgconfig:/usr/local/opt/imagemagick@6/lib/pkgconfig"

3．RMagick will search `ImageMagick-6xxx` package. it will appear in ImageMagick 6.9 and use it.
https://github.com/rmagick/rmagick/blob/96c30d058eb9155e64fba598d9f239e516058958/ext/RMagick/extconf.rb#L165

4．`pkg-config --cflags ImageMagick-6.Q16` show CFLAGS for ImageMagick 6.9

```
PKG_CONFIG_PATH="$HOME/imagemagick6.7/lib/pkgconfig:/usr/local/opt/imagemagick@6/lib/pkgconfig" pkg-config --cflags ImageMagick-6.Q16
-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick@6/6.9.10-27/include/ImageMagick-6
```

**Comment by Watson1978** [comment]
If use `ImageMagick` as package name, `pkg-config` will show the expected CFLAGS by search order.

```
$ PKG_CONFIG_PATH="$HOME/imagemagick6.7/lib/pkgconfig:/usr/local/opt/imagemagick@6/lib/pkgconfig" pkg-config --cflags ImageMagick
-I/Users/s-fujita/imagemagick6.7/include/ImageMagick
```

**Comment by dlemstra** [comment]
I changed this to be able to distinguish between ImageMagick 6 and 7 in the future and always prefer the latest version. 

I was not aware that `PKG_CONFIG_PATH` could affect the search order. I first found this post: https://askubuntu.com/a/326829 that says it only adds extra directories. But later I read in the manual that `PKG_CONFIG_PATH` would be the first directory that it would search in.

Removing `packages = `pkg-config --list-all`.scan(/(ImageMagick\-[\.A-Z0-9]+) .*/).flatten` should indeed resolve your issue.

**Comment by Watson1978** [comment]
I guess almost users does not encounter this issue.
I will solve with removing ImageMagick 6.9 installed by `brew`.

**Comment by mockdeep** [comment]
@Watson1978 should we close this issue?

**Comment by Watson1978** [comment]
Sorry, I will close this.
