### ISSUE TITLE
Magick::Image.capture always raise exception

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#560]
### Environment
* macOS 10.14

### Test code
```ruby
require 'rmagick'

Magick::Image.capture(true)
```

### Result
```
$ ruby rmagick.rb
rmagick.rb:3:in `capture': ImageMagick library function failed to return a result. (RuntimeError)
	from rmagick.rb:3:in `<main>'
```

**Comment by Watson1978** [comment]
Seems this feature depends on XWindow system.
We need to show clearly message for the environment without XWindow system.

**Comment by dlemstra** [comment]
I get the following error message: `Error: test_geometry(Image_Attributes_UT): Magick::ImageMagickError: unable to open X server '': No such file or directory @ error/xwindow.c/XImportImage/4899`

**Comment by mockdeep** [comment]
Would it be possible to get this working using [`xvfb` on CI](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui)? It does seem like it should throw a helpful error, though, when an XWindow system is not available. Also, how would this behave on Windows?

**Comment by dlemstra** [comment]
On Windows `XImportImage` will return `NULL` so this will cause an exception here: `rm_ensure_result(new_image)`.

**Comment by mockdeep** [comment]
When I try `Image#capture` in a Rails console on my local machine it just hangs. At any rate, it does seem like we should detect whether there is an XWindow system and raise a friendly error. @dlemstra it also sounds like this isn't supported on Windows in ImageMagick core. Is that right?

**Comment by dlemstra** [comment]
XWindows is not supported on Windows with the default build. I think it could be possible with a custom build but I don't think anyone will do that.

**Comment by Watson1978** [comment]
There's a simple description in the documentation.
https://rmagick.github.io/image1.html#capture

So, I will close this.
