### ISSUE TITLE
Draw#get_type_metrics incorrectly raises an exception on '%%'

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#57]
<a href="https://github.com/latortuga"><img src="https://avatars.githubusercontent.com/u/9379?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [latortuga](https://github.com/latortuga)**
_Friday Nov 01, 2013 at 18:38 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/92_

---

https://github.com/rmagick/rmagick/blob/962d56cba3a132d590be1dd062f2a3a2efa48545/ext/RMagick/rmdraw.c#L1917

This line causes '%%' to be included in the list of "image attributes" special escape sequences but '%%' is the escape sequence for a percentage sign, not for any image attributes (per the RMagick documentation, directly above the table [here](http://studio.imagemagick.org/RMagick/doc/draw.html#spec_chars_table)), and thus should not raise an exception.

**Comment by mkluczny** [comment]
I have the same problem. I would like to measure any kind of text, also those including %a, %b, etc. and escape variable placeholders before doing actual measurement. I followed documentation on this page: http://www.imagemagick.org/RMagick/doc/draw.html#spec_chars_table and escaped % by prepending it with another %. That should do the trick but it didn't work.

BTW. the documentation differs from the code. There are more special characters in the code than in the documentation: https://github.com/rmagick/rmagick/blob/master/ext/RMagick/rmdraw.c
static char attrs[] = "OPbcdefghiklmnopqrstuwxyz[@#%";

**Comment by mkluczny** [comment]
#179

**Comment by mkluczny** [comment]
I prepared pull request fixing this issue
#179
