### ISSUE TITLE
Support for webp?

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#60]
<a href="https://github.com/jphastings"><img src="https://avatars.githubusercontent.com/u/42999?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jphastings](https://github.com/jphastings)**
_Thursday Jan 23, 2014 at 10:53 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/97_

---

RMagick doesn't seem to support webp (despite `convert` on my system working, and calling out to `cwebp`). Is this implemented or planned?

**Comment by mockdeep** [comment]
This should work if you're using ImageMagick 6.8 or above.
