### ISSUE TITLE
Stack level too deep with ruby 2.1.0

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#62]
<a href="https://github.com/mlyubarskyy"><img src="https://avatars.githubusercontent.com/u/1397301?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mlyubarskyy](https://github.com/mlyubarskyy)**
_Monday Mar 03, 2014 at 16:45 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/100_

---

[15] pry(#Magick::ImageList)> show-method respond_to?
From: /Users/UGE/.rvm/gems/ruby-2.1.0/gems/rmagick-2.13.2/lib/RMagick.rb @ line 1799:
Owner: Magick::ImageList
Visibility: public
Number of lines: 9

```
def respond_to?(methID, priv=false)
  binding.pry
    return true if __respond_to__?(methID, priv)
    if @scene
        @images[@scene].respond_to?(methID, priv)
    else
        super
    end
end
```

[16] pry(#Magick::ImageList)> show-method __ respond_to __?

From: /Users/UGE/.rvm/gems/ruby-2.1.0/gems/rmagick-2.13.2/lib/rmagick.rb @ line 1799:
Owner: Magick::ImageList
Visibility: public
Number of lines: 9

```
def respond_to?(methID, priv=false)
  binding.pry
    return true if __respond_to__?(methID, priv)
    if @scene
        @images[@scene].respond_to?(methID, priv)
    else
        super
    end
end
```

this causes stack level too deep

**Comment by Watson1978** [comment]
Is this problem still occurring?

**Comment by mockdeep** [comment]
@mlyubarskyy are you still seeing this issue?

**Comment by mockdeep** [comment]
Closing for now. If you can provide more information, please let us know and we can re-open.
