### ISSUE TITLE
RVG Resolution DPI doesn't affect pixelation?

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#64]
<a href="https://github.com/hspinks"><img src="https://avatars.githubusercontent.com/u/1484366?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hspinks](https://github.com/hspinks)**
_Friday May 30, 2014 at 03:55 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/104_

----

I used RMagick::Draw to build PNGs of line graphs, and they looked great except for the resolution of the lines and text. Looking through the RMagick documentation, I thought [RVG](http://www.imagemagick.org/RMagick/doc/rvgtut.html) would come to the rescue.

Unfortunately, after setting `RVG::dpi = 300` and following the tutorial to draw my graph, I still end up with lines and text that appear pixelated. What am I missing?

I've followed the tutorial almost exactly, and you can see some of the code snippet [here](https://gist.github.com/hspinks/743160adaee72c09901e). Is there a way to improve the pixelation of the lines?

**Comment by linduxed** [comment]
No response for more than a year. Closing.
