### ISSUE TITLE
Image.read fails

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#66]
<a href="https://github.com/bobbdelsol"><img src="https://avatars.githubusercontent.com/u/4465308?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bobbdelsol](https://github.com/bobbdelsol)**
_Wednesday Jun 18, 2014 at 00:23 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/107_

----

Image.read(filename) fails.  It seems to be expecting the width height to be in the parameters, but recognizes that there should only be one parameter.

ALSO-  Your homepage link in rubygems is broken, i guess you've moved it since you last published a gem.  Are you saving gems somewhere else now?

**Comment by linduxed** [comment]
No sample code or resulting error messages. Closing.
