### ISSUE TITLE
convert image 

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#67]
<a href="https://github.com/Meenal-goyal"><img src="https://avatars.githubusercontent.com/u/5022351?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Meenal-goyal](https://github.com/Meenal-goyal)**
_Monday Jul 14, 2014 at 07:53 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/109_

---

I am running this command on the image:

```
 convert -verbose -density 150 -trim input.jpg -quality 100 -sharpen 0x1.0 output.jpg
```

But I wanted to execute same thing using ruby script, so i tried this:

im = Magick::Image.read(pdf_file_name)
im.each do | img |
  im[0].density = "150"
  im[0].trim!
  im[0] = im[0].sharpen(0,1.0)
  im[0].write("final.jpg") {self.quality = 100}
end

The problem is both are giving different outputs. Could you please tell where am i going wrong?

**Comment by Watson1978** [comment]
I tried with ImageMagick 6.9 and RMagick 3.1.
It appears to me that RMagick is generating the same image as ImageMagick.

### Input image
![Flower_Hat](https://user-images.githubusercontent.com/199156/59269716-ad288480-8c8a-11e9-83a4-5df542de3d9a.jpg)

### Output

Generated by ImageMagick | Generated by RMagick
-- | --
<img src="https://user-images.githubusercontent.com/199156/59269746-bdd8fa80-8c8a-11e9-99be-6ddb069e9c32.jpg"> | <img src="https://user-images.githubusercontent.com/199156/59269816-dcd78c80-8c8a-11e9-8b98-37cb7fe92f73.jpg">

* ImageMagick command

```
convert -verbose -density 150 -trim Flower_Hat.jpg -quality 100 -sharpen 0x1.0 ~/output.jpg
```

* RMagick code
  * same code in description

**Comment by Watson1978** [comment]
I will close this issue.
Feel free to reopen if you still have this issue.
