### ISSUE TITLE
Homepage URL is broke.

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#68]
<a href="https://github.com/rickcarlino"><img src="https://avatars.githubusercontent.com/u/1388608?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rickcarlino](https://github.com/rickcarlino)**
_Wednesday Jul 23, 2014 at 15:46 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/110_

----

It looks like this project was hosted on the now offline rubygems.org site.

Is there a new homepage URL now that Rubyforge shutdown?

**Comment by vassilevsky** [comment]
The site is now at http://rmagick.github.io

**Comment by bf4** [comment]
I can't see the diff on my phone
Was it not redirecting?

**Comment by vassilevsky** [comment]
Ugh. I'm afraid I don't understand the question :)
