### ISSUE TITLE
Variable can not be referenced in block of new_image

### ISSUE THREAD

**Issue by akicho8** [rmagick/rmagick#699]
### Overview

Even with block arguments can not access `params` because the scope is different

```ruby
list = Magick::ImageList.new
list.new_image(128, 64) { |e| e.background_color = params[:background_color] }
```
> #<NameError: undefined local variable or method `params' for #<Magick::Image::Info:0x00007fe814894e10>>`

### Steps to reproduce

```ruby
require "rmagick"
require "rmagick/version"

Magick::VERSION                 # => "3.1.0"

class App
  def params
    { background_color: "blue" }
  end

  # OK
  def case1
    list = Magick::ImageList.new
    list.new_image(128, 64) { self.background_color = "blue" }
  end

  # Can not access params because the scope is different
  def case2
    list = Magick::ImageList.new
    list.new_image(128, 64) { self.background_color = params[:background_color] }
  rescue => error
    error # => #<NameError: undefined local variable or method `params' for #<Magick::Image::Info:0x00007fe814886770>>
  end

  # Even with block arguments can not access params because the scope is different
  def case3
    list = Magick::ImageList.new
    list.new_image(128, 64) { |e| e.background_color = params[:background_color] }
  rescue => error
    error # => #<NameError: undefined local variable or method `params' for #<Magick::Image::Info:0x00007fe814894e10>>
  end

  # Last resort
  def case4
    list = Magick::ImageList.new
    params = self.params        # assign local variables
    list.new_image(128, 64) { self.background_color = params[:background_color] }
  rescue => error
    error # => 
  end
end

App.new.case1
App.new.case2
App.new.case3
App.new.case4
```

### How to call user friendly block

```ruby
class C
  def f(&block)
    if block.arity == 1
      block.call(self)
    else
      instance_eval(&block)
    end
  end
end

C.new.f { self }              # => #<C:0x00007fe814915a88>
C.new.f { |e| [e, self] }     # => [#<C:0x00007fe8149155b0>, main]
```

**Comment by Watson1978** [comment]
Agree

Image#new invokes a block using instace_eval.
It restricts the scope and makes tough to receive external values...

**Comment by mockdeep** [comment]
I've been thinking we should deprecate the `instance_eval` format, as it's also confusing. It looks like we pass the image through to the block, so we don't need to bind the block.

**Comment by mockdeep** [comment]
Actually, @akicho8 I don't think this is an issue. It looks like `params` is actually not defined. When I define it outside the scope it works fine:

```rb
params = { background_color: 'blue' }
list = Magick::ImageList.new
list.new_image(128, 64) { |e| e.background_color = params[:background_color] }
# => [  128x64 DirectClass 16-bit]
# scene=0
```

Can you double check that `params` is defined in your code?

**Comment by akicho8** [comment]
@Watson1978 @mockdeep Thank you for watching the issue.

The following code is similar to **case4** in the first example posted and works correctly. Because params is a local variable.

```ruby
require "rmagick"
class App
  def run
    params = {background_color: "blue"}
    list = Magick::ImageList.new
    list.new_image(128, 64) { self.background_color = params[:background_color] }
  end
end
App.new.run                     # => [  128x64 DirectClass 16-bit]
```

The following is an example of improving the original code and changing it to receive params from the outside. This does not work properly. Because params is out of scope.

```ruby
require "rmagick"

class App
  attr_accessor :params
  
  def initialize(params)
    @params = params
  end
  
  def run
    list = Magick::ImageList.new
    params                      # => {:background_color=>"blue"}
    list.new_image(128, 64) { self.background_color = params[:background_color] }
  end
end

App.new(background_color: "blue").run rescue $! # => #<NameError: undefined local variable or method `params' for #<Magick::Image::Info:0x00007f9a8b0906f0>>
```

I agree with the policy of ​​not using instance_eval.

But if change it quickly, may get confused.

In order to improve while maintaining the compatibility so far, I think it is better to change the part calling `instance_eval` as follows.

```ruby
if block.arity == 1
  block.call(self)
else
  instance_eval(&block)
end
```

**Comment by mockdeep** [comment]
@akicho8, ah, I see. Yeah, if it's a method call and not a local that makes sense. Right now we're focused on performance and the ImageMagick 7 release, so I don't know if we'll be able to change this soon. For now at least you have a couple of workarounds by using local variables. If you want to try to change this yourself, we'd be happy to look at a PR.
