### ISSUE TITLE
Can't get black value of a pixel in a CMYK Image

### ISSUE THREAD

**Issue by onlinetocode** [rmagick/rmagick#747]
ImageMagick 6.9.10-49
I tried ruby 2.5.1 and ruby 2.6.1
I tried RMagick 3.2.0, 3.1.0 and 2.16.0

I try to read the black value of some pixels in a CMYK image without luck.

I always get back `0`

I checked ImageMagick with this command:

```bash
$ convert black.jpg -format '%[pixel:p{1,1}]' info:-
cmyk(0,0,0,255)%
```

When I try to get the same value with RMagick with this script

```ruby
require 'rmagick'

black = Magick::Image.read('black.jpg')[0]
black_pixels = []
black.each_pixel do |pixel|
    black_pixels << pixel
end
puts "black.jpg Pixel 1/1: cmyk(#{black_pixels.first.cyan},#{black_pixels.first.magenta},#{black_pixels.first.yellow},#{black_pixels.first.black}),"

cyan = Magick::Image.read('cyan.jpg')[0]
cyan_pixels = []
cyan.each_pixel do |pixel|
    cyan_pixels << pixel
end
puts "cyan.jpg Pixel 1/1: cmyk(#{cyan_pixels.first.cyan},#{cyan_pixels.first.magenta},#{cyan_pixels.first.yellow},#{cyan_pixels.first.black})"
```

I get these results:

```bash
ruby read_color.rb
black.jpg Pixel 1/1: cmyk(0,0,0,0),
cyan.jpg Pixel 1/1: cmyk(65278,0,0,0)
```
Other color values are working, but not the black value.

I suspect that the error has something to do with the fact that black is associated with 'opacity' in ext/RMagick/rmpixel.c 

```c
DEF_PIXEL_CMYK_CHANNEL_ACCESSOR(cyan, red)
DEF_PIXEL_CMYK_CHANNEL_ACCESSOR(magenta, green)
DEF_PIXEL_CMYK_CHANNEL_ACCESSOR(yellow, blue)
DEF_PIXEL_CMYK_CHANNEL_ACCESSOR(black, opacity)
```
Here is my demo code: [https://github.com/onlinetocode/rmagick_black_test](https://github.com/onlinetocode/rmagick_black_test)

**Comment by Watson1978** [comment]
Seems `Image#get_pixels` or `Image#each_pixel` just return RGB color even if image has CMYK profile.

**Comment by Watson1978** [comment]
I think we have  to map `black` to `index` value. What do you think about this ? @dlemstra 

```
DEF_PIXEL_CMYK_CHANNEL_ACCESSOR(black, index)
```
