### ISSUE TITLE
Cannot get accented characters from Image properties

### ISSUE THREAD

**Issue by chrilleferna** [rmagick/rmagick#761]
I use text strings with accented characters (Swedish å, ä and ö) in image captions. When reading the strings with rMagick (version 2.16.0, ruby 2.5) all accented characters are replaced by one or several dots ('.', hexa 2E).

To read the test string I use:
`image_description = image.properties["exif:ImageDescription"]`

**Comment by Watson1978** [comment]
Can you provide your image to reproduce the issue?

**Comment by chrilleferna** [comment]
![_DSC2396](https://user-images.githubusercontent.com/4245720/60166981-6bf3b100-9802-11e9-84de-3220a9044b29.jpg)

Wow, you reacted so quikly I didn't even notice!
This is just an image with test strings in Copyright and Description.
Both the Swedish characters and the newlines are replaced by '.'

**Comment by Watson1978** [comment]
```
$ irb
>> require 'rmagick'
=> true
>> image = Magick::Image.read('test-exif.jpg').first
=> test-exif.jpg JPEG 2226x2505 2226x2505+0+0 DirectClass 8-bit 2576kb
>> image.properties["exif:ImageDescription"]
=> "a\xC3\xA5\xC3..a\xC3\xA4\xC3..o\xC3\xB6\xC3."
>> image.properties["exif:ImageDescription"].force_encoding('UTF-8')
=> "aå\xC3..aä\xC3..oö\xC3."
```

Basically, RMagick just retrives the values using ImageMagick in Image#properties method.
If you set `UTF-8` encoding via `force_encoding`, you can get a part value of `exif:ImageDescription`...

However, if you retrive `exif:ImageDescription` using ImageMagick command like below, it also shows the broken string.

```
$ `brew --prefix imagemagick@6`/bin/identify -verbose test-exif.jpg | grep 'exif:ImageDescription'
    exif:ImageDescription: aå�..aä�..oö�.
```

I think this issue is not bug of RMagick.

Could you please report this issue to ImageMagick project instead ?
Thank you.

**Comment by chrilleferna** [comment]
Thanks Watson! I'll do

**Comment by chrilleferna** [comment]
In case somebody else has the same problem: The problem with reading accented characters (and newline) from EXIF data lies in ImageMagick, not in the rMagick GEM.

BUT I noticed that the information I was looking for (Caption and Copyright) is also present in the IPTC meta data, and when reading that, things work as they should.

So instead of reading the Caption like this:

`image.properties["exif:ImageDescription"]`

I read it as IPTC like this:

`image.get_iptc_dataset(Magick::IPTC::Application::Caption)`

Possible arguments to the get_iptc_dataset method can be found here: https://rmagick.github.io/image2.html#get_iptc_dataset
