### ISSUE TITLE
Memory Leaks with IM 7

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#800]
I've run RMagick tests with IM7.
Unfortunately some memory leaks are detected by profiler.

<img width="1392" alt="スクリーンショット 2019-09-23 23 06 19" src="https://user-images.githubusercontent.com/199156/65437232-6a1ba700-de5e-11e9-82c1-4d23ec2d10f6.png">

**Comment by dlemstra** [comment]
Do you also see this with the IM6 code? The method `MagickCoreTerminus` is not called in this project to cleanup some of the objects that are created when `MagickCoreGenesis` is called. That would explain some of the leaking. Is it possible to determine where/when the memory was allocated with the tool that you are using?

**Comment by Watson1978** [comment]
I think there are two more points that are marked as libMagickCore-6 with IM6.
(I was going to erase everything before...)

<img width="1392" alt="スクリーンショット_2019-09-23_22_59_45" src="https://user-images.githubusercontent.com/199156/65441733-dfd74100-de65-11e9-9e6f-4ea4b39c68d6.png">

**Comment by Watson1978** [comment]
## Leaks in `Image#store_pixels`

### Reproduction

```ruby
require 'rmagick'

@img = Magick::Image.new(20, 20)
pixels = @img.get_pixels(0, 0, @img.columns, 1)

1000000.times do
  # Without exception
  # res = @img.store_pixels(0, 0, @img.columns, 1, pixels)

  begin
    pixels[0] = 'x'
    @img.store_pixels(0, 0, @img.columns, 1, pixels)
    # => will raise exception
  rescue
  end
end

GC.start
rss = `ps -o rss= -p #{Process.pid}`.to_i / 1024
puts "Process: #{Process.pid}: RSS = #{rss} MB"
```

```
$ ruby store_pixel.rb
Process: 32569: RSS = 472 MB
```

## Description
If unexpected parameter was given, https://github.com/rmagick/rmagick/blob/339ad7468d5f48e3ca9c76a81f8b4df608a2b475/ext/RMagick/rmimage.c#L14080 will raise exception.

Then heap area allocated by `exception = AcquireExceptionInfo();` will causes memory leak.

**Comment by Watson1978** [comment]
## `Image#channel`

Related to https://github.com/rmagick/rmagick/blob/0728ae3256ef20959e04de169f94257e8e21f019/test/Image1.rb#L369-L371

### Reproduction

```ruby
require 'rmagick'

@img = Magick::Image.new(20, 20)

5000.times do
  Magick::ChannelType.values do |channel|
    @img.channel(channel)
  end
end

GC.start
rss = `ps -o rss= -p #{Process.pid}`.to_i / 1024
puts Magick::Long_version
puts "=" * 80
puts "Process: #{Process.pid}: RSS = #{rss} MB"
```

```
$ ruby channel.rb
This is RMagick 4.1.0.rc2 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 7.0.8-66 Q16 x86_64 2019-09-23 https://imagemagick.org
Built for ruby 2.6.4
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org
================================================================================
Process: 48426: RSS = 3314 MB
```

**Comment by Watson1978** [comment]
## `Image#selective_blur_channel`

Related to https://github.com/rmagick/rmagick/blob/0728ae3256ef20959e04de169f94257e8e21f019/test/Image3.rb#L425

### Reproduction

* Platform
  * ImageMagick 7

```ruby
require 'rmagick'

@img = Magick::Image.new(20, 20)

10000.times do
  @img.selective_blur_channel(0, 1, '10%')
end

GC.start
rss = `ps -o rss= -p #{Process.pid}`.to_i / 1024
puts Magick::Long_version
puts "=" * 80
puts "Process: #{Process.pid}: RSS = #{rss} MB"
```

```
$ ruby selective_blur_channel.rb
This is RMagick 4.1.0.rc2 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 7.0.8-66 Q16 x86_64 2019-09-23 https://imagemagick.org
Built for ruby 2.6.4
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org
================================================================================
Process: 48735: RSS = 443 MB
```

**Comment by Watson1978** [comment]
## `Drow#annotate`

Related to https://github.com/rmagick/rmagick/blob/0728ae3256ef20959e04de169f94257e8e21f019/test/Draw.rb#L190

### Description

If `nil` was given as `text`, `StringValuePtr(text)` will raise exception.
https://github.com/rmagick/rmagick/blob/0728ae3256ef20959e04de169f94257e8e21f019/ext/RMagick/rmdraw.c#L983

Then heap area allocated by `exception = AcquireExceptionInfo();` will cause memory leak.
https://github.com/rmagick/rmagick/blob/0728ae3256ef20959e04de169f94257e8e21f019/ext/RMagick/rmdraw.c#L982

### Reproduce

* Platform
  * ImageMagick 7

```ruby
require 'rmagick'
require 'timeout'
puts Magick::Long_version

@draw = Magick::Draw.new

Timeout.timeout(60) do
  loop do
    img = Magick::Image.new(10, 10)

    begin
      @draw.annotate(img, 0, 0, 0, 20, nil)
    rescue
    end

    GC.start
  end
end

rss = `ps -o rss= -p #{Process.pid}`.to_i / 1024
puts Magick::Long_version
puts "=" * 80
puts "Process: #{Process.pid}: RSS = #{rss} MB"
```

```
$ ruby annotate.rb
This is RMagick 4.1.0.rc2 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 7.0.8-66 Q16 x86_64 2019-09-23 https://imagemagick.org
Built for ruby 2.6.4
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org
This is RMagick 4.1.0.rc2 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 7.0.8-66 Q16 x86_64 2019-09-23 https://imagemagick.org
Built for ruby 2.6.4
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org
================================================================================
Process: 75251: RSS = 19 MB
```

**Comment by mockdeep** [comment]
@Watson1978 are we okay to close this?

**Comment by dlemstra** [comment]
We still need to fix some of the issues reported here. Will work on that tomorrow.

**Comment by dlemstra** [comment]
You found a memory leak inside ImageMagick 7 with the issue that you reported for `Image#selective_blur_channel`. This will be resolved in the next release. Good catch!
