### ISSUE TITLE
Pixel colors changed after image was written

### ISSUE THREAD

**Issue by victorfink** [rmagick/rmagick#807]
When I make a new image using the constitue method, and then writing the image, it appears that my pixels are changed when I read the new image. The code I use is in the screenshot below, as well as the first pixel of the old image and the new image.

![Capture d’écran 2019-09-26 à 19 38 08](https://user-images.githubusercontent.com/46131176/65711663-abe26280-e095-11e9-9d98-0e0f8bcb23c3.png)

I tried this on different images but the result is the same.

I didn't find anything about this on internet. Any clue about this ?

Thanks

**Comment by mockdeep** [comment]
@victorfink which versions of RMagick and ImageMagick are you using?

**Comment by dlemstra** [comment]
What is the format of your input image? I suspect it is something other than `JPEG`. You are seeing this because JPEG only supports 8 or 12 bit precision and I suspect that your libjpeg library uses 8-bitt. This means that your value `65534` will be saved as `65534/257.0 = 254.9 => 255` and when that is converted back to your 16-bit ImageMagick version the value will become `255 * 257.0 = 65535`

**Comment by victorfink** [comment]
Thanks for your responses.

Version: ImageMagick 6.9.10-66 Q16 x86_64 2019-09-23
rmagick (4.0.0)

It's strange because I tested this with JPEG files. I just tested the same code with PNG files and it works just fine.

**Comment by mockdeep** [comment]
@victorfink PNG files support 16 bit values, so there is no scaling happening. JPEG typically uses 8 bit precision, so when writing out to the file the values need to be scaled down to fit in 8 bits.

@dlemstra is there anything to be done here? Even though it makes sense what it's doing, it does seem a little bit confusing. When we're working with an image, do we always use 16 bit values in memory? I guess it probably wouldn't be worth adding some warning about the scaling that's happening...

**Comment by dlemstra** [comment]
We will not add a warning about this. There are too many places where this could happen.

**Comment by mockdeep** [comment]
Okay. @victorfink closing this for now. This is working as expected. Please let us know if there's some way we can make this more clear.
