### ISSUE TITLE
ImageList#combine generates different image with ImageMagick 7

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#891]
## Test code
```ruby
require 'rmagick'

image = Magick::ImageList.new
image.new_image(200, 200, Magick::SolidFill.new('red'))
image.new_image(200, 200, Magick::SolidFill.new('blue'))
image.new_image(200, 200, Magick::SolidFill.new('green'))

image.combine(Magick::CMYKColorspace).write('./combine.png')
```

### Result
with IM6 | with IM7
-- | --
<img src="https://user-images.githubusercontent.com/199156/71619700-fcbfa500-2c08-11ea-9662-98720bc1a753.png"> | <img src="https://user-images.githubusercontent.com/199156/71619709-05b07680-2c09-11ea-8497-496a9e996516.png">

**Comment by Watson1978** [comment]
@dlemstra Do you have any idea to fix this issue?

**Comment by dlemstra** [comment]
ImageMagick 7 was using only the gray channel instead of the pixel intensity of the image like we do in IM6. I just pushed a patch to IM7 to fix this. Thanks for reporting this.

**Comment by Watson1978** [comment]
@dlemstra Thank you for your work. I will check it later.

**Comment by Watson1978** [comment]
This issue will be solved by https://github.com/ImageMagick/ImageMagick/commit/acf024a71ff66deaa9439cc7b1deb8b0ce6481e2.

Thanks
