### ISSUE TITLE
circle.rb example generates different image with ImageMagick 7

### ISSUE THREAD

**Issue by Watson1978** [rmagick/rmagick#905]
## Test code
https://github.com/rmagick/rmagick/blob/master/doc/ex/circle.rb

### Result
with IM6 | with IM7
-- | --
<img src="https://user-images.githubusercontent.com/199156/71715977-9760f380-2e56-11ea-9966-9b5eb52753fb.gif"> | <img src="https://user-images.githubusercontent.com/199156/71715992-a3e54c00-2e56-11ea-9c8b-542a572147fc.gif">

**Comment by Watson1978** [comment]
I think this is problem in ImageMagick 7.

Once I set the opacity to 0 with `fill-opacity 0`,
it can't revert opacity even if I call `fill-opacity`.

I confirmed with following ImageMagick command.

```
$ imagemagick7.0/bin/convert -size 200x200 xc:lightblue \
-draw "fill-opacity 0 \
       stroke 'red' \
       stroke-width 3 \
       circle 125,125 25,125 \
       stroke-width 1 \
       stroke 'gray50' \
       circle 25,125 28,128 \
       fill-opacity 1 \
       circle 125,125 128,128 \
       font-weight normal \
       font-style normal \
       fill "black" \
       stroke "transparent" \
       font-size 72 \
       text 132,125 '125,125' \
       text 32,125 '25,125'" \
text_draw-70.gif
```

### Result
with IM6 | with IM7
-- | --
<img src="https://user-images.githubusercontent.com/199156/71740236-06623a80-2e9f-11ea-886f-d0f4cf0ea773.gif"> | <img src="https://user-images.githubusercontent.com/199156/71740255-124dfc80-2e9f-11ea-9180-ba537d650daf.gif">

<img width="1123" src="https://user-images.githubusercontent.com/199156/71740321-3b6e8d00-2e9f-11ea-86b0-dd2c89c48a21.png">

The text remains transparent with ImageMagick 7.


@dlemstra How to fix this problem ?

**Comment by Watson1978** [comment]
Once if `fill_alpha` becomes to 0, the value cannot be changed.
(Because `n` is always 0.)
```
            graphic_context[n]->fill_alpha*=opacity;
```
https://github.com/ImageMagick/ImageMagick/blob/2366d1b99bf2b0d1624695180145271655933ac5/MagickCore/draw.c#L2911

To solve this issue, I need following changing in ImageMagick 7.

```diff
diff --git a/MagickCore/draw.c b/MagickCore/draw.c
index 18312f0..b835dae 100644
--- a/MagickCore/draw.c
+++ b/MagickCore/draw.c
@@ -2908,7 +2908,7 @@ static MagickBooleanType RenderMVGContent(Image *image,
               StringToDouble(token,&next_token),0.0),1.0);
             if (token == next_token)
               ThrowPointExpectedException(token,exception);
-            graphic_context[n]->fill_alpha*=opacity;
+            graphic_context[n]->fill_alpha=(QuantumRange-graphic_context[n]->fill_alpha)*opacity;
             if (graphic_context[n]->fill.alpha != TransparentAlpha)
               graphic_context[n]->fill.alpha=graphic_context[n]->fill_alpha;
             else
```

@dlemstra What do you think above?

**Comment by Watson1978** [comment]
Hmmm, looks like it might not good...

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by Watson1978** [comment]
@urban-warrior Thanks!! I comfirmed the problem was solved with ImageMagick 7 master code.
