### ISSUE TITLE
RMagick 2.13.3 on Windows 7 x32 with ImageMagick 6.8.9-6 Q16 x86 

### ISSUE THREAD

**Issue by DHB** [rmagick/rmagick#93]
I assume this is also related to #39.
This is on

```
$ ruby -v && gem -v
ruby 2.0.0p353 (2013-11-22) [i386-mingw32]
2.0.14
```

I tried to upgrade to `RMagick 2.13.3` using latest `Version: ImageMagick 6.8.9-6 Q16 x86 2014-07-22` and got this error: https://gist.github.com/9cde39c97c17fe7ebe11

Tried to switch back to  `RMagick 2.13.2` , still using latest `Version: ImageMagick 6.8.9-6 Q16 x86 2014-07-22` and got this error: https://gist.github.com/73e248e229c493deaccf

An attempt to install `RMagick 2.13.3` using my previous `Version: ImageMagick 6.8.0-3 2012-10-24` worked fine.

```
$ gem install rmagick --version=2.13.3 --platform=ruby -- '--with-opt-lib="h:/ImageMagick-6.8.0-Q16/lib" --with-opt-include="h:/ImageMagick-6.8.0-Q16/include"'
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-opt-lib="h:/ImageMagick-6.8.0-Q16/lib" --with-opt-include="h:/ImageMagick-6.8.0-Q16/include"'
This could take a while...
Please report any bugs. See https://github.com/gemhome/rmagick/compare/RMagick_2-13-2...master and https://github.com/rmagick/rmagick/issues/18
Successfully installed rmagick-2.13.3
Parsing documentation for rmagick-2.13.3
Installing ri documentation for rmagick-2.13.3
Done installing documentation for rmagick after 20 seconds
1 gem installed
```

No big deal for the time being, I can live with it, NO urgency!

Since ImageMagick 6.8.9-6 Q16 looks a lot easier on allocating resources:

```
   File       Area     Memory        Map       Disk   Thread  Throttle       Time
 --------------------------------------------------------------------------------
   1536    6.976GB  3.2485GiB  6.4969GiB  unlimited        2         0  unlimited
```

and I'd love to maintain identical versions between my Linux test/production boxes and my Windows development, it would be nice to be able to upgrade to latest, greatest ImageMagick.

Is the issue related to ImageMagick and version (in)compatibility?

**Comment by ABaumgaertner** [comment]
take a look at #175

**Comment by mockdeep** [comment]
@DHB are you still having issues installing on Windows as of RMagick 3.0.0?

**Comment by mockdeep** [comment]
No response, so I'm closing this for now. If it still fails for you on RMagick >= 3.0, please open a new issue.
